#!/usr/bin/env bash
# Template: install-bash-custom-1.0.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare INST64_LIB_PATH="${INST64_LIB_PATH:-/opt/inst64}"
[[ ! -d "$INST64_LIB_PATH" && -d "${HOME}/at64/inst64" ]] && INST64_LIB_PATH="${HOME}/at64/inst64"
# shellcheck source-path=src disable=SC2015
source "${INST64_LIB_PATH}/lib-bash" ||
  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }

#
# Globals
#

# Installation method
declare INST64_X_APP_NAME_CAPS_X_METHOD="${INST64_X_APP_NAME_CAPS_X_METHOD:-CUSTOM}"
# Installation destination
declare INST64_X_APP_NAME_CAPS_X_TARGET="${INST64_X_APP_NAME_CAPS_X_TARGET:-}"
# Hardware architecture
declare INST64_X_APP_NAME_CAPS_X_PLATFORM="${INST64_X_APP_NAME_CAPS_X_PLATFORM:-}"
# Application version
declare INST64_X_APP_NAME_CAPS_X_VERSION="${INST64_X_APP_NAME_CAPS_X_VERSION:-latest}"

# App information
INST64_APP_NAME='X_APP_NAME_X'
INST64_APP_ID='X_APP_NAME_CAPS_X'
INST64_APP_FULL_NAME='X_APP_FULL_NAME_X'
# shellcheck disable=SC2034
INST64_SCRIPT_VERSION='1.0.0'
INST64_CLI_NAME='X_CLI_NAME_X'
INST64_CLI_PATH='X_CLI_CUSTOM_PATH_X'

#
# Functions
#

function inst64_prepare() {
  inst64_lib_step_prepare || return 0
  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
    : # X_PREPARE_PLACEHOLDER_X
  fi
}

function inst64_install() {
  inst64_lib_step_install || return 0
  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
    : # X_INSTALL_PLACEHOLDER_X
  fi
}

function inst64_setup() {
  inst64_lib_step_setup || return 0
  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
    : # X_SETUP_PLACEHOLDER_X
  fi
}

function inst64_verify() {
  inst64_lib_step_verify || return 0
  # X_VERIFY_PLACEHOLDER_X
}

function inst64_select_platform() {
  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
    : # X_PLATFORM_SELECTION_PLACEHOLDER_X
  fi
}

function inst64_select_packages() {
  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
    : # X_SELECT_PKG_PLACEHOLDER_X
  fi
  inst64_lib_package_check_definition
}

function inst64_initialize() {
  inst64_lib_base_initialize &&
    inst64_lib_app_check_method "$INST64_METHOD_CUSTOM" ||
    return $?

  # X_INIT_PLACEHOLDER_X
  # X_PRE_REQ_PLACEHOLDER_X

  inst64_select_platform &&
    inst64_select_packages ||
    return $?

  inst64_lib_app_check_installed && return 0
  inst64_lib_message_show_parameters
}

#
# Main
#

inst64_lib_task_process_start &&
  inst64_initialize &&
  inst64_prepare &&
  inst64_install &&
  inst64_setup &&
  inst64_verify
inst64_lib_task_process_finish $?
