---
repos:
  - repo: "local"
    hooks:
    -   id: "lint-bash"
        name: "Lint / Bash"
        entry: "bin/dev-lint-bash"
        language: script
        pass_filenames: true
        types:
          - "bash"
        files: "src/"
...
