#!/usr/bin/env bash

[[ ! -d /project ]] && echo 'Error: test for lab container only' && exit 1

declare TARGET='/opt'
declare TARGET_INST64="$TARGET/inst64"

[[ -d "$TARGET_INST64" ]] && sudo rm -Rf "$TARGET_INST64"
sudo mkdir "$TARGET_INST64" &&
  sudo cp -f /project/src/* "$TARGET_INST64"
