# X_PLATFORM_SELECTION_PLACEHOLDER_X
    if [[ -z "$INST64_X_APP_NAME_CAPS_X_PLATFORM" ]]; then
      # X_PLATFORM_SELECTION_PLACEHOLDER_X
      INST64_X_APP_NAME_CAPS_X_PLATFORM="$INST64_CPU_ALL_ALL"
    fi
    inst64_lib_platform_check_cpu
