# X_CASE_X
      "$BL64_OS_FLAVOR_ARCH" \
      "$BL64_OS_FLAVOR_ALPINE" \
      "$BL64_OS_FLAVOR_DEBIAN" \
      "$BL64_OS_FLAVOR_FEDORA" \
      "$BL64_OS_FLAVOR_MACOS" \
      "$BL64_OS_FLAVOR_REDHAT" \
      "$BL64_OS_FLAVOR_SUSE" ||
