# X_PRE_OS_PLACEHOLDER_X
    bl64_os_check_compatibility \
      "${BL64_OS_ALM}" \
      "${BL64_OS_ALP}" \
      "${BL64_OS_AMZ}" \
      "${BL64_OS_CNT}" \
      "${BL64_OS_DEB}" \
      "${BL64_OS_FD}" \
      "${BL64_OS_KL}" \
      "${BL64_OS_MCOS}" \
      "${BL64_OS_OL}" \
      "${BL64_OS_RCK}" \
      "${BL64_OS_RHEL}" \
      "${BL64_OS_SLES}" \
      "${BL64_OS_UB}" \
