#!/usr/bin/env bash
# Template: install-bash-1.0.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare INST64_LIB_PATH="${INST64_LIB_PATH:-/opt/inst64}"
[[ ! -d "$INST64_LIB_PATH" && -d "${HOME}/at64/inst64" ]] && INST64_LIB_PATH="${HOME}/at64/inst64"
# shellcheck source-path=src disable=SC2015
source "${INST64_LIB_PATH}/lib-bash" ||
  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }

#
# Globals
#

# Installation method
declare INST64_X_APP_NAME_CAPS_X_METHOD="${INST64_X_APP_NAME_CAPS_X_METHOD:-X_METHOD_X}"
# Installation destination
declare INST64_X_APP_NAME_CAPS_X_TARGET="${INST64_X_APP_NAME_CAPS_X_TARGET:-}"
# Hardware architecture
declare INST64_X_APP_NAME_CAPS_X_PLATFORM="${INST64_X_APP_NAME_CAPS_X_PLATFORM:-}"
# Application version
declare INST64_X_APP_NAME_CAPS_X_VERSION="${INST64_X_APP_NAME_CAPS_X_VERSION:-latest}"

# App information
INST64_APP_NAME='X_APP_NAME_X'
INST64_APP_ID='X_APP_NAME_CAPS_X'
INST64_APP_FULL_NAME='X_APP_FULL_NAME_X'
# CLI information
INST64_CLI_NAME='X_CLI_NAME_X'
INST64_CLI_PATH='X_CLI_CUSTOM_PATH_X'
# shellcheck disable=SC2034
INST64_SCRIPT_VERSION='1.0.0'

# Source repository
INST64_WEB_REPO_URL='X_REPO_URL_X'
INST64_WEB_REPO_PATH='X_REPO_PATH_X'
INST64_WEB_REPO_API='X_REPO_API_X'

#
# Functions
#

function inst64_lib_prepare() {
  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 0
  inst64_lib_message_show_task 'prepare deployment'
  inst64_lib_base_create_path
  if [[ ! -d "$INST64_X_APP_NAME_CAPS_X_TARGET" ]]; then
    mkdir -p "$INST64_X_APP_NAME_CAPS_X_TARGET" &&
      chmod "$INST64_TARGET_MODE_DIR" "$INST64_X_APP_NAME_CAPS_X_TARGET"
  fi
}

function inst64_lib_install() {
  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 0
  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
    : # X_INSTALL_PLACEHOLDER_X
  fi
}

function inst64_lib_verify() {
  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 0
  inst64_lib_message_show_task 'verify deployment'
  # X_VERIFY_PLACEHOLDER_X
}

inst64_lib_select_platform() {
  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
    if [[ -z "$INST64_X_APP_NAME_CAPS_X_PLATFORM" ]]; then
      : # X_PLATFORM_SELECTION_PLACEHOLDER_X
    fi
  fi
  [[ -z "$INST64_X_APP_NAME_CAPS_X_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
  return 0
}

function inst64_lib_select_packages() {
  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
    : # X_SELECT_PKG_PLACEHOLDER_X
  fi
  [[ -z "$INST64_X_APP_NAME_CAPS_X_VERSION" ]] && echo 'Error: unable to determine package version' && return 1
  [[ -z "$INST64_PKG_MAIN" ]] && echo 'Error: unable to determine package name' && return 1
  return 0
}

function inst64_lib_initialize() {
  inst64_lib_base_initialize &&
    inst64_lib_app_check_method 'X_METHOD_X' ||
    return $?

  # X_INIT_PLACEHOLDER_X
  # X_PRE_REQ_PLACEHOLDER_X

  inst64_X_APP_NAME_X_select_platform &&
    inst64_X_APP_NAME_X_select_packages ||
    return $?

  inst64_lib_app_check_installed && return 0
  inst64_lib_show_parameters
}

#
# Main
#

declare -i inst64_script_status=0

inst64_lib_message_show_process "[${0}] started"

[[ -n "$INST64_DEBUG" ]] && set -x
inst64_lib_initialize &&
  inst64_lib_prepare &&
  inst64_lib_install &&
  inst64_lib_verify
inst64_script_status=$?

# shellcheck disable=SC2015
((inst64_script_status == 0)) &&
  inst64_lib_message_show_process "[${0}] finished successfully" ||
  inst64_lib_message_show_process "[${0}] finished with errors: exit-status-${inst64_script_status}"
# shellcheck disable=SC2086
exit $inst64_script_status
