#!/usr/bin/env bash
# Template: install-bl64-custom-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
# X_IMPORTS_PLACEHOLDER_X
source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64"

#
# Globals
#

# Installation method
declare INST64_X_APP_NAME_CAPS_X_METHOD="${INST64_X_APP_NAME_CAPS_X_METHOD:-AUTO}"
# optional # # Installation destination
# optional # declare INST64_X_APP_NAME_CAPS_X_TARGET="${INST64_X_APP_NAME_CAPS_X_TARGET:-}"
# optional # # Hardware architecture
# optional # declare INST64_X_APP_NAME_CAPS_X_PLATFORM="${INST64_X_APP_NAME_CAPS_X_PLATFORM:-}"
# optional # # Application version
# optional # declare INST64_X_APP_NAME_CAPS_X_VERSION="${INST64_X_APP_NAME_CAPS_X_VERSION:-latest}"
# optional # # Enable development packages?
# optional # declare INST64_X_APP_NAME_CAPS_X_DEVELOPMENT="${INST64_X_APP_NAME_CAPS_X_DEVELOPMENT:-NO}"

# App information
INST64_APP_NAME='X_APP_NAME_X'
INST64_APP_ID='X_APP_NAME_CAPS_X'
INST64_APP_FULL_NAME='X_APP_FULL_NAME_X'
INST64_CLI_NAME='X_CLI_NAME_X'
# optional # INST64_APP_DOC_SETUP='X_DOC_SETUP_URL_X'
# optional # INST64_APP_DOC_INSTALL='X_DOC_INSTALL_URL_X'

# X_GLOBALS_METHOD_PLACEHOLDER_X

#
# Functions
#

# X_STAND_ALONE_FUNCTIONS_X #

function my_install_custom() {
  bl64_dbg_app_show_function
  # X_INSTALL_CUSTOM_PLACEHOLDER_X
}

function my_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_prepare || return 0
  # X_PREPARE_PLACEHOLDER_X
  # optional # if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
  # optional #   inst64_lib_base_create_path
  # optional # fi
}

function my_install() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_install || return 0
  # X_INSTALL_PLACEHOLDER_X
  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
    my_install_custom
  fi
}

function my_setup() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_setup || return 0
  # X_SETUP_PLACEHOLDER_X
  # optional # if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
  # optional #   inst64_lib_show_task_publish
  # optional #   inst64_lib_setup_promote
  # optional # fi
}

function my_verify() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_verify || return 0
  # X_VERIFY_PLACEHOLDER_X
  # example # "${INST64_CLI_TARGET}" --version
}

function my_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_method_check \
    "$INST64_METHOD_AUTO" \
    "$INST64_METHOD_CUSTOM" ||
    return $?
  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_AUTO" ]]; then
    INST64_X_APP_NAME_CAPS_X_METHOD="$INST64_METHOD_CUSTOM"
  fi
  # optional # if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
  # optional #   INST64_SYSTEM_WIDE='NO'
  # optional # fi
}

function my_select_platform() {
  bl64_dbg_app_show_function
  inst64_lib_show_task_select_platform
  # X_PLATFORM_SELECTION_PLACEHOLDER_X
  # optional # if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
  # optional #   if [[ -z "$INST64_X_APP_NAME_CAPS_X_PLATFORM" ]]; then
  # optional #     INST64_X_APP_NAME_CAPS_X_PLATFORM="$INST64_CPU_ALL_ALL"
  # optional #   fi
  # optional #   inst64_lib_base_check_platform
  # optional # fi
  # optional # return 0
}

function my_select_packages() {
  bl64_dbg_app_show_function
  inst64_lib_show_task_select_packages
  # X_SELECT_PKG_PLACEHOLDER_X
  # optional # if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
  # optional #   :
  # optional # fi
  # optional # inst64_lib_base_check_package
}

function my_initialize() {
  bl64_dbg_app_show_function
  my_select_method &&
    inst64_lib_base_setup ||
    return $?

  # X_INIT_PLACEHOLDER_X
  # optional # if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
  # optional #   inst64_lib_base_check_prereq_exe 'X_COMMAND_NAME_X'
  # optional # fi

  my_select_platform &&
    my_select_packages ||
    return $?

  # X_INIT_PLACEHOLDER_X
  # optional # if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
  # optional #   INST64_CLI_PATH='X_PATH_DIR_X'
  # optional #   INST64_CLI_SOURCE="X_CUSTOM_CLI_NAME"
  # optional #   INST64_CLI_SUBPATH='X_CUSTOM_CLI_SUBPATH_X'
  # optional #   INST64_CLI_TARGET='X_PATH_FILE_X'
  # optional #   INST64_WEB_REPO_PATH="X_CUSTOM_URL_X"
  # optional #   INST64_WORK_PATH_SOURCE="X_CUSTOM_FILE_NAME_X"
  # optional # fi

  inst64_lib_base_finalize
}

#
# Main
#

bl64_lib_script_version_set '1.0.0'
inst64_lib_base_initialize
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_initialize &&
  my_prepare &&
  my_install &&
  my_setup &&
  my_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
