INST64_PKG_MAIN='X_PACKAGE_NAME_PLACEHOLDER_X'
    # INST64_PKG_MAIN="${package_prefix}${INST64_X_APP_NAME_CAPS_X_PLATFORM}${package_suffix}"
    # INST64_PKG_MAIN="${package_prefix}_${INST64_X_APP_NAME_CAPS_X_VERSION#v}_${INST64_X_APP_NAME_CAPS_X_PLATFORM}${package_suffix}"
    # INST64_PKG_MAIN="${package_prefix}_${INST64_X_APP_NAME_CAPS_X_VERSION}_${INST64_X_APP_NAME_CAPS_X_PLATFORM}${package_suffix}"
