INST64_X_APP_NAME_CAPS_X_PACKAGES='X_PACKAGE_NAME_PLACEHOLDER_X'
    # INST64_X_APP_NAME_CAPS_X_PACKAGES="${package_prefix}${INST64_X_APP_NAME_CAPS_X_PLATFORM}${package_sufix}"
    # INST64_X_APP_NAME_CAPS_X_PACKAGES="${package_prefix}_${INST64_X_APP_NAME_CAPS_X_VERSION#v}_${INST64_X_APP_NAME_CAPS_X_PLATFORM}${package_sufix}"
    # INST64_X_APP_NAME_CAPS_X_PACKAGES="${package_prefix}_${INST64_X_APP_NAME_CAPS_X_VERSION}_${INST64_X_APP_NAME_CAPS_X_PLATFORM}${package_sufix}"
