#!/usr/bin/env bash
# Template: 1.2.0
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 1.1.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Base Installer64 parameters
export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
export INST64_DEBUG="${INST64_DEBUG:-}"
export INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
export INST64_TMP="${INST64_TMP:-/tmp}"

# shellcheck source=SCRIPTDIR/../lib/bashlib64.bash
source "$INST64_BASHLIB64" || { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Installation method
export INST64_AZURECLI_METHOD="${INST64_AZURECLI_METHOD:-EXTERNAL}"

export INST64_AZURECLI_REPOSITORY_NAME='azure-cli'
export INST64_AZURECLI_SOURCE_RHEL='https://packages.microsoft.com/config/rhel'
export INST64_AZURECLI_SOURCE_DEB='https://packages.microsoft.com/repos/azure-cli'
export INST64_AZURECLI_REPOSITORY_KEY_DEB='https://packages.microsoft.com/keys/microsoft.asc'

#
# Functions
#

function inst64_azurecli_select_packages() {
  bl64_dbg_app_show_function
  local packages=''
  if bl64_os_match "${BL64_OS_OL}"; then
    packages='azure-cli'
  elif bl64_os_match "${BL64_OS_UB}"; then
    packages='azure-cli'
  fi
  [[ -n "$packages" ]] && echo "$packages"
}

function inst64_azurecli_add_repository() {
  bl64_dbg_app_show_function
  local repository_url=''
  local repository_key=''
  local repository_extra_1=''
  local repository_extra_2=''
  local repository_key_file='/etc/apt/keyrings/microsoft.gpg'

  bl64_msg_show_task 'Add external package repository'
  if bl64_os_match "${BL64_OS_OL}"; then
    repository_url="${INST64_AZURECLI_SOURCE_RHEL}/9.0/packages-microsoft-prod.rpm"
    bl64_pkg_deploy "$repository_url"
  elif bl64_os_match "${BL64_OS_UB}"; then
    repository_url="$INST64_AZURECLI_SOURCE_DEB"
    repository_key="$INST64_AZURECLI_REPOSITORY_KEY_DEB"
    repository_extra_2='main'
    bl64_rxtx_run_curl -sLS "$repository_key" |
      gpg --dearmor | "$BL64_OS_CMD_TEE" "$repository_key_file" >/dev/null &&
      bl64_fs_run_chmod go+r "$repository_key_file" &&
      repository_extra_1="$(lsb_release -cs)" &&
      echo "deb [signed-by=${repository_key_file}] ${repository_url} ${repository_extra_1} ${repository_extra_2}" |
      "$BL64_OS_CMD_TEE" /etc/apt/sources.list.d/${INST64_AZURECLI_REPOSITORY_NAME}.list >/dev/null
  fi
}

function inst64_azurecli_install_external_packages() {
  bl64_dbg_app_show_function
  local packages=''

  inst64_azurecli_add_repository ||
    return $?

  bl64_msg_show_task 'deploy packages'
  packages="$(inst64_azurecli_select_packages)" ||
    return $?
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_azurecli_install() {
  bl64_dbg_app_show_function
  if [[ "$INST64_AZURECLI_METHOD" == 'EXTERNAL' ]]; then
    inst64_azurecli_install_external_packages
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function inst64_azurecli_initialize() {
  bl64_dbg_app_show_function
  bl64_os_check_version \
    "${BL64_OS_UB}-22" \
    "${BL64_OS_OL}-9" &&
    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_AZURECLI_METHOD' \
      "$INST64_AZURECLI_METHOD" \
      'EXTERNAL' &&
    bl64_check_privilege_root &&
    bl64_pkg_setup
}

#
# Main
#

declare inst64_azurecli_installer_description='Install application: Azure CLI'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_azurecli_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_lib_enable
inst64_azurecli_initialize &&
  inst64_azurecli_install
bl64_msg_show_batch_finish $? "$inst64_azurecli_installer_description"
