#!/usr/bin/env bash
# Template: 1.2.0
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 2.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
# Enable debugging? Set to YES to enable
export INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Base path for 3rd party applications
export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"

# shellcheck source=SCRIPTDIR/../lib/bashlib64.bash
source "$INST64_BASHLIB64" || { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Installation method
export INST64_SHELLCHECK_METHOD="${INST64_SHELLCHECK_METHOD:-NATIVE}"

#
# Functions
#

function inst64_shellcheck_select_packages() {
  bl64_dbg_app_show_function
  local packages=''
  if bl64_os_match "${BL64_OS_ALP}"; then
    packages='shellcheck'
  elif bl64_os_match "${BL64_OS_UB}"; then
    packages='shellcheck'
  fi
  [[ -n "$packages" ]] && echo "$packages"
}

function inst64_shellcheck_install_os_packages() {
  bl64_dbg_app_show_function
  local packages=''

  bl64_msg_show_task 'deploy packages'
  packages="$(inst64_shellcheck_select_packages)" ||
    return $?
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_shellcheck_install() {
  bl64_dbg_app_show_function

  if [[ "$INST64_SHELLCHECK_METHOD" == 'NATIVE' ]]; then
    inst64_shellcheck_install_os_packages
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function inst64_shellcheck_initialize() {
  bl64_dbg_app_show_function

  bl64_os_check_version \
    "${BL64_OS_ALP}-3" \
    "${BL64_OS_UB}-22" &&
    bl64_check_privilege_root &&
    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_SHELLCHECK_METHOD' \
      "$INST64_SHELLCHECK_METHOD" \
      'NATIVE' &&
    bl64_pkg_setup
}

#
# Main
#

declare inst64_shellcheck_installer_description='Install application: Shellcheck'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_shellcheck_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_shellcheck_initialize &&
  inst64_shellcheck_install

bl64_msg_show_batch_finish $? "$inst64_shellcheck_installer_description"
