#!/usr/bin/env bash
# Template: 2.0.1
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 1.3.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
# Enable debugging? Set to YES to enable
export INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Base path for 3rd party applications
export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
# Location for temporary files
export INST64_TMP="${INST64_TMP:-/tmp}"

# shellcheck source=lib/bl64/bashlib64.bash
source "${INST64_BASHLIB64}/bashlib64.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

export INST64_KUBECTL_PLATFORM="${INST64_KUBECTL_PLATFORM:-linux/amd64}"
export INST64_KUBECTL_SOURCE="${INST64_KUBECTL_SOURCE:-https://dl.k8s.io/release}"
export INST64_KUBECTL_TARGET="${INST64_KUBECTL_TARGET:-${INST64_OPT_ROOT}/kubectl}"
export INST64_KUBECTL_VERSION="${INST64_KUBECTL_VERSION:-stable}"
# Install system wide? Requires root privilege
export INST64_KUBECTL_SYSTEM_WIDE="${INST64_KUBECTL_SYSTEM_WIDE:-YES}"
# Installation method
export INST64_KUBECTL_METHOD="${INST64_KUBECTL_METHOD:-CUSTOM}"

export INST64_KUBECTL_PACKAGE_URL=''
export INST64_KUBECTL_INSTALLER=''
export INST64_KUBECTL_PACKAGES=''
export INST64_KUBECTL_CLI_NAME='kubectl'
export INST64_KUBECTL_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_KUBECTL_CLI_NAME}"

#
# Functions
#

function inst64_kubectl_install_custom_package() {
  bl64_dbg_app_show_function
  local app_target_mode='0755'
  local app_target_owner='root'
  local app_cli_source="${INST64_KUBECTL_CLI_NAME}-${INST64_KUBECTL_VERSION}"

  bl64_msg_show_task 'deploy application'
  bl64_lib_flag_is_enabled "$INST64_KUBECTL_SYSTEM_WIDE" || app_target_owner="$BL64_VAR_DEFAULT"
  bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_KUBECTL_TARGET" &&
    bl64_rxtx_web_get_file \
      "${INST64_KUBECTL_PACKAGE_URL}/${INST64_KUBECTL_PACKAGES}" "${INST64_KUBECTL_TARGET}/${app_cli_source}" "$BL64_VAR_OFF" "$app_target_mode" ||
    return $?

  bl64_lib_flag_is_enabled "$INST64_KUBECTL_SYSTEM_WIDE" || INST64_KUBECTL_CLI_PATH="${INST64_KUBECTL_TARGET}/${INST64_KUBECTL_CLI_NAME}"
  bl64_msg_show_task "publish application to searchable path (${INST64_KUBECTL_CLI_PATH})"
  bl64_fs_create_symlink \
      "${INST64_KUBECTL_TARGET}/${app_cli_source}" "$INST64_KUBECTL_CLI_PATH" "$BL64_VAR_ON"
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_kubectl_install() {
  bl64_dbg_app_show_function
  inst64_kubectl_select_packages || return $?
  if [[ "$INST64_KUBECTL_METHOD" == 'CUSTOM' ]]; then
    inst64_kubectl_install_custom_package
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_kubectl_select_packages() {
  bl64_dbg_app_show_function
  local package_prefix=''
  local package_sufix=''
  if [[ "$INST64_KUBECTL_METHOD" == 'CUSTOM' ]]; then
    if [[ "$INST64_KUBECTL_VERSION" == 'stable' ]]; then
      INST64_KUBECTL_VERSION="$(bl64_rxtx_run_curl $BL64_RXTX_SET_CURL_SILENT $BL64_RXTX_SET_CURL_REDIRECT "${INST64_KUBECTL_SOURCE}/stable.txt")"
      [[ -z "$INST64_KUBECTL_VERSION" ]] && bl64_msg_show_error 'unable to determine package version' && return 1
      INST64_KUBECTL_VERSION="${INST64_KUBECTL_VERSION#v}"
    fi
    package_prefix='kubectl'
    package_sufix=''
    INST64_KUBECTL_PACKAGES="${package_prefix}${package_sufix}"
    INST64_KUBECTL_PACKAGE_URL="${INST64_KUBECTL_SOURCE}/v${INST64_KUBECTL_VERSION}/bin/${INST64_KUBECTL_PLATFORM}"
  fi
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_kubectl_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
  bl64_arc_setup
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_kubectl_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  if [[ "$INST64_KUBECTL_METHOD" == 'CUSTOM' ]]; then
    "$INST64_KUBECTL_CLI_PATH" version --client=true
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_kubectl_initialize() {
  bl64_dbg_app_show_function
  if bl64_lib_flag_is_enabled "$INST64_KUBECTL_SYSTEM_WIDE"; then
    bl64_check_privilege_root ||
      return $?
  fi
  bl64_os_check_version \
    "${BL64_OS_ALP}-3" \
    "${BL64_OS_OL}-9" \
    "${BL64_OS_UB}-22" &&
    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_KUBECTL_METHOD' \
      "$INST64_KUBECTL_METHOD" \
      'CUSTOM'
}

#
# Main
#

declare inst64_kubectl_installer_description='Install application: KubeCTL'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_kubectl_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_kubectl_initialize &&
  inst64_kubectl_prepare &&
  inst64_kubectl_install &&
  inst64_kubectl_verify
bl64_msg_show_batch_finish $? "$inst64_kubectl_installer_description"
