#!/usr/bin/env bash
# Template: 2.2.0
# Snippet: install-custom-package-4.2.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Home root
declare INST64_HOME="${HOME}/at64"
# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
# shellcheck source-path=lib/bl64 disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Enable debugging? Set to YES to enable
declare INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Location for temporary files
declare INST64_TMP="${INST64_TMP:-/tmp}"
# Base path for 3rd party applications
declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
# Install system wide? Requires root privilege
declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"

declare INST64_NODEJS_PLATFORM="${INST64_NODEJS_PLATFORM:-}"
declare INST64_NODEJS_SOURCE="${INST64_NODEJS_SOURCE:-https://nodejs.org/dist}"
declare INST64_NODEJS_TARGET="${INST64_NODEJS_TARGET:-}"
declare INST64_NODEJS_VERSION="${INST64_NODEJS_VERSION:-20.10.0}"
# Installation method
declare INST64_NODEJS_METHOD="${INST64_NODEJS_METHOD:-CUSTOM}"

declare INST64_NODEJS_PACKAGE_URL=''
declare INST64_NODEJS_INSTALLER=''
declare INST64_NODEJS_PACKAGES=''
declare INST64_NODEJS_CLI_NAME_NODE='node'
declare INST64_NODEJS_CLI_NAME_NPM='npm'
declare INST64_NODEJS_CLI_NAME_NPX='npx'
declare INST64_NODEJS_CLI_PATH=''

#
# Functions
#

function inst64_nodejs_install_custom_package() {
  bl64_dbg_app_show_function
  local work_path=''
  local app_target_mode='0755'
  local app_target_owner='root'
  local app_cli_source="${INST64_NODEJS_PACKAGES%.tar.gz}/bin"
  local app_component=''

  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    INST64_NODEJS_CLI_PATH="${INST64_LOCAL_BIN}"
  else
    INST64_NODEJS_CLI_PATH="${INST64_NODEJS_TARGET}/bin"
    app_target_owner="$BL64_VAR_DEFAULT"
  fi

  bl64_msg_show_task 'download application'
  work_path="$(bl64_fs_create_tmpdir)" &&
    bl64_rxtx_web_get_file \
      "${INST64_NODEJS_PACKAGE_URL}/${INST64_NODEJS_PACKAGES}" "${work_path}/${INST64_NODEJS_PACKAGES}" ||
    return $?

  bl64_msg_show_task 'deploy application'
  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_NODEJS_TARGET" &&
    bl64_arc_open_tar "${work_path}/${INST64_NODEJS_PACKAGES}" "${INST64_NODEJS_TARGET}" ||
    return $?

  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    bl64_msg_show_task "publish application to searchable path (${INST64_NODEJS_CLI_PATH})"
    for app_component in "$INST64_NODEJS_CLI_NAME_NODE" "$INST64_NODEJS_CLI_NAME_NPM" "$INST64_NODEJS_CLI_NAME_NPX"; do
      bl64_fs_symlink_create \
        "${INST64_NODEJS_TARGET}/${app_cli_source}/$app_component" "${INST64_NODEJS_CLI_PATH}/${app_component}" "$BL64_VAR_ON" ||
        return $?
    done
  else
    bl64_msg_show_task "publish generic application name (${INST64_NODEJS_CLI_PATH})"
    bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_NODEJS_CLI_PATH" ||
      return $?
    for app_component in "$INST64_NODEJS_CLI_NAME_NODE" "$INST64_NODEJS_CLI_NAME_NPM" "$INST64_NODEJS_CLI_NAME_NPX"; do
      bl64_fs_symlink_create \
        "${INST64_NODEJS_TARGET}/${app_cli_source}/$app_component" "${INST64_NODEJS_CLI_PATH}/${app_component}" "$BL64_VAR_ON" ||
        return $?
    done
  fi

  bl64_msg_show_task 'cleanup temporary files'
  bl64_fs_rm_tmpdir "$work_path"
  return 0
}

#######################################
# Selects platform ID
#
# * Platform ID format is defined by the package provider
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Platform ID
# Returns:
#   0: selection completed ok
#   >0: unable to selection
#######################################
function inst64_nodejs_select_platform() {
  bl64_dbg_app_show_function
  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
    [[ -z "$INST64_NODEJS_PLATFORM" ]] && INST64_NODEJS_PLATFORM='linux-x64'
  fi
  [[ -z "$INST64_NODEJS_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_nodejs_install() {
  bl64_dbg_app_show_function
  inst64_nodejs_select_platform &&
    inst64_nodejs_select_packages ||
    return $?
  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
    inst64_nodejs_install_custom_package
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_nodejs_select_packages() {
  bl64_dbg_app_show_function
  local package_prefix=''
  local package_sufix=''
  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
    package_prefix='node-'
    package_sufix='.tar.gz'
    INST64_NODEJS_PACKAGES="${package_prefix}v${INST64_NODEJS_VERSION}-${INST64_NODEJS_PLATFORM}${package_sufix}"
    INST64_NODEJS_PACKAGE_URL="${INST64_NODEJS_SOURCE}/v${INST64_NODEJS_VERSION}"
    [[ -z "$INST64_NODEJS_PACKAGE_URL" ]] && bl64_msg_show_error 'unable to determine package download URL' && return 1
  fi
  [[ -z "$INST64_NODEJS_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_nodejs_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
    bl64_arc_setup
  fi
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_nodejs_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  "${INST64_NODEJS_CLI_PATH}/${INST64_NODEJS_CLI_NAME_NODE}" --version &&
    "${INST64_NODEJS_CLI_PATH}/${INST64_NODEJS_CLI_NAME_NPM}" --version &&
    "${INST64_NODEJS_CLI_PATH}/${INST64_NODEJS_CLI_NAME_NPX}" --version
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_nodejs_initialize() {
  bl64_dbg_app_show_function
  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
    INST64_SYSTEM_WIDE='NO'
  fi
  if [[ -z "$INST64_OPT_ROOT" ]]; then
    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
  fi
  INST64_NODEJS_TARGET="${INST64_NODEJS_TARGET:-${INST64_OPT_ROOT}/nodejs}"
  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_NODEJS_METHOD' \
    "$INST64_NODEJS_METHOD" \
    'CUSTOM' ||
    return $?

  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
      bl64_check_privilege_root ||
        return $?
    fi
    bl64_os_check_compatibility \
      "${BL64_OS_UB}" \
      "${BL64_OS_OL}" \
      "${BL64_OS_FD}"
  fi
  bl64_msg_show_setup 'Install application: NodeJS' \
    'INST64_SYSDEN64_METHOD' 'INST64_SYSTEM_WIDE' 
}

#
# Main
#

bl64_lib_script_version_set '1.2.0'
bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_nodejs_initialize &&
  inst64_nodejs_prepare &&
  inst64_nodejs_install &&
  inst64_nodejs_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
