#!/usr/bin/env bash
# Template: install-python-2.4.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Home root
declare INST64_HOME="${HOME}/at64"
# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
# shellcheck source-path=lib/bl64 disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-py.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Enable debugging? Set to YES to enable
declare INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Location for temporary files
declare INST64_TMP="${INST64_TMP:-/tmp}"
# Base path for 3rd party applications
declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
# Install system wide? Requires root privilege
declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"

declare INST64_BANDIT_VERSION="${INST64_BANDIT_VERSION:-latest}"
# Installation method
declare INST64_BANDIT_METHOD="${INST64_BANDIT_METHOD:-PIP}"

declare INST64_BANDIT_PIPX_BIN="${INST64_BANDIT_PIPX_BIN:-pipx}"
declare INST64_BANDIT_PACKAGES=''
declare INST64_BANDIT_PACKAGES_PRE=''
declare INST64_BANDIT_PACKAGES_POST=''
declare INST64_BANDIT_CLI_NAME='bandit'
declare INST64_BANDIT_CLI_PATH=''

#
# Functions
#

function inst64_bandit_install_with_pip() {
  bl64_dbg_app_show_function

  bl64_msg_show_task 'deploy application'
  if [[ -n "$INST64_BANDIT_PACKAGES_PRE" ]]; then
    # shellcheck disable=SC2086
    bl64_py_pip_usr_install $INST64_BANDIT_PACKAGES_PRE ||
      return $?
  fi
  # shellcheck disable=SC2086
  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    bl64_py_pip_usr_deploy $INST64_BANDIT_PACKAGES ||
    return $?
  if [[ -n "$INST64_BANDIT_PACKAGES_POST" ]]; then
    # shellcheck disable=SC2086
    bl64_py_pip_usr_install $INST64_BANDIT_PACKAGES_POST ||
      return $?
  fi
  return 0
}

function inst64_bandit_install_with_pipx() {
  bl64_dbg_app_show_function

  bl64_msg_show_task 'deploy application'
  if [[ -n "$INST64_BANDIT_PACKAGES_PRE" ]]; then
    # shellcheck disable=SC2086
    "$INST64_BANDIT_PIPX_BIN" install --preinstall $INST64_BANDIT_PACKAGES_PRE $INST64_BANDIT_PACKAGES ||
      return $?
  else
    # shellcheck disable=SC2086
    "$INST64_BANDIT_PIPX_BIN" inject $INST64_BANDIT_PACKAGES $INST64_BANDIT_PACKAGES_PRE ||
      return $?
  fi
  if [[ -n "$INST64_BANDIT_PACKAGES_POST" ]]; then
    # shellcheck disable=SC2086
    "$INST64_BANDIT_PIPX_BIN" inject $INST64_BANDIT_PACKAGES $INST64_BANDIT_PACKAGES_POST ||
      return $?
  fi
  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_bandit_install() {
  bl64_dbg_app_show_function
  if [[ "$INST64_BANDIT_METHOD" == 'PIPX' ]]; then
    inst64_bandit_install_with_pipx
  elif [[ "$INST64_BANDIT_METHOD" == 'PIP' ]]; then
    inst64_bandit_install_with_pip
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_bandit_select_packages() {
  bl64_dbg_app_show_function
  local version_target=''

  if [[ "$INST64_BANDIT_METHOD" == 'PIPX' || "$INST64_BANDIT_METHOD" == 'PIP' ]]; then
    if [[ "$INST64_BANDIT_VERSION" == 'latest' ]]; then
      version_target=''
    else
      version_target="==${INST64_BANDIT_VERSION}.*"
    fi
    INST64_BANDIT_PACKAGES="bandit${version_target}"
    INST64_BANDIT_PACKAGES_PRE=''
    INST64_BANDIT_PACKAGES_POST=''
    if [[ "$INST64_BANDIT_METHOD" == 'PIP' ]]; then
      INST64_BANDIT_CLI_PATH="${BL64_BSH_XDG_PATH_BIN}/${INST64_BANDIT_CLI_NAME}"
    elif [[ "$INST64_BANDIT_METHOD" == 'PIPX' ]]; then
      INST64_BANDIT_CLI_PATH="${INST64_BANDIT_CLI_NAME}"
    fi
  fi
  [[ -z "$INST64_BANDIT_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_bandit_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
  if [[ "$INST64_BANDIT_METHOD" == 'PIPX' || "$INST64_BANDIT_METHOD" == 'PIP' ]]; then
    bl64_py_setup
  fi
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_bandit_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  "$INST64_BANDIT_CLI_PATH" --version
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_bandit_initialize() {
  bl64_dbg_app_show_function
  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
  fi
  if [[ -z "$INST64_OPT_ROOT" ]]; then
    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
  fi
  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_BANDIT_METHOD' \
    "$INST64_BANDIT_METHOD" \
    'PIP' 'PIPX' ||
    return $?

  if [[ "$INST64_BANDIT_METHOD" == 'PIPX' || "$INST64_BANDIT_METHOD" == 'PIP' ]]; then
    if [[ "$INST64_BANDIT_METHOD" == 'PIPX' ]]; then
      bl64_check_command_search_path "$INST64_BANDIT_PIPX_BIN" ||
      return $?
    fi
    bl64_check_privilege_not_root ||
      return $?
  fi
  inst64_bandit_select_packages ||
    return $?
  bl64_msg_show_setup 'Install application: Bandit' \
    'INST64_SYSTEM_WIDE' 'INST64_BANDIT_METHOD' \
    'INST64_BANDIT_VERSION' \
    'INST64_BANDIT_CLI_PATH'
}

#
# Main
#

bl64_lib_script_version_set '1.1.0'
bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_bandit_initialize &&
  inst64_bandit_prepare &&
  inst64_bandit_install &&
  inst64_bandit_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
