#!/usr/bin/env bash
# Template: install-bl64-krew-1.0.0
#   Skeleton: install-bl64-custom-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-k8s.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64" ||
  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }

#
# Globals
#

# Installation method
declare INST64_STERN_METHOD="${INST64_STERN_METHOD:-AUTO}"
# Application version
declare INST64_STERN_VERSION="${INST64_STERN_VERSION:-latest}"

# App information
INST64_APP_NAME='stern'
INST64_APP_ID='STERN'
INST64_APP_FULL_NAME='Stern - Kubernetes log tailing'

INST64_CLI_NAME='kubectl-stern'

INST64_PKG_MAIN='stern'

#
# Functions
#

function my_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_step_prepare || return 0
}

function my_install() {
  bl64_dbg_app_show_function
  inst64_lib_step_install || return 0
  if [[ "$INST64_STERN_METHOD" == "$INST64_METHOD_KREW" ]]; then
    inst64_lib_k8s_install_krew
  fi
}

function my_setup() {
  bl64_dbg_app_show_function
  inst64_lib_step_setup || return 0
}

function my_verify() {
  bl64_dbg_app_show_function
  inst64_lib_step_verify || return 0
  "${INST64_CLI_TARGET}" --version
}

function my_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_method_check \
    "$INST64_METHOD_AUTO" \
    "$INST64_METHOD_KREW" ||
    return $?
  if [[ "$INST64_STERN_METHOD" == "$INST64_METHOD_AUTO" ]]; then
    INST64_STERN_METHOD="$INST64_METHOD_KREW"
  fi
}

function my_select_platform() {
  bl64_dbg_app_show_function
  return 0
}

function my_select_packages() {
  bl64_dbg_app_show_function
  return 0
}

function my_initialize() {
  bl64_dbg_app_show_function
  my_select_method &&
    inst64_lib_base_initialize ||
    return $?

  my_select_platform &&
    my_select_packages ||
    return $?

  inst64_lib_base_finalize
}

#
# Main
#

bl64_lib_script_version_set '2.0.0'
inst64_lib_base_set_verbosity 
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_initialize &&
  my_prepare &&
  my_install &&
  my_setup &&
  my_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
