#!/usr/bin/env bash
# Template: 2.3.0
# Snippet: install-git-repo-1.2.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Home root
declare INST64_HOME="${HOME}/at64"
# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
# shellcheck source-path=lib/bl64 disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Enable debugging? Set to YES to enable
declare INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Location for temporary files
declare INST64_TMP="${INST64_TMP:-/tmp}"
# Base path for 3rd party applications
declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
# Install system wide? Requires root privilege
declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"

declare INST64_LYNIS_GIT_SERVER="${INST64_LYNIS_GIT_SERVER:-https://github.com/CISOfy}"
declare INST64_LYNIS_GIT_REPO="${INST64_LYNIS_GIT_REPO:-lynis}"
declare INST64_LYNIS_TARGET="${INST64_LYNIS_TARGET:-}"
declare INST64_LYNIS_BRANCH="${INST64_LYNIS_BRANCH:-master}"
# Installation method
declare INST64_LYNIS_METHOD="${INST64_LYNIS_METHOD:-GIT}"

declare INST64_LYNIS_INSTALLER=''
declare INST64_LYNIS_PACKAGES=''
declare INST64_LYNIS_CLI_NAME='lynis'
declare INST64_LYNIS_CLI_PATH=''

#
# Functions
#

function inst64_lynis_install_git_repo() {
  bl64_dbg_app_show_function
  local app_target_mode='0755'
  local app_target_mode_dir='0755'
  local app_target_mode_file='0644'
  local app_target_owner='root'
  local app_cli_source="${INST64_LYNIS_CLI_NAME}"

  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    INST64_LYNIS_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_LYNIS_CLI_NAME}"
  else
    INST64_LYNIS_CLI_PATH="${INST64_LYNIS_TARGET}/${INST64_LYNIS_CLI_NAME}"
    app_target_owner="$BL64_VAR_DEFAULT"
  fi

  bl64_msg_show_task 'download application'
  bl64_rxtx_git_get_dir \
    "${INST64_LYNIS_GIT_SERVER}/${INST64_LYNIS_GIT_REPO}" \
    '.' \
    "$INST64_LYNIS_TARGET" \
    "$BL64_VAR_ON" \
    "$INST64_LYNIS_BRANCH" ||
    return $?

  bl64_msg_show_task 'deploy application'
  if [[ -n "$INST64_LYNIS_INSTALLER" ]]; then
    "$INST64_LYNIS_INSTALLER" ||
      return $?
  fi
  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    bl64_fs_path_permission_set "$app_target_mode_file" "$app_target_mode_dir" "$app_target_owner" "$BL64_VAR_DEFAULT" "$BL64_VAR_ON" \
      "$INST64_LYNIS_TARGET" &&
      bl64_fs_path_permission_set "$app_target_mode" "$app_target_mode" "$app_target_owner" "$BL64_VAR_DEFAULT" "$BL64_VAR_OFF" \
        "${INST64_LYNIS_TARGET}/${app_cli_source}" ||
      return $?
  fi

  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    bl64_msg_show_task "publish application to searchable path (${INST64_LYNIS_CLI_PATH})"
    # shellcheck disable=SC2086
    bl64_fs_symlink_create "${INST64_LYNIS_TARGET}/${app_cli_source}" "$INST64_LYNIS_CLI_PATH" "$BL64_VAR_ON" ||
      return $?
  fi

  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_lynis_install() {
  bl64_dbg_app_show_function
  if [[ "$INST64_LYNIS_METHOD" == 'GIT' ]]; then
    inst64_lynis_install_git_repo
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_lynis_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_LYNIS_METHOD" == 'GIT' ]]; then
    INST64_LYNIS_PACKAGES='NONE'
  fi
  [[ -z "$INST64_LYNIS_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_lynis_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
  if [[ "$INST64_LYNIS_METHOD" == 'GIT' ]]; then
    inst64_lynis_select_packages
  fi
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_lynis_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  cd "${INST64_LYNIS_TARGET}" &&
    "$INST64_LYNIS_CLI_PATH" show version
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_lynis_initialize() {
  bl64_dbg_app_show_function
  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
  fi
  if [[ -z "$INST64_OPT_ROOT" ]]; then
    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
  fi
  INST64_LYNIS_TARGET="${INST64_LYNIS_TARGET:-${INST64_OPT_ROOT}/lynis}"
  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_LYNIS_METHOD' \
    "$INST64_LYNIS_METHOD" \
    'GIT' ||
    return $?

  if [[ "$INST64_LYNIS_METHOD" == 'GIT' ]]; then
    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
      bl64_check_privilege_root ||
        return $?
    fi
  fi
  # shellcheck disable=SC2181
  (($? =! 0)) && return $BL64_LIB_ERROR_TASK_FAILED
  bl64_msg_show_setup 'Install application: Lynis' \
    'INST64_LYNIS_METHOD' 'INST64_SYSTEM_WIDE' 
}

#
# Main
#

bl64_lib_script_version_set '1.0.0'
bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_lynis_initialize &&
  inst64_lynis_prepare &&
  inst64_lynis_install &&
  inst64_lynis_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
