#!/usr/bin/env bash
# Template: install-bl64-binary-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck source-path=lib/bl64 disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
# shellcheck source-path=src disable=SC2015
source "${BL64_SCRIPT_PATH}/lib-bl64" ||
  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }

#
# Globals
#

# Installation method
declare INST64_ZOHOVAULT_METHOD="${INST64_ZOHOVAULT_METHOD:-BINARY}"
# Installation destination
declare INST64_ZOHOVAULT_TARGET="${INST64_ZOHOVAULT_TARGET:-}"
# Hardware architecture
declare INST64_ZOHOVAULT_PLATFORM="${INST64_ZOHOVAULT_PLATFORM:-}"
# Application version
declare INST64_ZOHOVAULT_VERSION="${INST64_ZOHOVAULT_VERSION:-latest}"

INST64_APP_NAME='zohovault'
INST64_APP_ID='ZOHOVAULT'
INST64_APP_FULL_NAME='ZohoVault - Zoho Vault CLI'
INST64_CLI_NAME='zv'

INST64_WEB_REPO_URL='https://downloads.zohocdn.com'
INST64_WEB_REPO_PATH='vault-cli-desktop'
INST64_PKG_MAIN_PREFIX='zv_cli'
INST64_PKG_MAIN_SUFFIX='.zip'
INST64_CPU_DARWIN_ARM64='macos'
INST64_CPU_LINUX_AMD64='linux'

#
# Functions
#

function inst64_install_binary() {
  bl64_dbg_app_show_function

  inst64_lib_task_download
  inst64_lib_staging_create &&
    inst64_lib_web_get_file &&
    inst64_lib_staging_open_zip ||
    return $?

  inst64_lib_task_deploy
  inst64_lib_target_create &&
    inst64_lib_target_populate ||
    return $?

  inst64_lib_task_cleanup
  inst64_lib_staging_remove
}

function inst64_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_step_prepare || return 0
  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
    inst64_lib_base_create_path
  fi
}

function inst64_install() {
  bl64_dbg_app_show_function
  inst64_lib_step_install || return 0
  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
    inst64_install_binary
  fi
}

function inst64_setup() {
  bl64_dbg_app_show_function
  inst64_lib_step_setup || return 0
  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
    inst64_lib_task_publish
    inst64_lib_cli_promote
  fi
}

function inst64_verify() {
  bl64_dbg_app_show_function
  inst64_lib_step_verify || return 0
  cd $HOME &&
    "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version || return $?
  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
    inst64_lib_app_register_version
  fi
}

function inst64_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_app_check_method \
    'AUTO' \
    'BINARY' ||
    return $?
  if [[ "$INST64_ZOHOVAULT_METHOD" == 'AUTO' ]]; then
    INST64_ZOHOVAULT_METHOD='BINARY'
  fi
}

function inst64_select_platform() {
  bl64_dbg_app_show_function
  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
    if [[ -z "$INST64_ZOHOVAULT_PLATFORM" ]]; then
      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
        INST64_ZOHOVAULT_PLATFORM="$INST64_CPU_DARWIN_ARM64"
      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
        INST64_ZOHOVAULT_PLATFORM="$INST64_CPU_LINUX_AMD64"
      fi
    fi
    inst64_lib_platform_check_cpu
  fi
}

function inst64_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
    INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_PKG_MAIN_SUFFIX}"
    INST64_WEB_REPO_PATH+="/${INST64_ZOHOVAULT_PLATFORM}"
  fi
  inst64_lib_package_check_definition
}

function inst64_initialize() {
  bl64_dbg_app_show_function
  inst64_lib_base_initialize &&
    inst64_select_method &&
    inst64_lib_method_initialize ||
    return $?

  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then

    bl64_os_check_not_version \
      "${BL64_OS_UB}-24" \
      "${BL64_OS_UB}-25" ||
      return $?
  fi

  inst64_select_platform &&
    inst64_select_packages &&
    inst64_lib_cli_set_path ||
    return $?

  inst64_lib_app_check_installed && return 0
  inst64_lib_message_show_parameters
}

#
# Main
#

bl64_lib_script_version_set '2.0.0'
bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_initialize &&
  inst64_prepare &&
  inst64_install &&
  inst64_setup &&
  inst64_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
