#!/usr/bin/env bash
# Template: 1.2.0
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 1.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Base Installer64 parameters
export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
export INST64_DEBUG="${INST64_DEBUG:-}"
export INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
export INST64_TMP="${INST64_TMP:-/tmp}"

# shellcheck source=SCRIPTDIR/../lib/bashlib64.bash
source "$INST64_BASHLIB64" || { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

export INST64_GO_PLATFORM="${INST64_GO_PLATFORM:-linux-amd64}"
export INST64_GO_SOURCE="${INST64_GO_SOURCE:-https://go.dev/dl}"
export INST64_GO_TARGET="${INST64_GO_TARGET:-${INST64_OPT_ROOT}/go}"
export INST64_GO_VERSION="${INST64_GO_VERSION:-21.2}"

#
# Functions
#

function inst64_go_install_binary_release() {
  bl64_dbg_app_show_function
  local package_prefix='go1'
  local package_sufix='tar.gz'
  local package_name="${package_prefix}.${INST64_GO_VERSION}.${INST64_GO_PLATFORM}.${package_sufix}"
  local work_path=''
  local app_cli='go'

  bl64_msg_show_task 'download application'
  work_path="$(bl64_fs_create_tmpdir)" || return $?
  bl64_rxtx_web_get_file "${INST64_GO_SOURCE}/${package_name}" "${work_path}/${package_name}" &&
    bl64_arc_open_tar "${work_path}/${package_name}" "${INST64_OPT_ROOT}" ||
    return $?

  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
  # shellcheck disable=SC2086
  bl64_fs_run_ln $BL64_FS_SET_LN_SYMBOLIC "${INST64_GO_TARGET}/bin/${app_cli}" "${INST64_LOCAL_BIN}/${app_cli}" ||
    return $?

  bl64_msg_show_task 'cleanup temporary files'
  bl64_fs_rm_tmpdir "$work_path"
  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_go_install() {
  bl64_dbg_app_show_function
  inst64_go_install_binary_release
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function inst64_go_initialize() {
  bl64_dbg_app_show_function
  bl64_os_check_version \
    "${BL64_OS_UB}-22" &&
    bl64_arc_setup &&
    bl64_check_privilege_root
}

#
# Main
#

declare inst64_go_installer_description='Install application: Go'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_go_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_go_initialize &&
  inst64_go_install
bl64_msg_show_batch_finish $? "$inst64_go_installer_description"
