#!/usr/bin/env bash
# Template: install-bl64-custom-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck source-path=lib/bl64 disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
# shellcheck source-path=src disable=SC2015
source "${BL64_SCRIPT_PATH}/lib-bl64" ||
  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }

#
# Globals
#

# Installation method
declare INST64_AWSCLI_METHOD="${INST64_AWSCLI_METHOD:-CUSTOM}"
# Installation destination
declare INST64_AWSCLI_TARGET="${INST64_AWSCLI_TARGET:-}"
# Hardware architecture
declare INST64_AWSCLI_PLATFORM="${INST64_AWSCLI_PLATFORM:-}"
# Application version
declare INST64_AWSCLI_VERSION="${INST64_AWSCLI_VERSION:-latest}"

# App information
INST64_APP_NAME='awscli'
INST64_APP_ID='AWSCLI'
INST64_APP_FULL_NAME='AWS CLI'
INST64_CLI_NAME='aws'

INST64_CPU_LINUX_AMD64='linux-x86_64'
INST64_WEB_REPO_URL='https://awscli.amazonaws.com'
INST64_APP_INSTALLER='aws/install'

#
# Functions
#

function inst64_install_custom_linux() {
  bl64_dbg_app_show_function
  inst64_lib_staging_open_zip ||
    return $?

  inst64_lib_task_deploy
  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    "${INST64_WORK_PATH_STAGING}/$INST64_APP_INSTALLER" \
      --bin-dir "${INST64_AWSCLI_TARGET}/bin" \
      --install-dir "${INST64_AWSCLI_TARGET}/versions" \
      --update
}

function inst64_install_custom_macos() {
  bl64_dbg_app_show_function
  inst64_lib_task_deploy
  installer \
    -pkg "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}" \
    -target /
}

function inst64_install_custom() {
  bl64_dbg_app_show_function
  inst64_lib_task_binary_download &&
    inst64_lib_web_get_file ||
    return $?
  if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" ]]; then
    inst64_install_custom_linux
  elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" ]]; then
    inst64_install_custom_macos
  fi
  inst64_lib_task_binary_cleanup
}

function inst64_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_step_prepare || return 0
}

function inst64_install() {
  bl64_dbg_app_show_function
  inst64_lib_step_install || return 0
  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
    inst64_install_custom
  fi
}

function inst64_setup() {
  bl64_dbg_app_show_function
  inst64_lib_step_setup || return 0
  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
    INST64_WORK_PATH_CLI="${INST64_AWSCLI_TARGET}/bin/${INST64_CLI_NAME}"
    inst64_lib_task_publish
    inst64_lib_cli_promote
  fi
}

function inst64_verify() {
  bl64_dbg_app_show_function
  inst64_lib_step_verify || return 0
  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version
}

function inst64_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_app_check_method \
    'AUTO' \
    'CUSTOM' ||
    return $?
  if [[ "$INST64_AWSCLI_METHOD" == 'AUTO' ]]; then
    INST64_AWSCLI_METHOD='CUSTOM'
  fi
}

function inst64_select_platform() {
  bl64_dbg_app_show_function
  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
    if [[ -z "$INST64_AWSCLI_PLATFORM" ]]; then
      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
        INST64_AWSCLI_PLATFORM="$INST64_CPU_DARWIN_ARM64"
      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
        INST64_AWSCLI_PLATFORM="$INST64_CPU_LINUX_AMD64"
      fi
      INST64_CLI_PATH='/usr/local/bin'
    fi
    inst64_lib_platform_check_cpu
  fi
}

function inst64_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
    if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" ]]; then
      INST64_PKG_MAIN_PREFIX='awscli-exe-'
      INST64_PKG_MAIN_SUFFIX='.zip'
      INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_AWSCLI_PLATFORM}${INST64_PKG_MAIN_SUFFIX}"
    elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" ]]; then
      INST64_PKG_MAIN_PREFIX='AWSCLIV2'
      INST64_PKG_MAIN_SUFFIX='.pkg'
      INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_PKG_MAIN_SUFFIX}"
    fi
  fi
  inst64_lib_package_check_definition
}

function inst64_initialize() {
  bl64_dbg_app_show_function
  inst64_lib_base_initialize &&
    inst64_select_method ||
    return $?

  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
    bl64_check_privilege_root &&
      bl64_os_check_flavor \
        "$BL64_OS_FLAVOR_DEBIAN" \
        "$BL64_OS_FLAVOR_FEDORA" \
        "$BL64_OS_FLAVOR_REDHAT" \
        "$BL64_OS_FLAVOR_MACOS" &&
      bl64_arc_setup ||
      return $?
  fi

  inst64_select_platform &&
    inst64_select_packages &&
    inst64_lib_cli_set_path ||
    return $?

  inst64_lib_app_check_installed && return 0
  inst64_lib_message_show_parameters
}

#
# Main
#

bl64_lib_script_version_set '2.0.0'
bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_initialize &&
  inst64_prepare &&
  inst64_install &&
  inst64_setup &&
  inst64_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
