#!/usr/bin/env bash
# Template: install-bl64-external-1.0.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64" ||
  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }

#
# Globals
#

# Installation method
declare INST64_PROTONVPN_METHOD="${INST64_PROTONVPN_METHOD:-EXTERNAL}"
# Application version
declare INST64_PROTONVPN_VERSION="${INST64_PROTONVPN_VERSION:-latest}"
# Enable development packages?
declare INST64_PROTONVPN_DEVELOPMENT="${INST64_PROTONVPN_DEVELOPMENT:-NO}"

# App information
INST64_APP_NAME='protonvpn'
INST64_APP_ID='PROTONVPN'
INST64_APP_FULL_NAME='ProtonVPN - Secure VPN Service'
INST64_CLI_NAME='protonvpn-cli'

#
# Functions
#

function inst64_prepare_repository() {
  bl64_dbg_app_show_function
  local current_package="$INST64_PKG_MAIN"

  if bl64_os_is_flavor "$BL64_OS_FLAVOR_DEBIAN"; then
    INST64_PKG_MAIN='protonvpn-stable-release_1.0.8_all.deb'
    INST64_WEB_REPO_URL='https://repo.protonvpn.com'
    INST64_WEB_REPO_PATH="debian/dists/stable/main/binary-all"
  fi

  inst64_lib_staging_create &&
    inst64_lib_web_get_file &&
    inst64_lib_pkg_install_file ||
    return $?

  INST64_PKG_MAIN="$current_package"
  inst64_lib_staging_remove
}

function inst64_install_external() {
  bl64_dbg_app_show_function
  inst64_lib_pkg_install
}

function inst64_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_step_prepare || return 0
  if [[ "$INST64_PROTONVPN_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    inst64_prepare_repository
  fi
}

function inst64_install() {
  bl64_dbg_app_show_function
  inst64_lib_step_install || return 0
  if [[ "$INST64_PROTONVPN_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    inst64_install_external
  fi
}

function inst64_setup() {
  bl64_dbg_app_show_function
  inst64_lib_step_setup || return 0
}

function inst64_verify() {
  bl64_dbg_app_show_function
  inst64_lib_step_verify || return 0
}

function inst64_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_app_check_method \
    "$INST64_METHOD_AUTO" \
    "$INST64_METHOD_EXTERNAL" ||
    return $?
  if [[ "$INST64_PROTONVPN_METHOD" == "$INST64_METHOD_AUTO" ]]; then
    INST64_PROTONVPN_METHOD="$INST64_METHOD_EXTERNAL"
  fi
}

function inst64_select_platform() {
  bl64_dbg_app_show_function
}

function inst64_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_PROTONVPN_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    # shellcheck disable=SC2249
    case "$BL64_OS_FLAVOR" in
      "$BL64_OS_FLAVOR_DEBIAN")
        bl64_lib_flag_is_enabled "$INST64_PROTONVPN_DEVELOPMENT" &&
          INST64_PKG_DEV=''
        INST64_PKG_MAIN='proton-vpn-gnome-desktop'
        ;;
    esac
    INST64_PKG_MAIN+=" ${INST64_PKG_DEV}"
  fi
  inst64_lib_package_check_definition
}

function inst64_initialize() {
  bl64_dbg_app_show_function
  inst64_select_method &&
    inst64_lib_base_initialize ||
    return $?

  if [[ "$INST64_PROTONVPN_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    bl64_os_check_flavor \
      "$BL64_OS_FLAVOR_DEBIAN" ||
      return $?
  fi

  inst64_select_platform &&
    inst64_select_packages &&
    inst64_lib_cli_set_path ||
    return $?

  inst64_lib_app_check_installed && return 0
  inst64_lib_message_show_parameters
}

#
# Main
#

bl64_lib_script_version_set '2.0.0'
bl64_msg_set_format "$INST64_VERBOSE" && bl64_msg_all_enable_verbose && bl64_dbg_set_level "$INST64_DEBUG" 
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
inst64_initialize &&
  inst64_prepare &&
  inst64_install &&
  inst64_setup &&
  inst64_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
