#!/usr/bin/env bash
# Template: 2.0.1
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 1.1.0
#
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Home root
declare INST64_HOME="${HOME}/at64"
# BashLib64 location
declare INST64_BASHLIB64=''
[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
# Enable debugging? Set to YES to enable
declare INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Location for temporary files
declare INST64_TMP="${INST64_TMP:-/tmp}"
# Base path for 3rd party applications
declare INST64_OPT_ROOT=''
# Install system wide? Requires root privilege
declare INST64_SYSTEM_WIDE=''

# shellcheck source=lib/bl64/bashlib64.bash
source "${INST64_BASHLIB64}/bashlib64.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

declare INST64_SHFMT_PLATFORM="${INST64_SHFMT_PLATFORM:-linux_amd64}"
declare INST64_SHFMT_TARGET=''
declare INST64_SHFMT_VERSION="${INST64_SHFMT_VERSION:-latest}"
# Installation method
declare INST64_SHFMT_METHOD="${INST64_SHFMT_METHOD:-BINARY}"

declare INST64_SHFMT_REPO_NAME='sh'
declare INST64_SHFMT_REPO_OWNER='mvdan'
declare INST64_SHFMT_PACKAGES=''
declare INST64_SHFMT_CLI_NAME='shfmt'

#
# Functions
#

function inst64_shfmt_install_binary_release() {
  bl64_dbg_app_show_function
  local work_path=''
  local app_target_mode='0755'
  local app_target_owner='root'
  local app_cli_mode='0755'
  local app_cli_source="${INST64_SHFMT_PACKAGES}"

  bl64_msg_show_task 'download application'
  work_path="$(bl64_fs_create_tmpdir)" || return $?
  bl64_rxtx_github_get_asset \
    "$INST64_SHFMT_REPO_OWNER" "$INST64_SHFMT_REPO_NAME" "$INST64_SHFMT_VERSION" "$INST64_SHFMT_PACKAGES" "${work_path}/${INST64_SHFMT_PACKAGES}" ||
    return $?

  bl64_msg_show_task 'deploy application'
  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_SHFMT_TARGET" &&
    bl64_fs_path_copy "$app_cli_mode" "$BL64_VAR_DEFAULT" "$app_target_owner" "$app_target_owner" "$INST64_SHFMT_TARGET" "${work_path}/${app_cli_source}" ||
    return $?

  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
  # shellcheck disable=SC2086
  bl64_fs_symlink_create "${INST64_SHFMT_TARGET}/${app_cli_source}" "${INST64_LOCAL_BIN}/${INST64_SHFMT_CLI_NAME}" "$BL64_VAR_ON" ||
    return $?

  bl64_msg_show_task 'cleanup temporary files'
  bl64_fs_rm_tmpdir "$work_path"
  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_shfmt_install() {
  bl64_dbg_app_show_function
  inst64_shfmt_select_packages || return $?
  if [[ "$INST64_SHFMT_METHOD" == 'BINARY' ]]; then
    inst64_shfmt_install_binary_release
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_shfmt_select_packages() {
  bl64_dbg_app_show_function
  local package_prefix=''
  local package_sufix=''
  if [[ "$INST64_SHFMT_METHOD" == 'BINARY' ]]; then
    if [[ "$INST64_SHFMT_VERSION" == 'latest' ]]; then
      INST64_SHFMT_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_SHFMT_REPO_OWNER" "$INST64_SHFMT_REPO_NAME")" ||
        return $?
    fi
    package_prefix='shfmt_'
    package_sufix=''
    INST64_SHFMT_PACKAGES="${package_prefix}${INST64_SHFMT_VERSION}_${INST64_SHFMT_PLATFORM}${package_sufix}"
  fi
  [[ -z "$INST64_SHFMT_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_shfmt_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_shfmt_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  if [[ "$INST64_SHFMT_METHOD" == 'BINARY' ]]; then
    "${INST64_LOCAL_BIN}/${INST64_SHFMT_CLI_NAME}" --version
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_shfmt_initialize() {
  bl64_dbg_app_show_function
  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
  fi
  if [[ -z "$INST64_OPT_ROOT" ]]; then
    [[ "$INST64_SYSTEM_WIDE" == 'NO' ]] && INST64_OPT_ROOT="$INST64_HOME" || INST64_OPT_ROOT='/opt'
  fi
  INST64_SHFMT_TARGET="${INST64_SHFMT_TARGET:-${INST64_OPT_ROOT}/shfmt}"
  bl64_os_check_compatibility \
    "${BL64_OS_UB}-22" \
    "${BL64_OS_ALP}-3" &&
    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_SHFMT_METHOD' \
      "$INST64_SHFMT_METHOD" \
      'BINARY' &&
    bl64_check_privilege_root
}

#
# Main
#

declare inst64_shfmt_installer_description='Install application: Go SHFMT'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_shfmt_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_shfmt_initialize &&
  inst64_shfmt_prepare &&
  inst64_shfmt_install &&
  inst64_shfmt_verify
bl64_msg_show_batch_finish $? "$inst64_shfmt_installer_description"
