#!/usr/bin/env bash
# Template: 2.0.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Home root
declare INST64_HOME="${HOME}/at64"
# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
# shellcheck source=lib/bl64/bashlib64.bash
source "${INST64_BASHLIB64}/bashlib64.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Enable debugging? Set to YES to enable
declare INST64_DEBUG="${INST64_DEBUG:-}"
# Installer64 location
declare INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
# Base path for local applications
declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# User applications binaries location
declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
# Location for temporary files
declare INST64_TMP="${INST64_TMP:-/tmp}"
# Base path for 3rd party applications
declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
# Install system wide? Requires root privilege
declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"

declare INST64_DOCKLE_PLATFORM="${INST64_DOCKLE_PLATFORM:-Linux-64bit}"
declare INST64_DOCKLE_TARGET="${INST64_DOCKLE_TARGET:-}"
declare INST64_DOCKLE_VERSION="${INST64_DOCKLE_VERSION:-latest}"
# Installation method
declare INST64_DOCKLE_METHOD="${INST64_DOCKLE_METHOD:-BINARY}"

declare INST64_GH_REPO_NAME='dockle'
declare INST64_GH_REPO_OWNER='goodwithtech'

declare INST64_PKG_MAIN=''
declare INST64_CLI_NAME='dockle'

#
# Functions
#

function inst64_dockle_install_binary() {
  bl64_dbg_app_show_function
  local work_path=''
  local app_target_mode='0755'
  local app_target_owner='root'
  local app_cli_mode='0755'
  local app_cli_source="${INST64_CLI_NAME}"

  bl64_msg_show_task 'download application'
  work_path="$(bl64_fs_create_tmpdir)" || return $?
  bl64_rxtx_github_get_asset \
    "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME" "$INST64_DOCKLE_VERSION" "$INST64_PKG_MAIN" "${work_path}/${INST64_PKG_MAIN}" &&
    bl64_arc_open_tar "${work_path}/${INST64_PKG_MAIN}" "${work_path}" ||
    return $?

  bl64_msg_show_task 'deploy application'
  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_DOCKLE_TARGET" &&
    bl64_fs_path_copy "$app_cli_mode" "$BL64_VAR_DEFAULT" "$app_target_owner" "$app_target_owner" "$INST64_DOCKLE_TARGET" "${work_path}/${app_cli_source}" ||
    return $?

  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
  # shellcheck disable=SC2086
  bl64_fs_symlink_create "${INST64_DOCKLE_TARGET}/${app_cli_source}" "${INST64_LOCAL_BIN}/${INST64_CLI_NAME}" "$BL64_VAR_ON" ||
    return $?

  bl64_msg_show_task 'cleanup temporary files'
  bl64_fs_rm_tmpdir "$work_path"
  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_dockle_install() {
  bl64_dbg_app_show_function
  inst64_dockle_select_packages || return $?
  if [[ "$INST64_DOCKLE_METHOD" == 'BINARY' ]]; then
    inst64_dockle_install_binary
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_dockle_select_packages() {
  bl64_dbg_app_show_function
  local package_prefix=''
  local package_suffix=''
  if [[ "$INST64_DOCKLE_METHOD" == 'BINARY' ]]; then
    if [[ "$INST64_DOCKLE_VERSION" == 'latest' ]]; then
      INST64_DOCKLE_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME")" ||
        return $?
    fi
    package_prefix='dockle'
    package_suffix='.tar.gz'
    INST64_PKG_MAIN="${package_prefix}_${INST64_DOCKLE_VERSION:1}_${INST64_DOCKLE_PLATFORM}${package_suffix}"
  fi
  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_dockle_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
  bl64_arc_setup
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_dockle_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  "${INST64_LOCAL_BIN}/${INST64_CLI_NAME}" --version
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function inst64_dockle_initialize() {
  bl64_dbg_app_show_function
  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
  fi
  if [[ -z "$INST64_OPT_ROOT" ]]; then
    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
  fi
  INST64_DOCKLE_TARGET="${INST64_DOCKLE_TARGET:-${INST64_OPT_ROOT}/dockle}"
  bl64_os_check_compatibility \
      "${BL64_OS_OL}-9" \
      "${BL64_OS_UB}-22" \
      "${BL64_OS_ALP}-3" &&
    bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_DOCKLE_METHOD' \
      "$INST64_DOCKLE_METHOD" \
      'BINARY' &&
    bl64_check_privilege_root
  # shellcheck disable=SC2181
  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
  bl64_msg_show_setup 'Install application: Dockle' \
    'INST64_DOCKLE_METHOD' 'INST64_SYSTEM_WIDE' 
}

#
# Main
#

bl64_lib_script_version_set '1.2.0'
bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_dockle_initialize &&
  inst64_dockle_prepare &&
  inst64_dockle_install &&
  inst64_dockle_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
