#!/usr/bin/env bash
# Template: install-bl64-native-1.0.0
# Template: install-bl64-external-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64"

#
# Globals
#

# Installation method
declare INST64_KEEPASSXC_METHOD="${INST64_KEEPASSXC_METHOD:-AUTO}"
# Application version
declare INST64_KEEPASSXC_VERSION="${INST64_KEEPASSXC_VERSION:-latest}"
# Enable development packages?
declare INST64_KEEPASSXC_DEVELOPMENT="${INST64_KEEPASSXC_DEVELOPMENT:-NO}"

# App information
INST64_APP_NAME='keepassxc'
INST64_APP_ID='KEEPASSXC'
INST64_APP_FULL_NAME='KeePassXC - Cross-platform Password Manager'
INST64_CLI_NAME='keepassxc'

#
# Functions
#

function my_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_prepare || return 0
}

function my_install() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_install || return 0
  if [[ "$INST64_KEEPASSXC_METHOD" == "$INST64_METHOD_NATIVE" ]]; then
    inst64_lib_pkg_install
  elif [[ "$INST64_KEEPASSXC_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    inst64_lib_pkg_install
  fi
}

function my_setup() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_setup || return 0
}

function my_verify() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_verify || return 0
  bl64_check_command "$INST64_CLI_TARGET"
}

function my_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_method_check \
    "$INST64_METHOD_AUTO" \
    "$INST64_METHOD_EXTERNAL" \
    "$INST64_METHOD_NATIVE" ||
    return $?
  if [[ "$INST64_KEEPASSXC_METHOD" == "$INST64_METHOD_AUTO" ]]; then
    if bl64_os_is_flavor \
      "$BL64_OS_FLAVOR_ARCH" \
      "$BL64_OS_FLAVOR_DEBIAN" \
      "$BL64_OS_FLAVOR_FEDORA"; then
      INST64_KEEPASSXC_METHOD="$INST64_METHOD_NATIVE"
    elif bl64_os_is_flavor \
      "$BL64_OS_FLAVOR_REDHAT"; then
      INST64_KEEPASSXC_METHOD="$INST64_METHOD_EXTERNAL"
    fi
  fi
}

function my_select_platform() {
  bl64_dbg_app_show_function
  inst64_lib_show_task_select_platform
}

function my_select_packages() {
  bl64_dbg_app_show_function
  inst64_lib_show_task_select_packages
  if [[ "$INST64_KEEPASSXC_METHOD" == "$INST64_METHOD_NATIVE" ]]; then
    # shellcheck disable=SC2249
    case "$BL64_OS_FLAVOR" in
      "$BL64_OS_FLAVOR_ARCH")
        bl64_lib_flag_is_enabled "$INST64_KEEPASSXC_DEVELOPMENT" &&
          INST64_PKG_DEV=''
        INST64_PKG_MAIN='extra/keepassxc'
        ;;
      "$BL64_OS_FLAVOR_DEBIAN" | "$BL64_OS_FLAVOR_FEDORA")
        bl64_lib_flag_is_enabled "$INST64_KEEPASSXC_DEVELOPMENT" &&
          INST64_PKG_DEV=''
        INST64_PKG_MAIN='keepassxc'
        ;;
    esac
    INST64_PKG_MAIN+=" ${INST64_PKG_DEV}"
  elif [[ "$INST64_KEEPASSXC_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    bl64_lib_flag_is_enabled "$INST64_KEEPASSXC_DEVELOPMENT" &&
      INST64_PKG_DEV=''
    INST64_PKG_MAIN='keepassxc'
  fi
  inst64_lib_base_check_package
}

function my_initialize() {
  bl64_dbg_app_show_function
  my_select_method &&
    inst64_lib_base_setup ||
    return $?

  if [[ "$INST64_KEEPASSXC_METHOD" == "$INST64_METHOD_NATIVE" ]]; then
    bl64_os_check_flavor \
      "$BL64_OS_FLAVOR_DEBIAN" \
      "$BL64_OS_FLAVOR_FEDORA" \
      "$BL64_OS_FLAVOR_ARCH" ||
      return $?
  elif [[ "$INST64_KEEPASSXC_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    bl64_os_check_version \
      "${BL64_OS_OL}-8" "${BL64_OS_OL}-9" "${BL64_OS_OL}-10" &&
      inst64_lib_base_check_prereq_file 'repo-epel' /etc/yum.repos.d/*epel*.repo ||
      return $?
  fi

  my_select_platform &&
    my_select_packages ||
    return $?

  inst64_lib_base_finalize
}

#
# Main
#

bl64_lib_script_version_set '1.1.0'
inst64_lib_base_initialize
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_initialize &&
  my_prepare &&
  my_install &&
  my_setup &&
  my_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
