#!/usr/bin/env bash
# Template: install-bash-custom-1.0.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

declare INST64_LIB_PATH="${INST64_LIB_PATH:-/opt/inst64}"
[[ ! -d "$INST64_LIB_PATH" && -d "${HOME}/at64/inst64" ]] && INST64_LIB_PATH="${HOME}/at64/inst64"
# shellcheck source-path=src disable=SC2015
source "${INST64_LIB_PATH}/lib-bash" ||
  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }

#
# Globals
#

# Installation method
declare INST64_XCODECLI_METHOD="${INST64_XCODECLI_METHOD:-CUSTOM}"
# Installation destination
declare INST64_XCODECLI_TARGET="${INST64_XCODECLI_TARGET:-/Library/Developer/CommandLineTools}"
# Hardware architecture
declare INST64_XCODECLI_PLATFORM="${INST64_XCODECLI_PLATFORM:-}"
# Application version
declare INST64_XCODECLI_VERSION="${INST64_XCODECLI_VERSION:-16.4}"

# App information
INST64_APP_NAME='xcodecli'
INST64_APP_ID='XCODECLI'
INST64_APP_FULL_NAME='Command Line Tools for Xcode'
# CLI information
INST64_CLI_NAME='xcode-select'
INST64_CLI_PATH='/usr/bin'
# shellcheck disable=SC2034
INST64_SCRIPT_VERSION='1.0.0'

INST64_PKG_MAIN='Command Line Tools for Xcode'

#
# Functions
#

function inst64_install_custom() {
  /usr/sbin/softwareupdate \
    --install \
    --all \
    "$INST64_PKG_MAIN"
}

function inst64_prepare() {
  inst64_lib_step_prepare || return 0
  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'CUSTOM' ]]; then
    :
  fi
}

function inst64_install() {
  inst64_lib_step_install || return 0
  if [[ "$INST64_XCODECLI_METHOD" == 'CUSTOM' ]]; then
    inst64_install_custom
  fi
}

function inst64_setup() {
  inst64_lib_step_setup || return 0
  if [[ "$INST64_XCODECLI_METHOD" == 'CUSTOM' ]]; then
    :
  fi
}

function inst64_verify() {
  inst64_lib_step_verify || return 0
  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --print-path
}

function inst64_select_platform() {
  return 0
}

function inst64_select_packages() {
  if [[ "$INST64_XCODECLI_METHOD" == 'CUSTOM' ]]; then
    INST64_PKG_MAIN="${INST64_PKG_MAIN}-${INST64_XCODECLI_VERSION}"
    [[ -z "$INST64_PKG_MAIN" ]] && echo 'Error: unable to determine package name' && return 1
  fi
  return 0
}

function inst64_initialize() {
  inst64_lib_base_initialize &&
    inst64_lib_app_check_method 'CUSTOM' ||
    return $?

  if [[ "$INST64_XCODECLI_METHOD" == 'CUSTOM' ]]; then
    inst64_lib_check_privilege_root &&
      inst64_lib_check_os_compatibility 'MACOS' ||
      return $?
  fi

  inst64_select_platform &&
    inst64_select_packages ||
    return $?

  inst64_lib_app_check_installed && return 0
  inst64_lib_message_show_parameters
}

#
# Main
#

inst64_lib_task_process_start &&
  inst64_initialize &&
  inst64_prepare &&
  inst64_install &&
  inst64_setup &&
  inst64_verify
inst64_lib_task_process_finish $?
