#!/usr/bin/env bash
# Template: 1.2.0
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 1.1.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Base Installer64 parameters
export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
export INST64_DEBUG="${INST64_DEBUG:-}"
export INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
export INST64_TMP="${INST64_TMP:-/tmp}"

# shellcheck source=SCRIPTDIR/../lib/bashlib64.bash
source "$INST64_BASHLIB64" || { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Installation method
export INST64_AZURECLI_METHOD="${INST64_AZURECLI_METHOD:-NATIVE}"

export INST64_AZURECLI_SOURCE_RHEL='https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm'
export INST64_AZURECLI_SOURCE_DEB='https://packages.microsoft.com/repos/azure-cli'
export INST64_AZURECLI_KEY_DEB='https://packages.microsoft.com/keys/microsoft.asc'

#
# Functions
#

function inst64_azurecli_install_yum() {
  bl64_dbg_app_show_function
  local packages='azure-cli'

  bl64_msg_show_task 'Add external package repository'
  bl64_pkg_deploy $INST64_AZURECLI_SOURCE_RHEL ||
    return $?

  bl64_msg_show_task 'deploy packages'
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages
}

function inst64_azurecli_install_deb() {
  bl64_dbg_app_show_function
  local repository_name='azure-cli'
  local repository_suite=''
  local repository_component='main'
  local repository_key='/etc/apt/keyrings/microsoft.gpg'
  local packages='azure-cli'

  bl64_msg_show_task 'Add external package repository'
  curl -sLS "$INST64_AZURECLI_KEY_DEB" |
    gpg --dearmor |
    tee "$repository_key" >/dev/null &&
    chmod go+r "$repository_key" &&
    repository_suite="$(lsb_release -cs)" &&
    echo "deb [signed-by=${repository_key}] https://packages.microsoft.com/repos/azure-cli/ ${repository_suite} ${repository_component}" |
    tee /etc/apt/sources.list.d/${repository_name}.list >/dev/null ||
    return $?

  bl64_msg_show_task 'deploy packages'
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages
}

function inst64_azurecli_install_external_packages() {
  bl64_dbg_app_show_function
  if bl64_os_match "${BL64_OS_OL}"; then
    inst64_azurecli_install_yum
  elif bl64_os_match "${BL64_OS_UB}"; then
    inst64_azurecli_install_deb
  fi
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_azurecli_install() {
  bl64_dbg_app_show_function
  if [[ "$INST64_AZURECLI_METHOD" == 'NATIVE' ]]; then
    inst64_azurecli_install_external_packages
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function inst64_azurecli_initialize() {
  bl64_dbg_app_show_function
  bl64_os_check_version \
    "${BL64_OS_UB}-22" \
    "${BL64_OS_OL}-9" &&
    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_AZURECLI_METHOD' \
      "$INST64_AZURECLI_METHOD" \
      'NATIVE' &&
    bl64_check_privilege_root &&
    bl64_pkg_setup
}

#
# Main
#

declare inst64_azurecli_installer_description='Install application: Azure CLI'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_azurecli_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_lib_enable
inst64_azurecli_initialize &&
  inst64_azurecli_install
bl64_msg_show_batch_finish $? "$inst64_azurecli_installer_description"
