#!/usr/bin/env bash
# Template: 1.2.0
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 1.2.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
# Enable debugging? Set to YES to enable
export INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Base path for 3rd party applications
export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"

# shellcheck source=SCRIPTDIR/../lib/bashlib64.bash
source "${INST64_BASHLIB64}/bashlib64.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

export INST64_AWSCLI_PLATFORM="${INST64_AWSCLI_PLATFORM:-linux-x86_64}"
export INST64_AWSCLI_SOURCE="${INST64_AWSCLI_SOURCE:-https://awscli.amazonaws.com}"
export INST64_AWSCLI_TARGET="${INST64_AWSCLI_TARGET:-${INST64_OPT_ROOT}/awscli}"
# Installation method
export INST64_AWSCLI_METHOD="${INST64_AWSCLI_METHOD:-CUSTOM}"

#
# Functions
#

function inst64_awscli_install_custom_package() {
  bl64_dbg_app_show_function
  local package_prefix='awscli-exe-'
  local package_sufix='.zip'
  local package_name="${package_prefix}${INST64_AWSCLI_PLATFORM}${package_sufix}"
  local package_url="$INST64_AWSCLI_SOURCE"
  local work_path=''
  local app_target_mode='0755'
  local app_target_owner='root'
  local app_cli='aws'
  local app_installer='aws/install'
  local app_bin="${INST64_AWSCLI_TARGET}/bin"
  local app_versions="${INST64_AWSCLI_TARGET}/versions"

  bl64_msg_show_task 'download application'
  work_path="$(bl64_fs_create_tmpdir)" || return $?
  bl64_rxtx_web_get_file "${package_url}/${package_name}" "${work_path}/${package_name}" &&
    bl64_arc_open_zip "${work_path}/${package_name}" "${work_path}" ||
    return $?

  bl64_msg_show_task 'deploy application'
  bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_AWSCLI_TARGET" &&
    bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    "${work_path}/$app_installer" \
      --bin-dir "$app_bin" \
      --install-dir "$app_versions" \
      --update ||
    return $?

  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
  # shellcheck disable=SC2086
  bl64_fs_create_symlink "${app_bin}/${app_cli}" "${INST64_LOCAL_BIN}/${app_cli}" "$BL64_VAR_ON" ||
    return $?

  bl64_msg_show_task 'cleanup temporary files'
  bl64_fs_rm_tmpdir "$work_path"
  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_awscli_install() {
  bl64_dbg_app_show_function
  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
    inst64_awscli_install_custom_package
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function inst64_awscli_initialize() {
  bl64_dbg_app_show_function

  bl64_arc_setup &&
    bl64_os_check_version \
      "${BL64_OS_UB}-22" \
      "${BL64_OS_OL}-9" &&
    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_AWSCLI_METHOD' \
      "$INST64_AWSCLI_METHOD" \
      'CUSTOM' &&
    bl64_check_privilege_root
}

#
# Main
#

declare inst64_awscli_installer_description='Install application: AWS CLI'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_awscli_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_awscli_initialize &&
  inst64_awscli_install

bl64_msg_show_batch_finish $? "$inst64_awscli_installer_description"
