#!/usr/bin/env bash
# Snippet: install-git-repo-1.0.1
# Template: 2.3.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Home root
declare INST64_HOME="${HOME}/at64"
# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
# shellcheck source-path=lib/bl64 disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Enable debugging? Set to YES to enable
declare INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# User applications binaries location
declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
# Location for temporary files
declare INST64_TMP="${INST64_TMP:-/tmp}"
# Base path for 3rd party applications
declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
# Install system wide? Requires root privilege
declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"

declare INST64_BASHIT_GIT_SERVER="${INST64_BASHIT_GIT_SERVER:-https://github.com/Bash-it}"
declare INST64_BASHIT_GIT_REPO="${INST64_BASHIT_GIT_REPO:-bash-it.git}"
declare INST64_BASHIT_TARGET="${INST64_BASHIT_TARGET:-}"
declare INST64_BASHIT_BRANCH="${INST64_BASHIT_BRANCH:-master}"
# Installation method
declare INST64_BASHIT_METHOD="${INST64_BASHIT_METHOD:-GIT}"

declare INST64_BASHIT_INSTALLER=''
declare INST64_APP_PACKAGES=''
declare INST64_CLI_NAME='bash_it.sh'
declare INST64_CLI_PATH=''

#
# Functions
#

function inst64_bashit_install_git_repo() {
  bl64_dbg_app_show_function
  local app_target_mode='0755'

  INST64_CLI_PATH="${INST64_BASHIT_TARGET}/${INST64_CLI_NAME}"
  bl64_msg_show_task 'download application'
  bl64_rxtx_git_get_dir \
    "${INST64_BASHIT_GIT_SERVER}/${INST64_BASHIT_GIT_REPO}" \
    '.' \
    "$INST64_BASHIT_TARGET" \
    "$BL64_VAR_ON" \
    "$INST64_BASHIT_BRANCH" ||
    return $?

  bl64_msg_show_task 'deploy application'
  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    bl64_fs_path_permission_set "$app_target_mode" "$app_target_mode" "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" "$BL64_VAR_ON" \
      "$INST64_BASHIT_TARGET" ||
      return $?
  fi

  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_bashit_install() {
  bl64_dbg_app_show_function
  if [[ "$INST64_BASHIT_METHOD" == 'GIT' ]]; then
    inst64_bashit_install_git_repo
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_bashit_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_BASHIT_METHOD" == 'GIT' ]]; then
    INST64_APP_PACKAGES="$INST64_BASHIT_GIT_REPO"
  fi
  [[ -z "$INST64_APP_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_bashit_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
  inst64_bashit_select_packages || return $?
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_bashit_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  "$INST64_CLI_PATH" --help
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_bashit_initialize() {
  bl64_dbg_app_show_function
  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
    INST64_SYSTEM_WIDE='NO'
  fi
  if [[ -z "$INST64_OPT_ROOT" ]]; then
    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
  fi
  INST64_BASHIT_TARGET="${INST64_BASHIT_TARGET:-${HOME}/.bash_it}"
  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_BASHIT_METHOD' \
    "$INST64_BASHIT_METHOD" \
    'GIT' ||
    return $?

  bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && bl64_msg_show_error 'system-wide installation not supported' &&
    return $BL64_LIB_ERROR_PARAMETER_INVALID

  if [[ "$INST64_BASHIT_METHOD" == 'GIT' ]]; then
    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
      bl64_check_privilege_root ||
        return $?
    fi
  fi
  # shellcheck disable=SC2181
  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
  bl64_msg_show_setup 'Install application: Bash-it' \
    'INST64_BASHIT_METHOD' 'INST64_SYSTEM_WIDE' 
}

#
# Main
#

bl64_lib_script_version_set '1.2.0'
bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_bashit_initialize &&
  inst64_bashit_prepare &&
  inst64_bashit_install &&
  inst64_bashit_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
