#!/usr/bin/env bash
# Template: 2.0.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Home root
declare INST64_HOME="${HOME}/at64"
# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
# shellcheck source=lib/bl64/bashlib64.bash
source "${INST64_BASHLIB64}/bashlib64.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Enable debugging? Set to YES to enable
declare INST64_DEBUG="${INST64_DEBUG:-}"
# Installer64 location
declare INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
# Base path for local applications
declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# User applications binaries location
declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
# Location for temporary files
declare INST64_TMP="${INST64_TMP:-/tmp}"
# Base path for 3rd party applications
declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
# Install system wide? Requires root privilege
declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"

# Installation method
declare INST64_KUBEPUG_METHOD="${INST64_KUBEPUG_METHOD:-KREW}"

declare INST64_KUBEPUG_KREW_BIN="${HOME}/.krew/bin/kubectl-krew"
declare INST64_KUBEPUG_K8S_KUBECONFIG="${INST64_KUBEPUG_K8S_KUBECONFIG:-$BL64_VAR_DEFAULT}"
declare INST64_APP_PACKAGES=''
declare INST64_CLI_NAME='deprecations'


#
# Functions
#

function inst64_kubepug_install_krew_package() {
  bl64_dbg_app_show_function

  bl64_msg_show_task 'deploy application to local kubectl'
  # shellcheck disable=SC2086
  bl64_k8s_run_kubectl_plugin \
    "$INST64_KUBEPUG_K8S_KUBECONFIG" \
    krew install \
    $INST64_APP_PACKAGES
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_kubepug_install() {
  bl64_dbg_app_show_function
  inst64_kubepug_select_packages || return $?
  if [[ "$INST64_KUBEPUG_METHOD" == 'KREW' ]]; then
    inst64_kubepug_install_krew_package
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_kubepug_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_KUBEPUG_METHOD" == 'KREW' ]]; then
    INST64_APP_PACKAGES='deprecations'
  fi
  [[ -z "$INST64_APP_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_kubepug_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
  bl64_k8s_setup
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_kubepug_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  bl64_k8s_run_kubectl_plugin "$INST64_KUBEPUG_K8S_KUBECONFIG" \
    "$INST64_CLI_NAME" version
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_kubepug_initialize() {
  bl64_dbg_app_show_function
  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
  fi
  if [[ -z "$INST64_OPT_ROOT" ]]; then
    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
  fi
  bl64_os_check_compatibility \
    "${BL64_OS_OL}-9" &&
    bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_KUBEPUG_METHOD' \
      "$INST64_KUBEPUG_METHOD" \
      'KREW' &&
    bl64_check_privilege_not_root &&
    bl64_check_command "$INST64_KUBEPUG_KREW_BIN"
  # shellcheck disable=SC2181
  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
  bl64_msg_show_setup 'Install application: KubePug' \
    'INST64_KUBEPUG_METHOD' 'INST64_SYSTEM_WIDE' 
}

#
# Main
#

bl64_lib_script_version_set '1.1.0'
bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_kubepug_initialize &&
  inst64_kubepug_prepare &&
  inst64_kubepug_install &&
  inst64_kubepug_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
