#!/usr/bin/env bash
# Template: 2.0.1
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 1.1.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
# Enable debugging? Set to YES to enable
export INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Base path for 3rd party applications
export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
# Location for temporary files
export INST64_TMP="${INST64_TMP:-/tmp}"

# shellcheck source=lib/bl64/bashlib64.bash
source "${INST64_BASHLIB64}/bashlib64.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Installation method
export INST64_GCC_METHOD="${INST64_GCC_METHOD:-NATIVE}"
# Enable development packages?
export INST64_GCC_DEVELOPMENT="${INST64_GCC_DEVELOPMENT:-$BL64_VAR_OFF}"

export INST64_GCC_PACKAGES=''
export INST64_GCC_CLI_NAME='gcc'

#
# Functions
#

function inst64_gcc_install_os_packages() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'deploy packages'
  # shellcheck disable=SC2086
  bl64_pkg_deploy $INST64_GCC_PACKAGES
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_gcc_install() {
  bl64_dbg_app_show_function
  inst64_gcc_select_packages || return $?
  if [[ "$INST64_GCC_METHOD" == 'NATIVE' ]]; then
    inst64_gcc_install_os_packages
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_gcc_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_GCC_METHOD" == 'NATIVE' ]]; then
    if bl64_os_match "$BL64_OS_UB"; then
      INST64_GCC_PACKAGES='build-essential'
    fi
  fi
  [[ -z "$INST64_GCC_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_gcc_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
  bl64_pkg_setup
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_gcc_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  if [[ "$INST64_GCC_METHOD" == 'NATIVE' ]]; then
    "/usr/bin/${INST64_GCC_CLI_NAME}" --version
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_gcc_initialize() {
  bl64_dbg_app_show_function
  bl64_os_check_compatibility \
    "${BL64_OS_UB}-22" &&
    bl64_check_privilege_root &&
    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_GCC_METHOD' \
      "$INST64_GCC_METHOD" \
      'NATIVE'
}

#
# Main
#

declare inst64_gcc_installer_description='Install application: GCC'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_gcc_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_gcc_initialize &&
  inst64_gcc_prepare &&
  inst64_gcc_install &&
  inst64_gcc_verify
bl64_msg_show_batch_finish $? "$inst64_gcc_installer_description"
