#!/usr/bin/env bash
# Template: install-bl64-external-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64"

#
# Globals
#

# Installation method
declare INST64_KUBEADM_METHOD="${INST64_KUBEADM_METHOD:-AUTO}"
# Application version
declare INST64_KUBEADM_VERSION="${INST64_KUBEADM_VERSION:-1.36}"
# Enable development packages?
declare INST64_KUBEADM_DEVELOPMENT="${INST64_KUBEADM_DEVELOPMENT:-NO}"

# App information
INST64_APP_NAME='kubeadm'
INST64_APP_ID='KUBEADM'
INST64_APP_FULL_NAME='KubeAdm - Kubernetes Bootstrap Toolbox'
INST64_CLI_NAME='kubeadm'
INST64_APP_DOC_INSTALL='https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm'

INST64_OS_REPO_NAME='kubernetes'
INST64_WEB_REPO_URL='https://dl.k8s.io'
INST64_OS_SOURCE_APT="https://pkgs.k8s.io/core:/stable:/"
INST64_OS_REPO_KEY_APT="https://pkgs.k8s.io/core:/stable:/"
INST64_OS_SOURCE_YUM="$INST64_OS_SOURCE_APT"
INST64_OS_REPO_KEY_YUM="$INST64_OS_REPO_KEY_APT"

#
# Functions
#

function my_select_packages_version() {
  bl64_dbg_app_show_function
  local package_version=''
  package_version="$(
    bl64_api_call \
      "$INST64_WEB_REPO_URL" \
      '/release/stable.txt' \
      "$BL64_API_METHOD_GET"
  )"
  if [[ -n "$package_version" ]]; then
    echo "${package_version#v}"
  else
    bl64_msg_show_error "Unable to detect package version (${INST64_WEB_REPO_URL})"
    return "$BL64_LIB_ERROR_TASK_FAILED"
  fi
}

function my_prepare_repository() {
  bl64_dbg_app_show_function
  local repository_url=''
  local repository_key=''
  local repository_apt_suite='/'
  local repository_apt_component=''

  if bl64_os_is_flavor "$BL64_OS_FLAVOR_DEBIAN"; then
    repository_url="${INST64_OS_SOURCE_APT}v${INST64_KUBEADM_VERSION}/deb"
    repository_key="${INST64_OS_REPO_KEY_APT}v${INST64_KUBEADM_VERSION}/deb/Release.key"
  elif bl64_os_is_flavor "$BL64_OS_FLAVOR_FEDORA" || bl64_os_is_flavor "$BL64_OS_FLAVOR_REDHAT"; then
    repository_url="${INST64_OS_SOURCE_YUM}v${INST64_KUBEADM_VERSION}/rpm"
    repository_key="${INST64_OS_REPO_KEY_YUM}v${INST64_KUBEADM_VERSION}/rpm/repodata/repomd.xml.key"
  fi

  inst64_lib_pkg_repo_add \
    "$repository_url" "$repository_key" \
    "$repository_apt_suite" "$repository_apt_component"
}

function my_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_prepare || return 0
  if [[ "$INST64_KUBEADM_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    my_prepare_repository
  fi
}

function my_install() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_install || return 0
  if [[ "$INST64_KUBEADM_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    inst64_lib_pkg_install
  fi
}

function my_setup() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_setup || return 0
}

function my_verify() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_verify || return 0
  "${INST64_CLI_TARGET}" version
}

function my_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_method_check \
    "$INST64_METHOD_AUTO" \
    "$INST64_METHOD_EXTERNAL" ||
    return $?
  if [[ "$INST64_KUBEADM_METHOD" == "$INST64_METHOD_AUTO" ]]; then
    INST64_KUBEADM_METHOD="$INST64_METHOD_EXTERNAL"
  fi
}

function my_select_platform() {
  bl64_dbg_app_show_function
  inst64_lib_show_task_select_platform
}

function my_select_packages() {
  bl64_dbg_app_show_function
  inst64_lib_show_task_select_packages
  if [[ "$INST64_KUBEADM_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    if [[ "$INST64_KUBEADM_VERSION" == 'latest' ]]; then
      INST64_KUBEADM_VERSION="$(my_select_packages_version)" ||
        return $?
    fi
    bl64_lib_flag_is_enabled "$INST64_KUBEADM_DEVELOPMENT" &&
      INST64_PKG_DEV=''
    INST64_PKG_MAIN=' kubelet'
    INST64_PKG_MAIN+=' kubeadm'
    INST64_PKG_MAIN+=' kubeadm'
    INST64_PKG_MAIN+=" ${INST64_PKG_DEV}"
  fi
  inst64_lib_base_check_package
}

function my_initialize() {
  bl64_dbg_app_show_function
  my_select_method &&
    inst64_lib_base_setup ||
    return $?

  if [[ "$INST64_KUBEADM_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    bl64_os_check_flavor \
      "$BL64_OS_FLAVOR_DEBIAN" \
      "$BL64_OS_FLAVOR_FEDORA" \
      "$BL64_OS_FLAVOR_REDHAT" ||
      return $?
  fi

  my_select_platform &&
    my_select_packages ||
    return $?

  inst64_lib_base_finalize
}

#
# Main
#

bl64_lib_script_version_set '1.1.1'
inst64_lib_base_initialize
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_initialize &&
  my_prepare &&
  my_install &&
  my_setup &&
  my_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
