#!/usr/bin/env bash
# Template: install-bl64-native-1.0.0
# Template: install-bl64-binary-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64" ||
  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }

#
# Globals
#

# Installation method
declare INST64_VSCODE_METHOD="${INST64_VSCODE_METHOD:-AUTO}"
# Installation destination
declare INST64_VSCODE_TARGET="${INST64_VSCODE_TARGET:-}"
# Hardware architecture
declare INST64_VSCODE_PLATFORM="${INST64_VSCODE_PLATFORM:-}"
# Application version
declare INST64_VSCODE_VERSION="${INST64_VSCODE_VERSION:-latest}"

# App information
INST64_APP_NAME='vscode'
INST64_APP_ID='VSCODE'
INST64_APP_FULL_NAME='Visual Studio Code'
INST64_CLI_NAME='code'
INST64_CLI_SUBPATH='bin'
INST64_WEB_REPO_URL='https://code.visualstudio.com'
INST64_WEB_REPO_PATH='sha'
INST64_PKG_MAIN_PREFIX='download?build=stable&os='
INST64_CPU_LINUX_AMD64='x64'
INST64_CPU_LINUX_ARM64='arm64'

#
# Functions
#

function inst64_install_native() {
  bl64_dbg_app_show_function
  inst64_lib_task_download
  inst64_lib_staging_create &&
    inst64_lib_web_get_file ||
    return $?

  inst64_lib_task_deploy
  inst64_lib_pkg_install_file ||
    return $?

  inst64_lib_task_cleanup
  inst64_lib_staging_remove
}

function inst64_install_binary() {
  bl64_dbg_app_show_function

  INST64_WORK_PATH_SOURCE="VSCode-${INST64_PKG_MAIN_SUFFIX}"
  inst64_lib_task_download
  inst64_lib_staging_create &&
    inst64_lib_web_get_file &&
    inst64_lib_staging_open_tar ||
    return $?

  inst64_lib_task_deploy
  inst64_lib_target_create &&
    inst64_lib_target_merge ||
    return $?

  inst64_lib_task_cleanup
  inst64_lib_staging_remove
}

function inst64_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_step_prepare || return 0
  if [[ "$INST64_VSCODE_METHOD" == 'BINARY' ]]; then
    inst64_lib_base_create_path
  fi
}

function inst64_install() {
  bl64_dbg_app_show_function
  inst64_lib_step_install || return 0
  if [[ "$INST64_VSCODE_METHOD" == 'NATIVE' ]]; then
    inst64_install_native
  elif [[ "$INST64_VSCODE_METHOD" == 'BINARY' ]]; then
    inst64_install_binary
  fi
}

function inst64_setup() {
  bl64_dbg_app_show_function
  inst64_lib_step_setup || return 0
  if [[ "$INST64_VSCODE_METHOD" == 'BINARY' ]]; then
    INST64_CLI_NORMALIZE='NO'
    bl64_dbg_app_show_comments 'required for portable mode on linux'
    bl64_fs_run_chown root "$INST64_VSCODE_TARGET"/chrome-sandbox &&
      bl64_fs_run_chmod 4755 "$INST64_VSCODE_TARGET"/chrome-sandbox &&
      inst64_lib_task_publish
    inst64_lib_cli_promote
  fi
}

function inst64_verify() {
  bl64_dbg_app_show_function
  inst64_lib_step_verify || return 0
  [[ -x "${INST64_CLI_PATH}/${INST64_CLI_NAME}" ]]
}

function inst64_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_app_check_method \
    'AUTO' \
    'BINARY' \
    'NATIVE' ||
    return $?
  if [[ "$INST64_VSCODE_METHOD" == 'AUTO' ]]; then
    INST64_VSCODE_METHOD='NATIVE'
  fi
}

function inst64_select_platform() {
  bl64_dbg_app_show_function
  if [[ "$INST64_VSCODE_METHOD" =~ 'NATIVE'|'BINARY' ]]; then
    if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
      INST64_VSCODE_PLATFORM="$INST64_CPU_LINUX_AMD64"
    elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
      INST64_VSCODE_PLATFORM="$INST64_CPU_LINUX_ARM6464"
    fi
    inst64_lib_platform_check_cpu
  fi
}

function inst64_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_VSCODE_METHOD" == 'NATIVE' ]]; then
    # shellcheck disable=SC2249
    case "$BL64_OS_FLAVOR" in
      "$BL64_OS_FLAVOR_FEDORA" | "$BL64_OS_FLAVOR_REDHAT")
        INST64_PKG_MAIN_SUFFIX="linux-rpm-${INST64_VSCODE_PLATFORM}"
        INST64_PKG_MAIN="${INST64_CLI_NAME}.rpm"
        ;;
      "$BL64_OS_FLAVOR_DEBIAN")
        INST64_PKG_MAIN_SUFFIX="linux-deb-${INST64_VSCODE_PLATFORM}"
        INST64_PKG_MAIN="${INST64_CLI_NAME}.deb"
        ;;
    esac
  elif [[ "$INST64_VSCODE_METHOD" == 'BINARY' ]]; then
    INST64_PKG_MAIN_SUFFIX="linux-${INST64_VSCODE_PLATFORM}"
    INST64_PKG_MAIN="${INST64_CLI_NAME}-stable"
  fi
  INST64_WEB_FILE_SOURCE="${INST64_PKG_MAIN_PREFIX}${INST64_PKG_MAIN_SUFFIX}"
  inst64_lib_package_check_definition
}

function inst64_initialize() {
  bl64_dbg_app_show_function
  inst64_select_method &&
    inst64_lib_base_initialize ||
    return $?

  if [[ "$INST64_VSCODE_METHOD" == 'NATIVE' ]]; then
    bl64_os_check_flavor \
      "$BL64_OS_FLAVOR_DEBIAN" \
      "$BL64_OS_FLAVOR_FEDORA" \
      "$BL64_OS_FLAVOR_REDHAT" ||
      return $?
  elif [[ "$INST64_VSCODE_METHOD" == 'BINARY' ]]; then
    bl64_os_check_flavor \
      "$BL64_OS_FLAVOR_ARCH" \
      "$BL64_OS_FLAVOR_DEBIAN" \
      "$BL64_OS_FLAVOR_FEDORA" \
      "$BL64_OS_FLAVOR_REDHAT" ||
      return $?
  fi

  inst64_select_platform &&
    inst64_select_packages &&
    inst64_lib_cli_set_path ||
    return $?

  inst64_lib_app_check_installed && return 0
  inst64_lib_message_show_parameters
}

#
# Main
#

bl64_lib_script_version_set '1.1.0'
bl64_msg_set_format "$INST64_VERBOSE" && bl64_msg_all_enable_verbose && bl64_dbg_set_level "$INST64_DEBUG"
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
inst64_initialize &&
  inst64_prepare &&
  inst64_install &&
  inst64_setup &&
  inst64_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
