#!/usr/bin/env bash
# Template: 1.2.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Home root
declare INST64_HOME="${HOME}/at64"
# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
# shellcheck source=lib/bl64/bashlib64.bash
source "${INST64_BASHLIB64}/bashlib64.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Enable debugging? Set to YES to enable
declare INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Base path for 3rd party applications
declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
# Install system wide? Requires root privilege
declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"

# Installation method
declare INST64_GCLOUD_METHOD="${INST64_GCLOUD_METHOD:-EXTERNAL}"
declare INST64_GCLOUD_PLATFORM_RHEL="${INST64_GCLOUD_PLATFORM:-x86_64}"

declare INST64_GCLOUD_REPOSITORY_NAME='google-cloud-sdk'
declare INST64_GCLOUD_SOURCE_RHEL='https://packages.cloud.google.com/yum/repos'
declare INST64_GCLOUD_REPOSITORY_KEY_RHEL='https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
declare INST64_GCLOUD_SOURCE_DEB='https://packages.cloud.google.com/apt'
declare INST64_GCLOUD_REPOSITORY_KEY_DEB='https://packages.cloud.google.com/apt/doc/apt-key.gpg'

#
# Functions
#

function inst64_gcloud_select_packages() {
  bl64_dbg_app_show_function
  local packages=''
  if bl64_os_is_distro "$BL64_OS_OL"; then
    packages='google-cloud-cli'
  elif bl64_os_is_distro "$BL64_OS_UB"; then
    packages='google-cloud-cli'
  fi
  [[ -n "$packages" ]] && echo "$packages"
}

function inst64_gcloud_add_repository() {
  local repository_url=''
  local repository_key=''
  local repository_extra_1=''
  local repository_extra_2=''

  bl64_msg_show_task 'Add external package repository'
  if bl64_os_is_distro "$BL64_OS_OL"; then
    repository_url="${INST64_GCLOUD_SOURCE_RHEL}/cloud-sdk-el8-${INST64_GCLOUD_PLATFORM_RHEL}"
    repository_key="$INST64_GCLOUD_REPOSITORY_KEY_RHEL"
    bl64_pkg_repository_add "$INST64_GCLOUD_REPOSITORY_NAME" \
      "$repository_url" "$repository_key" \
      "$repository_extra_1" "$repository_extra_2"
  elif bl64_os_is_distro "${BL64_OS_UB}-22"; then
    repository_url="${INST64_GCLOUD_SOURCE_DEB}"
    repository_key="$INST64_GCLOUD_REPOSITORY_KEY_DEB"
    repository_extra_1='cloud-sdk'
    repository_extra_2='main'
    bl64_pkg_deploy 'gnupg' 'lsb-release' &&
      bl64_rxtx_run_curl -sLS "$repository_key" |
      apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - &&
      echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] ${repository_url} ${repository_extra_1} ${repository_extra_2}" |
      "$BL64_OS_CMD_TEE" /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
  fi
}

function inst64_gcloud_install_external_packages() {
  bl64_dbg_app_show_function
  local packages=''

  inst64_gcloud_add_repository ||
    return $?

  bl64_msg_show_task 'deploy packages'
  packages="$(inst64_gcloud_select_packages)" ||
    return $?
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_gcloud_install() {
  bl64_dbg_app_show_function
  if [[ "$INST64_GCLOUD_METHOD" == 'EXTERNAL' ]]; then
    inst64_gcloud_install_external_packages
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function inst64_gcloud_initialize() {
  bl64_dbg_app_show_function
  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
  fi
  if [[ -z "$INST64_OPT_ROOT" ]]; then
    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
  fi

  bl64_os_check_version \
    "${BL64_OS_UB}-22" \
    "${BL64_OS_OL}-9" &&
    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_GCLOUD_METHOD' \
      "$INST64_GCLOUD_METHOD" \
      'EXTERNAL' &&
    bl64_check_privilege_root &&
    bl64_pkg_setup
}

#
# Main
#

declare inst64_gcloud_installer_description='Install application: GCloud CLI'

bl64_lib_script_version_set '1.2.0'
bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_gcloud_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_gcloud_initialize &&
  inst64_gcloud_install

bl64_msg_show_batch_finish $? "$inst64_gcloud_installer_description"
