#!/usr/bin/env bash
# Template: 2.3.1
# Snippet: install-custom-package-4.2.0
# Snippet: select-platform-1.0.0
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 1.6.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
# shellcheck source-path=lib/bl64 disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Enable debugging? Set to YES to enable
export INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Base path for 3rd party applications
export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
# Location for temporary files
export INST64_TMP="${INST64_TMP:-/tmp}"

export INST64_HELM_PLATFORM="${INST64_HELM_PLATFORM:-}"
export INST64_HELM_SOURCE="${INST64_HELM_SOURCE:-https://get.helm.sh}"
export INST64_HELM_TARGET="${INST64_HELM_TARGET:-${INST64_OPT_ROOT}/helm}"
export INST64_HELM_VERSION="${INST64_HELM_VERSION:-latest}"
# Install system wide? Requires root privilege
export INST64_HELM_SYSTEM_WIDE="${INST64_HELM_SYSTEM_WIDE:-YES}"
# Installation method
export INST64_HELM_METHOD="${INST64_HELM_METHOD:-CUSTOM}"

export INST64_HELM_PACKAGE_URL=''
export INST64_HELM_INSTALLER=''
export INST64_HELM_PACKAGES=''
export INST64_HELM_CLI_NAME='helm'
export INST64_HELM_CLI_PATH=''

export INST64_HELM_REPO_NAME='helm'
export INST64_HELM_REPO_OWNER='helm'

#
# Functions
#

function inst64_helm_install_custom_package() {
  bl64_dbg_app_show_function
  local work_path=''
  local app_target_mode='0755'
  local app_target_owner='root'
  local app_cli_source="${INST64_HELM_CLI_NAME}"

  if bl64_lib_flag_is_enabled "$INST64_HELM_SYSTEM_WIDE"; then
    INST64_HELM_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_HELM_CLI_NAME}"
  else
    INST64_HELM_CLI_PATH="${INST64_HELM_TARGET}/${INST64_HELM_CLI_NAME}"
    app_target_owner="$BL64_VAR_DEFAULT"
  fi

  bl64_msg_show_task 'download application'
  work_path="$(bl64_fs_create_tmpdir)" &&
    bl64_rxtx_web_get_file \
      "${INST64_HELM_PACKAGE_URL}/${INST64_HELM_PACKAGES}" \
      "${work_path}/${INST64_HELM_PACKAGES}" \
      'YES' \
      "$app_target_mode" &&
    bl64_arc_open_tar "${work_path}/${INST64_HELM_PACKAGES}" "${work_path}" ||
    return $?

  bl64_msg_show_task 'deploy application'
  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_HELM_TARGET" &&
    bl64_fs_path_copy "$app_target_mode" "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_HELM_TARGET" "${work_path}/${INST64_HELM_PLATFORM}/${app_cli_source}" ||
    return $?

  if bl64_lib_flag_is_enabled "$INST64_HELM_SYSTEM_WIDE"; then
    bl64_msg_show_task "publish application to searchable path (${INST64_HELM_CLI_PATH})"
    # shellcheck disable=SC2086
    bl64_fs_create_symlink "${INST64_HELM_TARGET}/${app_cli_source}" "$INST64_HELM_CLI_PATH" "$BL64_VAR_ON" ||
      return $?
  fi

  bl64_msg_show_task 'cleanup temporary files'
  bl64_fs_rm_tmpdir "$work_path"
  return 0
}

#######################################
# Selects platform ID
#
# * Platform ID format is defined by the package provider
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Platform ID
# Returns:
#   0: selection completed ok
#   >0: unable to selection
#######################################
function inst64_helm_select_platform() {
  bl64_dbg_app_show_function
  if [[ "$INST64_HELM_METHOD" == 'CUSTOM' ]]; then
    [[ -z "$INST64_HELM_PLATFORM" ]] && INST64_HELM_PLATFORM='linux-amd64'
  fi
  [[ -z "$INST64_HELM_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_helm_install() {
  bl64_dbg_app_show_function
  if [[ "$INST64_HELM_METHOD" == 'CUSTOM' ]]; then
    inst64_helm_install_custom_package
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_helm_select_packages() {
  bl64_dbg_app_show_function
  local package_prefix=''
  local package_sufix=''
  if [[ "$INST64_HELM_METHOD" == 'CUSTOM' ]]; then
    if [[ "$INST64_HELM_VERSION" == 'latest' ]]; then
      INST64_HELM_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_HELM_REPO_OWNER" "$INST64_HELM_REPO_NAME")" ||
        return $?
    fi
    package_prefix='helm-'
    package_sufix='.tar.gz'
    INST64_HELM_PACKAGES="${package_prefix}${INST64_HELM_VERSION}-${INST64_HELM_PLATFORM}${package_sufix}"
    INST64_HELM_PACKAGE_URL="$INST64_HELM_SOURCE"
    [[ -z "$INST64_HELM_PACKAGE_URL" ]] && bl64_msg_show_error 'unable to determine package download URL' && return 1
  fi
  [[ -z "$INST64_HELM_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_helm_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
  inst64_helm_select_platform &&
    inst64_helm_select_packages ||
    return $?
  if [[ "$INST64_HELM_METHOD" == 'CUSTOM' ]]; then
    bl64_arc_setup
  fi
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_helm_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  "$INST64_HELM_CLI_PATH" version
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_helm_initialize() {
  bl64_dbg_app_show_function
  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_HELM_METHOD' \
    "$INST64_HELM_METHOD" \
    'CUSTOM' ||
    return $?

  if [[ "$INST64_HELM_METHOD" == 'CUSTOM' ]]; then
    if bl64_lib_flag_is_enabled "$INST64_HELM_SYSTEM_WIDE"; then
      bl64_check_privilege_root ||
        return $?
    fi
  fi
}

#
# Main
#

declare inst64_helm_installer_description='Install application: Helm'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_helm_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_helm_initialize &&
  inst64_helm_prepare &&
  inst64_helm_install &&
  inst64_helm_verify
bl64_msg_show_batch_finish $? "$inst64_helm_installer_description"
