#!/usr/bin/env bash
# Template: 2.2.0
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 1.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
# shellcheck source-path=lib/bl64 disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Enable debugging? Set to YES to enable
export INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Base path for 3rd party applications
export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
# Location for temporary files
export INST64_TMP="${INST64_TMP:-/tmp}"

export INST64_GOMPLATE_PLATFORM="${INST64_GOMPLATE_PLATFORM:-linux-amd64}"
export INST64_GOMPLATE_TARGET="${INST64_GOMPLATE_TARGET:-${INST64_OPT_ROOT}/gomplate}"
export INST64_GOMPLATE_VERSION="${INST64_GOMPLATE_VERSION:-latest}"
# Install system wide? Requires root privilege
export INST64_GOMPLATE_SYSTEM_WIDE="${INST64_GOMPLATE_SYSTEM_WIDE:-YES}"
# Installation method
export INST64_GOMPLATE_METHOD="${INST64_GOMPLATE_METHOD:-BINARY}"

export INST64_GOMPLATE_REPO_NAME='gomplate'
export INST64_GOMPLATE_REPO_OWNER='hairyhenderson'
export INST64_GOMPLATE_PACKAGES=''
export INST64_GOMPLATE_CLI_NAME='gomplate'
export INST64_GOMPLATE_CLI_PATH=''

#
# Functions
#

function inst64_gomplate_install_binary_release() {
  bl64_dbg_app_show_function
  local work_path=''
  local app_target_mode='0755'
  local app_target_owner='root'
  local app_cli_mode='0755'
  local app_cli_source="${INST64_GOMPLATE_PACKAGES}"

  if bl64_lib_flag_is_enabled "$INST64_GOMPLATE_SYSTEM_WIDE"; then
    INST64_GOMPLATE_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_GOMPLATE_CLI_NAME}"
  else
    INST64_GOMPLATE_CLI_PATH="${INST64_GOMPLATE_TARGET}/${INST64_GOMPLATE_CLI_NAME}"
    app_target_owner="$BL64_VAR_DEFAULT"
  fi

  bl64_msg_show_task 'download application'
  work_path="$(bl64_fs_create_tmpdir)" || return $?
  bl64_rxtx_github_get_asset \
    "$INST64_GOMPLATE_REPO_OWNER" "$INST64_GOMPLATE_REPO_NAME" "$INST64_GOMPLATE_VERSION" "$INST64_GOMPLATE_PACKAGES" "${work_path}/${INST64_GOMPLATE_PACKAGES}" ||
    return $?

  bl64_msg_show_task 'deploy application'
  bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_GOMPLATE_TARGET" &&
    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_GOMPLATE_TARGET" "${work_path}/${app_cli_source}" ||
    return $?

  if bl64_lib_flag_is_enabled "$INST64_GOMPLATE_SYSTEM_WIDE"; then
    bl64_msg_show_task "publish application to searchable path (${INST64_GOMPLATE_CLI_PATH})"
    # shellcheck disable=SC2086
    bl64_fs_create_symlink "${INST64_GOMPLATE_TARGET}/${app_cli_source}" "$INST64_GOMPLATE_CLI_PATH" "$BL64_VAR_ON" ||
      return $?
  fi

  bl64_msg_show_task 'cleanup temporary files'
  bl64_fs_rm_tmpdir "$work_path"
  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_gomplate_install() {
  bl64_dbg_app_show_function
  inst64_gomplate_select_packages || return $?
  if [[ "$INST64_GOMPLATE_METHOD" == 'BINARY' ]]; then
    inst64_gomplate_install_binary_release
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_gomplate_select_packages() {
  bl64_dbg_app_show_function
  local package_prefix=''
  local package_sufix=''
  if [[ "$INST64_GOMPLATE_METHOD" == 'BINARY' ]]; then
    if [[ "$INST64_GOMPLATE_VERSION" == 'latest' ]]; then
      INST64_GOMPLATE_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_GOMPLATE_REPO_OWNER" "$INST64_GOMPLATE_REPO_NAME")" ||
        return $?
    fi
    package_prefix='gomplate_'
    package_sufix=''
    INST64_GOMPLATE_PACKAGES="${package_prefix}${INST64_GOMPLATE_PLATFORM}${package_sufix}"
  fi
  [[ -z "$INST64_GOMPLATE_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_gomplate_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_gomplate_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  "$INST64_GOMPLATE_CLI_PATH" --version
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_gomplate_initialize() {
  bl64_dbg_app_show_function
  if bl64_lib_flag_is_enabled "$INST64_GOMPLATE_SYSTEM_WIDE"; then
    bl64_check_privilege_root ||
      return $?
  fi
  bl64_os_check_compatibility \
    "${BL64_OS_ALP}" \
    "${BL64_OS_UB}" \
    "${BL64_OS_OL}" \
    "${BL64_OS_FD}" &&
    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_GOMPLATE_METHOD' \
      "$INST64_GOMPLATE_METHOD" \
      'BINARY'
}

#
# Main
#

declare inst64_gomplate_installer_description='Install application: Gomplate'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_gomplate_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_gomplate_initialize &&
  inst64_gomplate_prepare &&
  inst64_gomplate_install &&
  inst64_gomplate_verify
bl64_msg_show_batch_finish $? "$inst64_gomplate_installer_description"
