#!/usr/bin/env bash
# Template: install-bl64-binary-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64" ||
  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }

#
# Globals
#

# Installation method
declare INST64_JAVA_METHOD="${INST64_JAVA_METHOD:-BINARY}"
# Installation destination
declare INST64_JAVA_TARGET="${INST64_JAVA_TARGET:-}"
# Hardware architecture
declare INST64_JAVA_PLATFORM="${INST64_JAVA_PLATFORM:-}"
# Application version
declare INST64_JAVA_VERSION="${INST64_JAVA_VERSION:-24}"

INST64_APP_NAME='java'
INST64_APP_ID='JAVA'
INST64_APP_FULL_NAME='Java - Java runtime environment'
INST64_CLI_NAME='java'
INST64_CLI_SOURCE="$INST64_CLI_NAME"

INST64_WEB_REPO_URL='https://download.oracle.com'
INST64_WEB_REPO_PATH='java'
INST64_PKG_MAIN_PREFIX='jdk-'
INST64_PKG_MAIN_SUFFIX='_bin.tar.gz'
INST64_CPU_DARWIN_ARM64='macos-aarch64'
INST64_CPU_LINUX_AMD64='linux-x64'

#
# Functions
#

function inst64_install_binary() {
  bl64_dbg_app_show_function

  inst64_lib_task_download
  inst64_lib_staging_create &&
    inst64_lib_web_get_file &&
    bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    inst64_lib_staging_open_tar ||
    return $?

  inst64_lib_task_deploy
  INST64_WORK_PATH_SOURCE="$(
    cd "$INST64_WORK_PATH_STAGING" &&
      bl64_bsh_pattern_match_file "${INST64_PKG_MAIN_PREFIX}${INST64_JAVA_VERSION}".*
  )"
  if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" ]]; then
    bl64_dbg_app_show_comments 'Ajust target path for macOS java_home compatibility'
    INST64_JAVA_TARGET="$(bl64_fmt_path_get_dirname "$INST64_JAVA_TARGET")/${INST64_WORK_PATH_SOURCE}"
    INST64_CLI_PATH="${INST64_JAVA_TARGET}/${INST64_CLI_SUBPATH}"
  fi
  inst64_lib_target_create &&
    inst64_lib_target_merge ||
    return $?

  inst64_lib_task_cleanup
  inst64_lib_staging_remove
}

function inst64_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_step_prepare || return 0
  if [[ "$INST64_JAVA_METHOD" == 'BINARY' ]]; then
    inst64_lib_base_create_path
  fi
}

function inst64_install() {
  bl64_dbg_app_show_function
  inst64_lib_step_install || return 0
  if [[ "$INST64_JAVA_METHOD" == 'BINARY' ]]; then
    inst64_install_binary
  fi
}

function inst64_setup() {
  bl64_dbg_app_show_function
  inst64_lib_step_setup || return 0
  if [[ "$INST64_JAVA_METHOD" == 'BINARY' ]]; then
    if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" ]]; then
      inst64_lib_task_publish
      inst64_lib_cli_promote
    else
      bl64_dbg_app_show_comments 'do not promote on MacOS to avoid conflicts with native java_home'
    fi
  fi
}

function inst64_verify() {
  bl64_dbg_app_show_function
  inst64_lib_step_verify || return 0
  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version || return $?
  if [[ "$INST64_JAVA_METHOD" == 'BINARY' ]]; then
    if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" ]]; then
      inst64_lib_app_register_version
    fi
  fi
}

function inst64_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_app_check_method \
    'AUTO' \
    'BINARY' ||
    return $?
  if [[ "$INST64_JAVA_METHOD" == 'AUTO' ]]; then
    INST64_JAVA_METHOD='BINARY'
  fi
}

function inst64_select_platform() {
  bl64_dbg_app_show_function
  if [[ "$INST64_JAVA_METHOD" == 'BINARY' ]]; then
    if [[ -z "$INST64_JAVA_PLATFORM" ]]; then
      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
        INST64_JAVA_PLATFORM="$INST64_CPU_DARWIN_ARM64"
      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
        INST64_JAVA_PLATFORM="$INST64_CPU_LINUX_AMD64"
      fi
    fi
    inst64_lib_platform_check_cpu
  fi
}

function inst64_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_JAVA_METHOD" == 'BINARY' ]]; then
    INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_JAVA_VERSION}_${INST64_JAVA_PLATFORM}${INST64_PKG_MAIN_SUFFIX}"
    INST64_WEB_REPO_PATH+="/${INST64_JAVA_VERSION}/latest"
  fi
  inst64_lib_package_check_definition
}

function inst64_initialize() {
  bl64_dbg_app_show_function

  inst64_select_method ||
    return $?

  if [[ "$INST64_JAVA_METHOD" == 'BINARY' ]]; then
    if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" ]]; then
      bl64_dbg_app_show_comments 'Prefer java_home compatible paths for the tool to properly detect the jvm'
      INST64_ROOT_PATH_DEFAULT_SYSTEM='/Library/Java/JavaVirtualMachines'
      INST64_ROOT_PATH_DEFAULT_USER="${HOME}/Library/Java/JavaVirtualMachines"
      INST64_CLI_SUBPATH='Contents/Home/bin'
    elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" ]]; then
      INST64_TARGET_PATH_DEFAULT="java-v${INST64_JAVA_VERSION}"
      INST64_CLI_NAME+="${INST64_JAVA_VERSION}"
      INST64_CLI_SUBPATH='bin'
    fi
  fi

  inst64_lib_base_initialize ||
    return $?

  if [[ "$INST64_JAVA_METHOD" == 'BINARY' ]]; then
    bl64_os_check_not_version "${BL64_OS_ALP}" ||
      return $?
  fi

  inst64_select_platform &&
    inst64_select_packages &&
    inst64_lib_cli_set_path ||
    return $?

  if [[ "$INST64_JAVA_METHOD" == 'BINARY' ]]; then
    if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" ]]; then
      bl64_dbg_app_show_comments 'CLI path is unknown at this point, leave it empty'
      INST64_CLI_PATH="$INST64_JAVA_TARGET"
    fi
  fi

  inst64_lib_app_check_installed && return 0
  inst64_lib_message_show_parameters
}

#
# Main
#

bl64_lib_script_version_set '1.0.1'
bl64_msg_set_format "$INST64_VERBOSE" && bl64_msg_all_enable_verbose && bl64_dbg_set_level "$INST64_DEBUG" 
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
inst64_initialize &&
  inst64_prepare &&
  inst64_install &&
  inst64_setup &&
  inst64_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
