#!/usr/bin/env bash
# Template: install-bl64-python-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-py.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64" ||
  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }

#
# Globals
#

# Installation method
declare INST64_KST_METHOD="${INST64_KST_METHOD:-PIPX}"
# Application version
declare INST64_KST_VERSION="${INST64_KST_VERSION:-latest}"

# App information
INST64_APP_NAME='ksh'
INST64_APP_ID='KST'
INST64_APP_FULL_NAME='Kandji Sync Toolkit'
# CLI information
INST64_CLI_NAME='kst'

INST64_PKG_MAIN='kst'

#
# Functions
#

function inst64_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_step_prepare || return 0
}

function inst64_install() {
  bl64_dbg_app_show_function
  inst64_lib_step_install || return 0
  if [[ "$INST64_KST_METHOD" == 'PIPX' ]]; then
    inst64_lib_python_install_pipx
  elif [[ "$INST64_KST_METHOD" == 'PIP' ]]; then
    inst64_lib_python_install_pip
  fi
}

function inst64_setup() {
  bl64_dbg_app_show_function
  inst64_lib_step_setup || return 0
}

function inst64_verify() {
  bl64_dbg_app_show_function
  inst64_lib_step_verify || return 0
  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version
}

function inst64_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_app_check_method \
    'AUTO' \
    'PIP' 'PIPX' ||
    return $?
  if [[ "$INST64_KST_METHOD" == 'AUTO' ]]; then
    INST64_KST_METHOD='PIPX'
  fi
}

function inst64_select_platform() {
  bl64_dbg_app_show_function
  return 0
}

function inst64_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_KST_METHOD" == 'PIPX' || "$INST64_KST_METHOD" == 'PIP' ]]; then
    if [[ "$INST64_KST_VERSION" == 'latest' ]]; then
      version_target=''
    else
      version_target="==${INST64_KST_VERSION}.*"
    fi
    INST64_PKG_MAIN="${INST64_PKG_MAIN}${version_target}"
  fi
  inst64_lib_package_check_definition
}

function inst64_initialize() {
  bl64_dbg_app_show_function
  inst64_select_method &&
    inst64_lib_base_initialize ||
    return $?

  inst64_select_platform &&
    inst64_select_packages &&
    inst64_lib_cli_set_path ||
    return $?

  inst64_lib_app_check_installed && return 0
  inst64_lib_message_show_parameters
}

#
# Main
#

bl64_lib_script_version_set '1.0.1'
bl64_msg_set_format "$INST64_VERBOSE" && bl64_msg_all_enable_verbose && bl64_dbg_set_level "$INST64_DEBUG" 
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
inst64_initialize &&
  inst64_prepare &&
  inst64_install &&
  inst64_setup &&
  inst64_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
