#!/usr/bin/env bash
# Template: install-bl64-external-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64"

#
# Globals
#

# Installation method
declare INST64_REPOHPSPP9_METHOD="${INST64_REPOHPSPP9_METHOD:-AUTO}"
# Application version
declare INST64_REPOHPSPP9_VERSION="${INST64_REPOHPSPP9_VERSION:-current}"
# Hardware architecture
declare INST64_REPOHPSPP9_PLATFORM="${INST64_REPOHPSPP9_PLATFORM:-}"

# App information
INST64_APP_NAME='repohpspp9'
INST64_APP_ID='REPOHPSPP9'
INST64_APP_FULL_NAME='HP SPP - External Linux RPM repository for HP Service Pack ProLiant Gen9'
INST64_APP_DOC_INSTALL='https://downloads.linux.hpe.com/sdr/project/spp/'

INST64_OS_REPO_NAME='hp-spp-9'
INST64_OS_SOURCE_YUM='https://downloads.linux.hpe.com/repo'
INST64_OS_REPO_KEY_YUM='https://downloads.linux.hpe.com/repo/spp/GPG-KEY-spp,https://downloads.linux.hpe.com/repo/spp/GPG-KEY2-spp'
INST64_CPU_LINUX_AMD64='x86_64'

#
# Functions
#

function my_prepare_repository() {
  bl64_dbg_app_show_function
  local repository_url=''
  local repository_key=''

  if bl64_os_is_flavor "$BL64_OS_FLAVOR_FEDORA" || bl64_os_is_flavor "$BL64_OS_FLAVOR_REDHAT"; then
    repository_url="${INST64_OS_SOURCE_YUM}/spp-gen9/redhat/${BL64_OS_DISTRO##*-}/${INST64_REPOHPSPP9_PLATFORM}/${INST64_REPOHPSPP9_VERSION}"
    repository_key="$INST64_OS_REPO_KEY_YUM"
  fi

  inst64_lib_pkg_repo_add \
    "$repository_url" "$repository_key"
}

function my_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_prepare || return 0
  if [[ "$INST64_REPOHPSPP9_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    my_prepare_repository
  fi
}

function my_install() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_install || return 0
}

function my_setup() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_setup || return 0
}

function my_verify() {
  bl64_dbg_app_show_function
}

function my_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_method_check \
    "$INST64_METHOD_AUTO" \
    "$INST64_METHOD_EXTERNAL" ||
    return $?
  if [[ "$INST64_REPOHPSPP9_METHOD" == "$INST64_METHOD_AUTO" ]]; then
    INST64_REPOHPSPP9_METHOD="$INST64_METHOD_EXTERNAL"
  fi
}

function my_select_platform() {
  bl64_dbg_app_show_function
  inst64_lib_show_task_select_platform
  if [[ "$INST64_REPOHPSPP9_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
      INST64_REPOHPSPP9_PLATFORM="$INST64_CPU_LINUX_AMD64"
    fi
    inst64_lib_base_check_platform
  fi
}

function my_select_packages() {
  bl64_dbg_app_show_function
  inst64_lib_show_task_select_packages
}

function my_initialize() {
  bl64_dbg_app_show_function
  my_select_method &&
    inst64_lib_base_setup ||
    return $?

  if [[ "$INST64_REPOHPSPP9_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    bl64_os_check_flavor \
      "$BL64_OS_FLAVOR_REDHAT" ||
      return $?
  fi

  my_select_platform &&
    my_select_packages ||
    return $?

  inst64_lib_base_finalize
}

#
# Main
#

bl64_lib_script_version_set '1.0.0'
inst64_lib_base_initialize
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_initialize &&
  my_prepare &&
  my_install &&
  my_setup &&
  my_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
