#!/usr/bin/env bash
# Template: 2.0.0
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 2.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
# Enable debugging? Set to YES to enable
export INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Base path for 3rd party applications
export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
# Location for temporary files
export INST64_TMP="${INST64_TMP:-/tmp}"

# shellcheck source=SCRIPTDIR/../lib/bl64/bashlib64.bash
source "${INST64_BASHLIB64}/bashlib64.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Installation method
export INST64_MKDOCS_METHOD="${INST64_MKDOCS_METHOD:-PIP}"
export INST64_MKDOCS_VERSION="${INST64_MKDOCS_VERSION:-latest}"
export INST64_MKDOCS_PIPX_BIN='/usr/bin/pipx'
export INST64_MKDOCS_PACKAGES=''
export INST64_MKDOCS_CLI_NAME='mkdocs'

#
# Functions
#

function inst64_mkdocs_install_with_pip() {
  bl64_dbg_app_show_function
  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    bl64_py_pip_usr_prepare &&
    bl64_py_pip_usr_deploy "$INST64_MKDOCS_PACKAGES"
}

function inst64_mkdocs_install_with_pipx() {
  bl64_dbg_app_show_function
  pipx install "$INST64_MKDOCS_PACKAGES"
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_mkdocs_install() {
  bl64_dbg_app_show_function
  inst64_mkdocs_select_packages || return $?
  bl64_msg_show_task 'deploy application'
  if [[ "$INST64_MKDOCS_METHOD" == 'PIPX' ]]; then
    inst64_mkdocs_install_with_pipx
  elif [[ "$INST64_MKDOCS_METHOD" == 'PIP' ]]; then
    inst64_mkdocs_install_with_pip
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_mkdocs_select_packages() {
  bl64_dbg_app_show_function
  local version_target=''

  if [[ "$INST64_MKDOCS_METHOD" == 'PIPX' || "$INST64_MKDOCS_METHOD" == 'PIP' ]]; then
    if [[ "$INST64_MKDOCS_VERSION" == 'latest' ]]; then
      version_target=''
    else
      version_target="==${INST64_MKDOCS_VERSION}.*"
    fi
    INST64_MKDOCS_PACKAGES="mkdocs${version_target}"
    INST64_MKDOCS_PACKAGES+=' Markdown'
    INST64_MKDOCS_PACKAGES+=' mdx-truly-sane-lists'
    INST64_MKDOCS_PACKAGES+=' mkdocs-autorefs'
    INST64_MKDOCS_PACKAGES+=' mkdocs-awesome-pages-plugin'
    INST64_MKDOCS_PACKAGES+=' mkdocs-exclude'
    INST64_MKDOCS_PACKAGES+=' mkdocs-include-markdown-plugin'
    INST64_MKDOCS_PACKAGES+=' mkdocs-markmap'
    INST64_MKDOCS_PACKAGES+=' mkdocs-material'
    INST64_MKDOCS_PACKAGES+=' mkdocs-mermaid2-plugin'
    INST64_MKDOCS_PACKAGES+=' mkdocs-minify-plugin'
    INST64_MKDOCS_PACKAGES+=' mkdocstrings'
    INST64_MKDOCS_PACKAGES+=' Pygments'
    INST64_MKDOCS_PACKAGES+=' pymdown-extensions'
  fi
  [[ -z "$INST64_MKDOCS_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_mkdocs_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
  bl64_py_setup
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_mkdocs_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  if [[ "$INST64_MKDOCS_METHOD" == 'PIP' ]]; then
    "${INST64_MKDOCS_CLI_NAME}" --version
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_mkdocs_initialize() {
  bl64_dbg_app_show_function
  bl64_os_check_version \
    "${BL64_OS_ALP}-3" \
    "${BL64_OS_UB}-22" &&
    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_MKDOCS_METHOD' \
      "$INST64_MKDOCS_METHOD" \
      'PIP' 'PIPX' &&
    bl64_check_privilege_not_root
}

#
# Main
#

declare inst64_mkdocs_installer_description='Install application: MKDocs'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_mkdocs_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_mkdocs_initialize &&
  inst64_mkdocs_prepare &&
  inst64_mkdocs_install &&
  inst64_mkdocs_verify
bl64_msg_show_batch_finish $? "$inst64_mkdocs_installer_description"
