#!/usr/bin/env bash
# Template: 2.0.1
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 1.1.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
# Enable debugging? Set to YES to enable
export INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Base path for 3rd party applications
export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
# Location for temporary files
export INST64_TMP="${INST64_TMP:-/tmp}"

# shellcheck source=lib/bl64/bashlib64.bash
source "${INST64_BASHLIB64}/bashlib64.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

export INST64_NODEJS_PLATFORM="${INST64_NODEJS_PLATFORM:-linux-x64}"
export INST64_NODEJS_SOURCE="${INST64_NODEJS_SOURCE:-https://nodejs.org/dist}"
export INST64_NODEJS_TARGET="${INST64_NODEJS_TARGET:-${INST64_OPT_ROOT}/nodejs}"
export INST64_NODEJS_VERSION="${INST64_NODEJS_VERSION:-20.10.0}"
# Installation method
export INST64_NODEJS_METHOD="${INST64_NODEJS_METHOD:-CUSTOM}"

export INST64_NODEJS_PACKAGE_URL=''
export INST64_NODEJS_INSTALLER=''
export INST64_NODEJS_PACKAGES=''
export INST64_NODEJS_CLI_NAME_NODE='node'
export INST64_NODEJS_CLI_NAME_NPM='npm'
export INST64_NODEJS_CLI_NAME_NPX='npx'

#
# Functions
#

function inst64_nodejs_install_custom_package() {
  bl64_dbg_app_show_function
  local work_path=''
  local app_target_mode='0755'
  local app_target_owner='root'
  local app_cli_source="${INST64_NODEJS_PACKAGES%.tar.gz}/bin"
  local app_component=''

  bl64_msg_show_task 'download application'
  work_path="$(bl64_fs_create_tmpdir)" &&
    bl64_rxtx_web_get_file "${INST64_NODEJS_PACKAGE_URL}/${INST64_NODEJS_PACKAGES}" "${work_path}/${INST64_NODEJS_PACKAGES}" ||
    return $?

  bl64_msg_show_task 'deploy application'
  bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_NODEJS_TARGET" &&
    bl64_arc_open_tar "${work_path}/${INST64_NODEJS_PACKAGES}" "${INST64_NODEJS_TARGET}" ||
    return $?

  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
  for app_component in "$INST64_NODEJS_CLI_NAME_NODE" "$INST64_NODEJS_CLI_NAME_NPM" "$INST64_NODEJS_CLI_NAME_NPX"; do
    bl64_fs_create_symlink \
      "${INST64_NODEJS_TARGET}/${app_cli_source}/$app_component" "${INST64_LOCAL_BIN}/${app_component}" "$BL64_VAR_ON" ||
      return $?
  done

  bl64_msg_show_task 'cleanup temporary files'
  bl64_fs_rm_tmpdir "$work_path"
  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_nodejs_install() {
  bl64_dbg_app_show_function
  inst64_nodejs_select_packages || return $?
  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
    inst64_nodejs_install_custom_package
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_nodejs_select_packages() {
  bl64_dbg_app_show_function
  local package_prefix=''
  local package_sufix=''
  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
    package_prefix='node-'
    package_sufix='.tar.gz'
    INST64_NODEJS_PACKAGES="${package_prefix}v${INST64_NODEJS_VERSION}-${INST64_NODEJS_PLATFORM}${package_sufix}"
    INST64_NODEJS_PACKAGE_URL="${INST64_NODEJS_SOURCE}/v${INST64_NODEJS_VERSION}"
  fi
  [[ -z "$INST64_NODEJS_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_nodejs_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
  bl64_arc_setup
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_nodejs_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
    "${INST64_LOCAL_BIN}/${INST64_NODEJS_CLI_NAME_NODE}" --version &&
      "${INST64_LOCAL_BIN}/${INST64_NODEJS_CLI_NAME_NPM}" --version &&
      "${INST64_LOCAL_BIN}/${INST64_NODEJS_CLI_NAME_NPX}" --version
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_nodejs_initialize() {
  bl64_dbg_app_show_function
  bl64_os_check_compatibility \
    "${BL64_OS_UB}-22" &&
    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_NODEJS_METHOD' \
      "$INST64_NODEJS_METHOD" \
      'CUSTOM' &&
    bl64_check_privilege_root
}

#
# Main
#

declare inst64_nodejs_installer_description='Install application: NodeJS'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$inst64_nodejs_installer_description"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_nodejs_initialize &&
  inst64_nodejs_prepare &&
  inst64_nodejs_install &&
  inst64_nodejs_verify
bl64_msg_show_batch_finish $? "$inst64_nodejs_installer_description"
