#!/usr/bin/env bash
# Template: install-bl64-external-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64"

#
# Globals
#

# Installation method
declare INST64_REPOELREPO_METHOD="${INST64_REPOELREPO_METHOD:-AUTO}"

# App information
INST64_APP_NAME='repoelrepo'
INST64_APP_ID='REPOELREPO'
INST64_APP_FULL_NAME='El Repo - Community supported hardware packages for Enterprise Linux'
INST64_APP_DOC_INSTALL='https://elrepo.org/wiki/doku.php?id=start'

#
# Functions
#

function my_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_prepare || return 0
}

function my_install() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_install || return 0
  if [[ "$INST64_REPOELREPO_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    inst64_lib_pkg_install
  fi
}

function my_setup() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_setup || return 0
}

function my_verify() {
  bl64_dbg_app_show_function
}

function my_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_method_check \
    "$INST64_METHOD_AUTO" \
    "$INST64_METHOD_EXTERNAL" ||
    return $?
  if [[ "$INST64_REPOELREPO_METHOD" == "$INST64_METHOD_AUTO" ]]; then
    INST64_REPOELREPO_METHOD="$INST64_METHOD_EXTERNAL"
  fi
}

function my_select_platform() {
  bl64_dbg_app_show_function
  inst64_lib_show_task_select_platform
}

function my_select_packages() {
  bl64_dbg_app_show_function
  inst64_lib_show_task_select_packages
  if [[ "$INST64_REPOELREPO_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    # shellcheck disable=SC2249
    case "$BL64_OS_DISTRO" in
      "${BL64_OS_ALM}"-8.* | "${BL64_OS_RCK}"-8.* | "${BL64_OS_CNT}"-8.* | "${BL64_OS_OL}"-8.* | "${BL64_OS_RHEL}"-8.*) INST64_PKG_MAIN='https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm' ;;
      "${BL64_OS_ALM}"-9.* | "${BL64_OS_RCK}"-9.* | "${BL64_OS_CNT}"-9.* | "${BL64_OS_OL}"-9.* | "${BL64_OS_RHEL}"-9.*) INST64_PKG_MAIN='https://www.elrepo.org/elrepo-release-9.el9.elrepo.noarch.rpm' ;;
      "${BL64_OS_ALM}"-10.* | "${BL64_OS_RCK}"-10.* | "${BL64_OS_CNT}"-10.* | "${BL64_OS_OL}"-10.* | "${BL64_OS_ORHE}"-10.*) INST64_PKG_MAIN='https://www.elrepo.org/elrepo-release-10.el10.elrepo.noarch.rpm' ;;
    esac
  fi
  inst64_lib_base_check_package
}

function my_initialize() {
  bl64_dbg_app_show_function
  my_select_method &&
    inst64_lib_base_setup ||
    return $?

  if [[ "$INST64_REPOELREPO_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    bl64_os_check_flavor \
      "$BL64_OS_FLAVOR_REDHAT" ||
      return $?
  fi

  my_select_platform &&
    my_select_packages ||
    return $?

  inst64_lib_base_finalize
}

#
# Main
#

bl64_lib_script_version_set '1.0.1'
inst64_lib_base_initialize
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_initialize &&
  my_prepare &&
  my_install &&
  my_setup &&
  my_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
