#!/usr/bin/env bash
# Template: install-binary-1.0.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck source-path=lib/bl64 disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
# shellcheck source-path=src disable=SC2015
source "${BL64_SCRIPT_PATH}/lib-bl64" ||
  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }

#
# Globals
#

# Installation method
declare INST64_7ZIP_METHOD="${INST64_7ZIP_METHOD:-BINARY}"
# Installation destination
declare INST64_7ZIP_TARGET="${INST64_7ZIP_TARGET:-}"
# Hardware architecture
declare INST64_7ZIP_PLATFORM="${INST64_7ZIP_PLATFORM:-}"
# Application version
declare INST64_7ZIP_VERSION="${INST64_7ZIP_VERSION:-latest}"

INST64_APP_NAME='7zip'
INST64_APP_ID='7ZIP'
INST64_APP_FULL_NAME='7-Zip'
INST64_CLI_NAME='7zz'

INST64_GH_REPO_NAME='7zip'
INST64_GH_REPO_OWNER='ip7z'
INST64_PKG_MAIN_PREFIX='7z'
INST64_PKG_MAIN_SUFFIX='.tar.xz'
INST64_CPU_DARWIN_ARM64='mac'
INST64_CPU_LINUX_AMD64='linux-x64'
INST64_CPU_LINUX_ARM64='linux-arm64'

#
# Functions
#

function inst64_7zip_install_binary() {
  bl64_dbg_app_show_function
  local work_path=''
  local app_work_path="${INST64_CLI_NAME}"

  bl64_msg_show_task 'download application'
  work_path="$(bl64_fs_create_tmpdir)" || return $?
  bl64_rxtx_github_get_asset \
    "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME" "$INST64_7ZIP_VERSION" "$INST64_PKG_MAIN" "${work_path}/${INST64_PKG_MAIN}" &&
    bl64_arc_open_tar "${work_path}/${INST64_PKG_MAIN}" "${work_path}" ||
    return $?

  bl64_msg_show_task 'deploy application'
  bl64_fs_dir_create "$INST64_TARGET_MODE" "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" "$INST64_7ZIP_TARGET" &&
    bl64_fs_path_copy "$INST64_CLI_MODE" "$INST64_TARGET_MODE" "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" "$INST64_7ZIP_TARGET" "${work_path}/${app_work_path}" ||
    return $?

  bl64_msg_show_task 'cleanup temporary files'
  bl64_fs_rm_tmpdir "$work_path"
  return 0
}

function inst64_7zip_prepare() {
  bl64_dbg_app_show_function
  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 0
  bl64_msg_show_task 'prepare deployment'
  if [[ "$INST64_7ZIP_METHOD" == 'BINARY' ]]; then
    inst64_lib_base_create_path
  fi
}

function inst64_7zip_install() {
  bl64_dbg_app_show_function
  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 0
  if [[ "$INST64_7ZIP_METHOD" == 'BINARY' ]]; then
    inst64_7zip_install_binary
  fi
}

function inst64_7zip_setup() {
  bl64_dbg_app_show_function
  local app_cli_source=''
  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 0
  if [[ "$INST64_7ZIP_METHOD" == 'BINARY' ]]; then
    app_cli_source="${INST64_7ZIP_TARGET}/${INST64_CLI_NAME}"
    bl64_msg_show_task "publish application to searchable path (${INST64_CLI_PATH})"
    # shellcheck disable=SC2086
    bl64_fs_symlink_create "${app_cli_source}" "${INST64_CLI_PATH}/${INST64_CLI_NAME}" "$BL64_VAR_ON"
  fi
}

function inst64_7zip_verify() {
  bl64_dbg_app_show_function
  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 0
  bl64_msg_show_task 'verify deployment'
  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" -h &&
    inst64_lib_app_register_version
}

function inst64_7zip_select_platform() {
  bl64_dbg_app_show_function
  if [[ "$INST64_7ZIP_METHOD" == 'BINARY' ]]; then
    if [[ -z "$INST64_7ZIP_PLATFORM" ]]; then
      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
        INST64_7ZIP_PLATFORM="$INST64_CPU_DARWIN_ARM64"
      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
        INST64_7ZIP_PLATFORM="$INST64_CPU_LINUX_AMD64"
      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
        INST64_7ZIP_PLATFORM="$INST64_CPU_LINUX_ARM64"
      else
        inst64_lib_alert_incompatible_platform
        return $?
      fi
    fi
  fi
  [[ -z "$INST64_7ZIP_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
  return 0
}

function inst64_7zip_select_packages() {
  bl64_dbg_app_show_function
  local version_string=''
  if [[ "$INST64_7ZIP_METHOD" == 'BINARY' ]]; then
    if [[ "$INST64_7ZIP_VERSION" == 'latest' ]]; then
      INST64_7ZIP_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME")" ||
        return $?
    fi
    version_string="${INST64_7ZIP_VERSION#v}"
    version_string="${version_string//./}"
    INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${version_string}-${INST64_7ZIP_PLATFORM}${INST64_PKG_MAIN_SUFFIX}"
  fi
  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

function inst64_7zip_initialize() {
  bl64_dbg_app_show_function
  inst64_lib_app_check_method \
    'BINARY' &&
    inst64_lib_base_set_system_wide &&
    inst64_lib_base_set_path &&
    inst64_lib_target_set_owner &&
    inst64_lib_target_set_path &&
    inst64_lib_cli_set_path ||
    return $?

  if [[ "$INST64_7ZIP_METHOD" == 'BINARY' ]]; then
    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
      bl64_check_privilege_root ||
        return $?
    fi
    bl64_arc_setup ||
      return $?
  fi

  inst64_7zip_select_platform &&
    inst64_7zip_select_packages ||
    return $?
  inst64_lib_app_check_installed && return 0
  inst64_lib_show_parameters
}

#
# Main
#

bl64_lib_script_version_set '1.0.0'
bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_7zip_initialize &&
  inst64_7zip_prepare &&
  inst64_7zip_install &&
  inst64_7zip_setup &&
  inst64_7zip_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
