#!/usr/bin/env bash
# Template: install-bl64-custom-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64" ||
  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }

#
# Globals
#

# Installation method
declare INST64_BASHIT_METHOD="${INST64_BASHIT_METHOD:-CUSTOM}"
# Installation destination
declare INST64_BASHIT_TARGET="${HOME}/.bashit"
# Hardware architecture
declare INST64_BASHIT_PLATFORM="${INST64_BASHIT_PLATFORM:-}"
# Application version
declare INST64_BASHIT_VERSION="${INST64_BASHIT_VERSION:-latest}"

INST64_APP_NAME='bashit'
INST64_APP_ID='BASHIT'
INST64_APP_FULL_NAME='BashIt - Bash Framework'
INST64_CLI_NAME='install.sh'

INST64_GIT_SERVER='https://github.com/Bash-it'
INST64_GIT_REPO='bash-it.git'
INST64_GIT_BRANCH='master'
INST64_SYSTEM_WIDE='NO'
INST64_APP_INSTALLER='install.sh'

#
# Functions
#

function inst64_install_custom() {
  bl64_dbg_app_show_function

  inst64_lib_task_download
  inst64_lib_staging_create &&
    inst64_lib_git_get_dir ||
    return $?

  inst64_lib_task_deploy
  inst64_lib_target_normalize &&
    inst64_lib_cli_normalize &&
    "${INST64_BASHIT_TARGET}/${INST64_APP_INSTALLER}" \
    --silent \
    --overwrite-backup ||
    return $?

  inst64_lib_task_cleanup
  inst64_lib_staging_remove
}

function inst64_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_step_prepare || return 0
  if [[ "$INST64_BASHIT_METHOD" == 'CUSTOM' ]]; then
    inst64_lib_base_create_path
  fi
}

function inst64_install() {
  bl64_dbg_app_show_function
  inst64_lib_step_install || return 0
  if [[ "$INST64_BASHIT_METHOD" == 'CUSTOM' ]]; then
    inst64_install_custom
  fi
}

function inst64_setup() {
  bl64_dbg_app_show_function
  inst64_lib_step_setup || return 0
  if [[ "$INST64_BASHIT_METHOD" == 'CUSTOM' ]]; then
    inst64_lib_task_publish
    inst64_lib_cli_promote
  fi
}

function inst64_verify() {
  bl64_dbg_app_show_function
  inst64_lib_step_verify || return 0
  [[ -d "$INST64_BASHIT_TARGET" ]]
}

function inst64_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_app_check_method \
    'AUTO' \
    'CUSTOM' ||
    return $?
  if [[ "$INST64_BASHIT_METHOD" == 'AUTO' ]]; then
    INST64_BASHIT_METHOD='CUSTOM'
  fi
}

function inst64_select_platform() {
  bl64_dbg_app_show_function
  return 0
}

function inst64_select_packages() {
  bl64_dbg_app_show_function
  return 0
}

function inst64_initialize() {
  bl64_dbg_app_show_function
  inst64_select_method &&
    inst64_lib_base_initialize ||
    return $?

  if [[ "$INST64_BASHIT_METHOD" == 'CUSTOM' ]]; then
    inst64_lib_app_check_mode_user &&
      bl64_check_privilege_not_root &&
      bl64_arc_setup ||
      return $?
  fi

  inst64_select_platform &&
    inst64_select_packages &&
    inst64_lib_cli_set_path ||
    return $?

  inst64_lib_app_check_installed && return 0
  inst64_lib_message_show_parameters
}

#
# Main
#

bl64_lib_script_version_set '2.0.0'
bl64_msg_set_format "$INST64_VERBOSE" && bl64_msg_all_enable_verbose && bl64_dbg_set_level "$INST64_DEBUG" 
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
inst64_initialize &&
  inst64_prepare &&
  inst64_install &&
  inst64_setup &&
  inst64_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
