#!/usr/bin/env bash
# Template: install-bl64-binary-1.1.0
# Template: install-bl64-external-1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64"

#
# Globals
#

# Installation method
declare INST64_STEPCLI_METHOD="${INST64_STEPCLI_METHOD:-AUTO}"
# Installation destination
declare INST64_STEPCLI_TARGET="${INST64_STEPCLI_TARGET:-}"
# Hardware architecture
declare INST64_STEPCLI_PLATFORM="${INST64_STEPCLI_PLATFORM:-}"
# Application version
declare INST64_STEPCLI_VERSION="${INST64_STEPCLI_VERSION:-latest}"
# Enable development packages?
declare INST64_STEPCLI_DEVELOPMENT="${INST64_STEPCLI_DEVELOPMENT:-NO}"

INST64_APP_NAME='stepcli'
INST64_APP_ID='STEPCLI'
INST64_APP_FULL_NAME='Step CLI - Public Key Infrastructure management tool'
INST64_CLI_NAME='step'
INST64_APP_DOC_INSTALL='https://smallstep.com/docs/step-cli/installation/'

INST64_GH_REPO_NAME='cli'
INST64_GH_REPO_OWNER='smallstep'
INST64_PKG_MAIN_PREFIX='step_'
INST64_PKG_MAIN_SUFFIX='.tar.gz'
INST64_CPU_DARWIN_ARM64='arm64'
INST64_CPU_LINUX_AMD64='amd64'
INST64_CPU_LINUX_ARM64='arm64'
INST64_OS_REPO_NAME='smallstep'
INST64_OS_SOURCE_YUM='https://packages.smallstep.com/stable/fedora'
INST64_OS_REPO_KEY_YUM='https://packages.smallstep.com/keys/smallstep-0x889B19391F774443.gpg'

#
# Functions
#

function my_prepare_repository() {
  bl64_dbg_app_show_function
  local repository_url=''
  local repository_key=''
  local repository_apt_suite=''
  local repository_apt_component=''

  if bl64_os_is_flavor "$BL64_OS_FLAVOR_FEDORA" || bl64_os_is_flavor "$BL64_OS_FLAVOR_REDHAT"; then
    repository_url="${INST64_OS_SOURCE_YUM}"
    repository_key="$INST64_OS_REPO_KEY_YUM"
  fi

  inst64_lib_pkg_repo_add \
    "$repository_url" "$repository_key" \
    "$repository_apt_suite" "$repository_apt_component"
}

function my_install_binary() {
  bl64_dbg_app_show_function

  inst64_lib_show_task_download
  inst64_lib_staging_create &&
    inst64_lib_custom_gh_get_asset &&
    inst64_lib_staging_open_tar ||
    return $?

  inst64_lib_show_task_deploy
  inst64_lib_target_create &&
    inst64_lib_target_populate ||
    return $?

  inst64_lib_show_task_cleanup
  inst64_lib_staging_remove
}

function my_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_prepare || return 0
  if [[ "$INST64_STEPCLI_METHOD" == "$INST64_METHOD_BINARY" ]]; then
    inst64_lib_base_create_path
    INST64_WORK_PATH_SOURCE="${INST64_PKG_MAIN_PREFIX}${INST64_STEPCLI_VERSION#v}/bin/${INST64_CLI_NAME}"
  elif [[ "$INST64_STEPCLI_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    my_prepare_repository
  fi
}

function my_install() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_install || return 0
  if [[ "$INST64_STEPCLI_METHOD" == "$INST64_METHOD_BINARY" ]]; then
    my_install_binary
  elif [[ "$INST64_STEPCLI_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    inst64_lib_pkg_install
  fi
}

function my_setup() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_setup || return 0
  if [[ "$INST64_STEPCLI_METHOD" == "$INST64_METHOD_BINARY" ]]; then
    inst64_lib_show_task_publish
    inst64_lib_setup_promote
  fi
}

function my_verify() {
  bl64_dbg_app_show_function
  inst64_lib_show_step_verify || return 0
  "${INST64_CLI_TARGET}" --version || return $?
  if [[ "$INST64_STEPCLI_METHOD" == "$INST64_METHOD_BINARY" ]]; then
    inst64_lib_verify_register_version
  fi
}

function my_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_method_check \
    "$INST64_METHOD_AUTO" \
    "$INST64_METHOD_BINARY" \
    "$INST64_METHOD_EXTERNAL" ||
    return $?
  if [[ "$INST64_STEPCLI_METHOD" == "$INST64_METHOD_AUTO" ]]; then
    INST64_STEPCLI_METHOD="$INST64_METHOD_BINARY"
  fi
}

function my_select_platform() {
  bl64_dbg_app_show_function
  inst64_lib_show_task_select_platform
  if [[ "$INST64_STEPCLI_METHOD" == "$INST64_METHOD_BINARY" ]]; then
    if [[ -z "$INST64_STEPCLI_PLATFORM" ]]; then
      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
        INST64_STEPCLI_PLATFORM="$INST64_CPU_DARWIN_ARM64"
      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
        INST64_STEPCLI_PLATFORM="$INST64_CPU_LINUX_AMD64"
      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
        INST64_STEPCLI_PLATFORM="$INST64_CPU_LINUX_ARM64"
      fi
    fi
    inst64_lib_base_check_platform
  fi
}

function my_select_packages() {
  bl64_dbg_app_show_function
  inst64_lib_show_task_select_packages
  if [[ "$INST64_STEPCLI_METHOD" == "$INST64_METHOD_BINARY" ]]; then
    if [[ "$INST64_STEPCLI_VERSION" == 'latest' ]]; then
      INST64_STEPCLI_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME")" ||
        return $?
    fi
    if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" ]]; then
      INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}darwin_${INST64_STEPCLI_VERSION#v}_${INST64_STEPCLI_PLATFORM}${INST64_PKG_MAIN_SUFFIX}"
    elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" ]]; then
      INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}linux_${INST64_STEPCLI_VERSION#v}_${INST64_STEPCLI_PLATFORM}${INST64_PKG_MAIN_SUFFIX}"
    fi
  elif [[ "$INST64_STEPCLI_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    # shellcheck disable=SC2249
    case "$BL64_OS_FLAVOR" in
      "$BL64_OS_FLAVOR_FEDORA" | "$BL64_OS_FLAVOR_REDHAT")
        bl64_lib_flag_is_enabled "$INST64_STEPCLI_DEVELOPMENT" &&
          INST64_PKG_DEV=''
        INST64_PKG_MAIN='step-cli'
        ;;
    esac
    INST64_PKG_MAIN+=" ${INST64_PKG_DEV}"
  fi
  inst64_lib_base_check_package
}

function my_initialize() {
  bl64_dbg_app_show_function
  my_select_method &&
    inst64_lib_base_setup ||
    return $?

  if [[ "$INST64_STEPCLI_METHOD" == "$INST64_METHOD_EXTERNAL" ]]; then
    bl64_os_check_flavor \
      "$BL64_OS_FLAVOR_FEDORA" \
      "$BL64_OS_FLAVOR_REDHAT" ||
      return $?
  fi

  my_select_platform &&
    my_select_packages ||
    return $?

  inst64_lib_base_finalize
}

#
# Main
#

bl64_lib_script_version_set '1.0.1'
inst64_lib_base_initialize
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_initialize &&
  my_prepare &&
  my_install &&
  my_setup &&
  my_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
