#!/usr/bin/env bash
# Template: install-git-2.4.0
#   Skeleton: installer-base-2.4.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Home root
declare INST64_HOME="${HOME}/at64"
# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
# shellcheck source-path=lib/bl64 disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Enable debugging? Set to YES to enable
declare INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# User applications binaries location
declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
# Location for temporary files
declare INST64_TMP="${INST64_TMP:-/tmp}"
# Base path for 3rd party applications
declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
# Install system wide? Requires root privilege
declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"

declare INST64_GIT_SERVER="${INST64_GIT_SERVER:-https://github.com/nvm-sh}"
declare INST64_GIT_REPO="${INST64_GIT_REPO:-nvm.git}"
declare INST64_NVM_TARGET=''
declare INST64_GIT_BRANCH="${INST64_GIT_BRANCH:-master}"
# Installation method
declare INST64_NVM_METHOD="${INST64_NVM_METHOD:-GIT}"

declare INST64_APP_INSTALLER=''
declare INST64_APP_PACKAGES=''
declare INST64_CLI_NAME='nvm.sh'
declare INST64_CLI_PATH=''

#
# Functions
#

function inst64_nvm_install_git_repo() {
  bl64_dbg_app_show_function
  local app_target_mode='0755'
  local app_target_owner="$BL64_IAM_SYSTEM_USER"
  local app_target_group="$BL64_IAM_SYSTEM_GROUP"
  local app_cli_source="${INST64_CLI_NAME}"

  if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    app_target_owner="$BL64_VAR_DEFAULT"
    app_target_group="$BL64_VAR_DEFAULT"
  fi

  bl64_msg_show_task 'download application'
  bl64_rxtx_git_get_dir \
    "${INST64_GIT_SERVER}/${INST64_GIT_REPO}" \
    '.' \
    "$INST64_NVM_TARGET" \
    "$BL64_VAR_ON" \
    "$INST64_GIT_BRANCH" ||
    return $?

  bl64_msg_show_task 'deploy application'
  if [[ -n "$INST64_APP_INSTALLER" ]]; then
    "$INST64_APP_INSTALLER" ||
      return $?
  fi
  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    bl64_fs_path_permission_set "$app_target_mode" "$app_target_mode" "$app_target_owner" "$app_target_group" "$BL64_VAR_ON" \
      "$INST64_NVM_TARGET" ||
      return $?
  fi

  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    bl64_msg_show_task "publish application to searchable path (${INST64_CLI_PATH})"
    # shellcheck disable=SC2086
    bl64_fs_symlink_create "${INST64_NVM_TARGET}/${app_cli_source}" "$INST64_CLI_PATH" "$BL64_VAR_ON" ||
      return $?
  fi

  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_nvm_install() {
  bl64_dbg_app_show_function
  if [[ "$INST64_NVM_METHOD" == 'GIT' ]]; then
    inst64_nvm_install_git_repo
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_nvm_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_NVM_METHOD" == 'GIT' ]]; then
    INST64_APP_PACKAGES='NONE'
    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
      INST64_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_CLI_NAME}"
    else
      INST64_CLI_PATH="${INST64_NVM_TARGET}/${INST64_CLI_NAME}"
    fi
  fi
  [[ -z "$INST64_APP_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_nvm_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_nvm_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  [[ -s "$INST64_CLI_PATH" ]]
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_nvm_initialize() {
  bl64_dbg_app_show_function
  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
  fi
  if [[ -z "$INST64_OPT_ROOT" ]]; then
    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
  fi
  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    INST64_NVM_TARGET="${INST64_NVM_TARGET:-${INST64_OPT_ROOT}/nvm}"
  else
    INST64_NVM_TARGET="${INST64_NVM_TARGET:-${HOME}/.nvm}"
  fi
  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_NVM_METHOD' \
    "$INST64_NVM_METHOD" \
    'GIT' ||
    return $?

  if [[ "$INST64_NVM_METHOD" == 'GIT' ]]; then
    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
      bl64_check_privilege_root ||
        return $?
    fi
  fi
  inst64_nvm_select_packages ||
    return $?

  bl64_msg_show_setup 'Install application: Node Version Manager (NVM)' \
    'INST64_SYSTEM_WIDE' 'INST64_NVM_METHOD' \
    'INST64_GIT_SERVER' \
    'INST64_GIT_REPO' \
    'INST64_GIT_BRANCH' \
    'INST64_NVM_TARGET' \
    'INST64_CLI_PATH'
}

#
# Main
#

bl64_lib_script_version_set '1.0.0'
bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_nvm_initialize &&
  inst64_nvm_prepare &&
  inst64_nvm_install &&
  inst64_nvm_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
