#!/usr/bin/env bash
# Template: install-bl64-native-1.0.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
# shellcheck disable=SC2015
source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
source "${BL64_SCRIPT_PATH}/lib-bl64" ||
  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }

#
# Globals
#

# Installation method
declare INST64_MONGODBCLI_METHOD="${INST64_MONGODBCLI_METHOD:-NATIVE}"
# Application version
declare INST64_MONGODBCLI_VERSION="${INST64_MONGODBCLI_VERSION:-latest}"
# Enable development packages?
declare INST64_MONGODBCLI_DEVELOPMENT="${INST64_MONGODBCLI_DEVELOPMENT:-NO}"

# App information
INST64_APP_NAME='mongodbcli'
INST64_APP_ID='MONGODBCLI'
INST64_APP_FULL_NAME='MongoDB CLI'
INST64_CLI_NAME='mongosh'

INST64_OS_REPO_NAME='mongodb-org'
INST64_OS_SOURCE_YUM='https://repo.mongodb.org/yum'
INST64_OS_SOURCE_APT='https://repo.mongodb.org/apt'
INST64_OS_REPO_KEY_YUM='https://www.mongodb.org/static/pgp/server-6.0.asc'
INST64_OS_REPO_KEY_APT='https://www.mongodb.org/static/pgp/server-8.0.asc'

#
# Functions
#

function inst64_prepare_repository() {
  bl64_dbg_app_show_function
  local repository_url=''
  local repository_key=''
  local repository_apt_suite=''
  local repository_apt_component=''

  if bl64_os_is_flavor "$BL64_OS_FLAVOR_DEBIAN"; then
    repository_url="${INST64_OS_SOURCE_APT}/ubuntu"
    repository_key="$INST64_OS_REPO_KEY_APT"
    # shellcheck disable=SC2154
    repository_apt_suite="${VERSION_CODENAME}/mongodb-org/8.0"
    repository_apt_component='multiverse'
  elif bl64_os_is_flavor "$BL64_OS_FLAVOR_FEDORA" || bl64_os_is_flavor "$BL64_OS_FLAVOR_REDHAT"; then
    repository_url="${INST64_OS_SOURCE_YUM}/redhat/\$releasever/mongodb-org/6.0/\$basearch"
    repository_key="$INST64_OS_REPO_KEY_YUM"
  fi

  inst64_lib_pkg_repo_add \
    "$repository_url" "$repository_key" \
    "${repository_apt_suite}" "$repository_apt_component"
}

function inst64_install_native() {
  bl64_dbg_app_show_function
  inst64_lib_pkg_install
}

function inst64_prepare() {
  bl64_dbg_app_show_function
  inst64_lib_step_prepare || return 0
  if [[ "$INST64_MONGODBCLI_METHOD" == 'NATIVE' ]]; then
    inst64_prepare_repository
  fi
}

function inst64_install() {
  bl64_dbg_app_show_function
  inst64_lib_step_install || return 0
  if [[ "$INST64_MONGODBCLI_METHOD" == 'NATIVE' ]]; then
    inst64_install_native
  fi
}

function inst64_setup() {
  bl64_dbg_app_show_function
  inst64_lib_step_setup || return 0
}

function inst64_verify() {
  bl64_dbg_app_show_function
  inst64_lib_step_verify || return 0
  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version
}

function inst64_select_method() {
  bl64_dbg_app_show_function
  inst64_lib_app_check_method \
    'AUTO' \
    'NATIVE' ||
    return $?
  if [[ "$INST64_MONGODBCLI_METHOD" == 'AUTO' ]]; then
    INST64_MONGODBCLI_METHOD='NATIVE'
  fi
}

function inst64_select_platform() {
  bl64_dbg_app_show_function
  return 0
}

function inst64_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_MONGODBCLI_METHOD" == 'NATIVE' ]]; then
    bl64_lib_flag_is_enabled "$INST64_MONGODBCLI_DEVELOPMENT" &&
      INST64_PKG_DEV=''
    INST64_PKG_MAIN='mongodb-org-tools mongodb-mongosh'
    INST64_PKG_MAIN+=" ${INST64_PKG_DEV}"
  fi
  inst64_lib_package_check_definition
}

function inst64_initialize() {
  bl64_dbg_app_show_function
  inst64_select_method &&
    inst64_lib_base_initialize ||
    return $?

  if [[ "$INST64_MONGODBCLI_METHOD" == 'NATIVE' ]]; then
    bl64_os_check_flavor \
        "$BL64_OS_FLAVOR_DEBIAN" \
        "$BL64_OS_FLAVOR_FEDORA" \
        "$BL64_OS_FLAVOR_REDHAT" ||
      return $?
  fi

  inst64_select_platform &&
    inst64_select_packages &&
    inst64_lib_cli_set_path ||
    return $?

  inst64_lib_app_check_installed && return 0
  inst64_lib_message_show_parameters
}

#
# Main
#

bl64_lib_script_version_set '2.0.1'
bl64_msg_set_format "$INST64_VERBOSE" && bl64_msg_all_enable_verbose && bl64_dbg_set_level "$INST64_DEBUG" 
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
inst64_initialize &&
  inst64_prepare &&
  inst64_install &&
  inst64_setup &&
  inst64_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
