#!/usr/bin/env bash
# Template: 2.0.1
# Snippet: setup-environment-2.0.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Home root
declare INST64_HOME="${HOME}/at64"
# BashLib64 location
declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
# shellcheck source=lib/bl64/bashlib64.bash
source "${INST64_BASHLIB64}/bashlib64.bash" ||
  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }

#
# Globals
#

# Enable debugging? Set to YES to enable
declare INST64_DEBUG="${INST64_DEBUG:-}"
# Base path for local applications
declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
# Local applications binaries location
declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
# Location for temporary files
declare INST64_TMP="${INST64_TMP:-/tmp}"
# Base path for 3rd party applications
declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
# Install system wide? Requires root privilege
declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"

# Installation method
declare INST64_RUBY_METHOD="${INST64_RUBY_METHOD:-NATIVE}"
# Enable development packages?
declare INST64_RUBY_DEVELOPMENT="${INST64_RUBY_DEVELOPMENT:-$BL64_VAR_OFF}"

declare INST64_RUBY_ENV='ruby.env'
declare INST64_RUBY_PACKAGES=''
declare INST64_RUBY_CLI_NAME='ruby'
declare INST64_RUBY_ENV_NAME='ruby'

#
# Functions
#

function inst64_ruby_install_os_packages() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'deploy packages'
  # shellcheck disable=SC2086
  bl64_pkg_deploy $INST64_RUBY_PACKAGES
}

#######################################
# Perform post installation setup
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Setup progress
# Returns:
#   0: setup completed ok
#   >0: unable to setup
#######################################
function inst64_ruby_setup() {
  bl64_dbg_app_show_function
  local mode='0644'

  bl64_msg_show_task 'setup application environment'
  INST64_RUBY_ENV="${INST64_LOCAL_BIN}/${INST64_RUBY_ENV}"
  bl64_msg_show_subtask "create shell env file (${INST64_RUBY_ENV})"
  # shellcheck disable=SC2016
  printf '#!/usr/bin/env sh
#
# Ruby
#
# * Define application environment variables
#

GEM_HOME="${HOME}/gems"
export GEM_HOME
PATH="${GEM_HOME}/bin:${PATH}"
' >"$INST64_RUBY_ENV" &&
    bl64_fs_run_chmod "$mode" "$INST64_RUBY_ENV" ||
    return $?

  return 0
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_ruby_install() {
  bl64_dbg_app_show_function
  inst64_ruby_select_packages || return $?
  if [[ "$INST64_RUBY_METHOD" == 'NATIVE' ]]; then
    inst64_ruby_install_os_packages
  fi
}

#######################################
# Select installation packages and related information
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package name list
# Returns:
#   0: selection ok
#   >0: selection failed
#######################################
function inst64_ruby_select_packages() {
  bl64_dbg_app_show_function
  if [[ "$INST64_RUBY_METHOD" == 'NATIVE' ]]; then
    if bl64_os_is_distro "$BL64_OS_UB"; then
      INST64_RUBY_PACKAGES='ruby ruby-rubygems'
      bl64_lib_flag_is_enabled "$INST64_RUBY_DEVELOPMENT" &&
        INST64_RUBY_PACKAGES="${INST64_RUBY_PACKAGES} ruby-dev"
    fi
  fi
  [[ -z "$INST64_RUBY_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
  return 0
}

#######################################
# Prepare installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Preparation progress and errors
# Returns:
#   0: preparation ok
#   >0: preparation failed
#######################################
function inst64_ruby_prepare() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'prepare deployment'
  bl64_pkg_setup
}

#######################################
# Verify installation
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Verification progress and errors
# Returns:
#   0: verification ok
#   >0: verification failed
#######################################
function inst64_ruby_verify() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'verify deployment'
  if [[ "$INST64_RUBY_METHOD" == 'NATIVE' ]]; then
    "/usr/bin/${INST64_RUBY_CLI_NAME}" --version
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: initialization failed
#######################################
function inst64_ruby_initialize() {
  bl64_dbg_app_show_function
  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
  fi
  if [[ -z "$INST64_OPT_ROOT" ]]; then
    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
  fi
  bl64_os_check_compatibility \
    "${BL64_OS_UB}-22" &&
    bl64_check_privilege_root &&
    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_RUBY_METHOD' \
      "$INST64_RUBY_METHOD" \
      'NATIVE'
  # shellcheck disable=SC2181
  (($? == 0)) && bl64_msg_show_setup 'Install application: Ruby' \
    'INST64_RUBY_METHOD' 'INST64_SYSTEM_WIDE' 
}

#
# Main
#

bl64_lib_script_version_set '1.2.0'
bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"

[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
inst64_ruby_initialize &&
  inst64_ruby_prepare &&
  inst64_ruby_install &&
  inst64_ruby_setup &&
  inst64_ruby_verify
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
