#!/usr/bin/env bash
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

function inst64_lib_python_install_pip() {
  bl64_dbg_app_show_function

  if [[ -n "$INST64_PKG_PRE" ]]; then
    # shellcheck disable=SC2086
    bl64_py_pip_usr_install $INST64_PKG_PRE ||
      return $?
  fi
  # shellcheck disable=SC2086
  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    bl64_py_pip_usr_deploy $INST64_PKG_MAIN ||
    return $?
  if [[ -n "$INST64_PKG_POST" ]]; then
    # shellcheck disable=SC2086
    bl64_py_pip_usr_install $INST64_PKG_POST ||
      return $?
  fi
  return 0
}

function inst64_lib_python_install_pipx() {
  bl64_dbg_app_show_function

  if [[ -n "$INST64_PKG_PRE" ]]; then
    # shellcheck disable=SC2086
    bl64_py_run_pipx install --preinstall $INST64_PKG_PRE $INST64_PKG_MAIN ||
      return $?
  else
    # shellcheck disable=SC2086
    bl64_py_run_pipx install $INST64_PKG_MAIN ||
      return $?
  fi
  if [[ -n "$INST64_PKG_POST" ]]; then
    # shellcheck disable=SC2086
    bl64_py_run_pipx inject $INST64_PKG_MAIN $INST64_PKG_POST ||
      return $?
  fi
  return 0
}

function inst64_lib_python_install_uv() {
  bl64_dbg_app_show_function

  if [[ -n "$INST64_PKG_PRE" ]]; then
    # shellcheck disable=SC2086
    inst64_lib_command_run_uv tool install --with $INST64_PKG_PRE $INST64_PKG_MAIN ||
      return $?
  else
    # shellcheck disable=SC2086
    inst64_lib_command_run_uv tool install $INST64_PKG_MAIN ||
      return $?
  fi
  if [[ -n "$INST64_PKG_POST" ]]; then
    # shellcheck disable=SC2086
    inst64_lib_command_run_uv tool install --with $INST64_PKG_POST $INST64_PKG_MAIN ||
      return $?
  fi
  return 0
}
