#!/usr/bin/env bash
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

function inst64_lib_go_install_go() {
  bl64_dbg_app_show_function
  local package_version="INST64_${INST64_APP_ID}_VERSION"

  bl64_check_parameter 'INST64_PKG_MAIN' &&
    bl64_check_parameter "$package_version" ||
    return $?

  cd "$HOME" || return $?
  inst64_lib_command_run_go \
    install \
    -trimpath \
    -v \
    "${INST64_PKG_MAIN}@${!package_version}"
}
