#!/usr/bin/env bash
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

function inst64_lib_base_set_path_root() {
  bl64_dbg_app_show_function
  local method="INST64_${INST64_APP_ID}_METHOD"

  bl64_check_parameter "$method" || return $?
  [[ "${!method}" =~ ^("$INST64_METHOD_AUR"|"$INST64_METHOD_NATIVE"|"$INST64_METHOD_PACKAGE"|"$INST64_METHOD_EXTERNAL"|"$INST64_METHOD_PIP"|"$INST64_METHOD_PIPX"|"$INST64_METHOD_UV"|"$INST64_METHOD_NPM"|"$INST64_METHOD_GO"|"$INST64_METHOD_FPAK"|"$INST64_METHOD_SNAP"|"$INST64_METHOD_KREW"|"$INST64_METHOD_BREW")$ ]] &&
    return 0

  if [[ -z "$INST64_OPT_ROOT" ]]; then
    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
      if [[ -n "$INST64_ROOT_PATH_DEFAULT_SYSTEM" ]]; then
        INST64_OPT_ROOT="$INST64_ROOT_PATH_DEFAULT_SYSTEM"
      else
        INST64_OPT_ROOT='/opt'
      fi
    else
      if [[ -n "$INST64_ROOT_PATH_DEFAULT_USER" ]]; then
        INST64_OPT_ROOT="$INST64_ROOT_PATH_DEFAULT_USER"
      else
        INST64_OPT_ROOT="$INST64_HOME"
      fi
    fi
  fi
  bl64_dbg_app_show_vars 'INST64_OPT_ROOT'
}

function inst64_lib_base_create_path() {
  bl64_dbg_app_show_function
  local method="INST64_${INST64_APP_ID}_METHOD"

  bl64_check_parameter "$method" || return $?
  [[ "${!method}" =~ ^("$INST64_METHOD_AUR"|"$INST64_METHOD_NATIVE"|"$INST64_METHOD_PACKAGE"|"$INST64_METHOD_EXTERNAL"|"$INST64_METHOD_PIP"|"$INST64_METHOD_PIPX"|"$INST64_METHOD_UV"|"$INST64_METHOD_NPM"|"$INST64_METHOD_GO"|"$INST64_METHOD_FPAK"|"$INST64_METHOD_SNAP"|"$INST64_METHOD_KREW"|"$INST64_METHOD_BREW")$ ]] &&
    return 0

  if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    if bl64_lib_flag_is_enabled "$INST64_CLI_PROMOTE"; then
      bl64_bsh_xdg_create "$HOME" ||
        return $?
    fi
    if ! bl64_lib_flag_is_enabled "$INST64_TARGET_REQUESTED"; then
      bl64_fs_dir_create "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" \
        "$INST64_OPT_ROOT"
    fi
  fi
}

function inst64_lib_base_setup() {
  bl64_dbg_app_show_function
  local method="INST64_${INST64_APP_ID}_METHOD"

  if [[ -z "${!method}" ]]; then
    bl64_msg_show_fatal 'unable to determine installation method. Installation can not proceed'
    return $BL64_LIB_ERROR_TASK_FAILED
  fi

  bl64_msg_show_phase 'initialize installer'
  if ! bl64_lib_flag_is_enabled "$INST64_STATUS_LEGACY"; then
    bl64_lib_script_minver_check "$INST64_LIB_VERSION_REQUIRED" ||
      return $?
  else
    bl64_msg_show_warning "BashLib64 library must be upgraded to ensure compatibility (current: ${BL64_VERSION} / required: ${INST64_LIB_VERSION_REQUIRED})"
  fi

  inst64_lib_type_set &&
    inst64_lib_base_set_path_root &&
    inst64_lib_target_set_owner &&
    inst64_lib_target_set_path &&
    inst64_lib_method_initialize &&
    inst64_lib_base_set_path_cli &&
    return 0

  bl64_msg_show_error 'installer initialization failed'
  return "$BL64_LIB_ERROR_TASK_FAILED"
}

function inst64_lib_base_finalize() {
  bl64_dbg_app_show_function

  inst64_lib_verify_check_installed && return 0
  inst64_lib_show_docs &&
    inst64_lib_show_parameters
}

function inst64_lib_base_initialize() {
  bl64_dbg_app_show_function
  local output="$BL64_MSG_OUTPUT_ANSI"
  local format="$BL64_MSG_FORMAT_FULL"

  bl64_dbg_set_level "$INST64_DEBUG"
  bl64_dbg_app_show_comments 'support legacy bl64 versions'
  if [[ $(type -t 'bl64_lib_script_minver_check') == 'function' ]]; then
    if ! bl64_fmt_version_is_less_than "$BL64_VERSION" '22.10.0'; then
      output="$BL64_MSG_OUTPUT_EMOJI"
      format="$BL64_MSG_FORMAT_FULL2"
    fi
  else
    INST64_STATUS_LEGACY='YES'
  fi

  bl64_msg_set_output "$output" &&
    bl64_msg_set_format "${INST64_VERBOSE:-$format}" &&
    bl64_msg_set_level "$INST64_VERBOSE_LEVEL" &&
    bl64_msg_help_set_about "Installer tool for: ${INST64_APP_FULL_NAME}" &&
    bl64_msg_help_show_about ||
    return $?

  if ! bl64_lib_flag_is_enabled "$INST64_STATUS_LEGACY" && [[ $(type -t 'bl64_msg_show_attention') == 'function' ]]; then
    bl64_msg_show_attention 'this installer is provided as-is without any warranties. Please ensure that you have verified the origin, license, and security status of the application before proceeding. Press CONTROL+C at any time to stop the installation task.'
  fi
  inst64_lib_show_globals
}

function inst64_lib_base_set_path_cli() {
  bl64_dbg_app_show_function
  local method="INST64_${INST64_APP_ID}_METHOD"

  bl64_check_parameter "$method" || return $?
  [[ -n "$INST64_CLI_PATH" ]] && return 0
  # shellcheck disable=SC2249
  case "${!method}" in
    "$INST64_METHOD_KREW")
      INST64_CLI_PATH="${HOME}/.krew/bin"
      ;;
    "$INST64_METHOD_BREW")
      INST64_CLI_PATH="${BL64_PKG_PATH_BREW_HOME}/bin"
      ;;
    "$INST64_METHOD_NPM")
      INST64_CLI_PATH="${HOME}/node_modules/.bin"
      ;;
    "$INST64_METHOD_GO")
      INST64_CLI_PATH="${HOME}/go/bin"
      ;;
    "$INST64_METHOD_FPAK")
      INST64_CLI_PATH='/var/lib/flatpak/exports/bin'
      ;;
    "$INST64_METHOD_SNAP")
      INST64_CLI_PATH='/snap/bin'
      ;;
    "$INST64_METHOD_PIPX" | "$INST64_METHOD_UV")
      INST64_CLI_PATH="${HOME}/.local/bin"
      ;;
    "$INST64_METHOD_PIP")
      INST64_CLI_PATH="${BL64_PY_PATH_PIP_USR_BIN}"
      ;;
    "$INST64_METHOD_AUR" | "$INST64_METHOD_NATIVE" | "$INST64_METHOD_PACKAGE" | "$INST64_METHOD_EXTERNAL")
      INST64_CLI_PATH='/usr/bin'
      ;;
    "$INST64_METHOD_BINARY" | "$INST64_METHOD_CUSTOM")
      if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
        INST64_CLI_PATH="${INST64_LOCAL_BIN}"
      else
        INST64_CLI_PATH="${INST64_USER_BIN}"
      fi
      ;;
  esac
}

function inst64_lib_base_check_package() {
  bl64_dbg_app_show_function
  bl64_check_parameter 'INST64_PKG_MAIN'
}

function inst64_lib_base_check_platform() {
  bl64_dbg_app_show_function
  local platform="INST64_${INST64_APP_ID}_PLATFORM"
  [[ -v "$platform" && -n "${!platform}" ]] && return 0
  bl64_os_raise_platform_unsupported
}

function inst64_lib_base_check_prereq_exe() {
  bl64_dbg_app_show_function "$@"
  local command_name="${1:-}"

  bl64_check_parameter 'command_name' ||
    return $?

  shift
  if [[ -z "$(bl64_bsh_command_locate_user "$command_name" "$@")" ]]; then
    bl64_msg_show_error "the installer was not able to find a required command. Install it and try again (command: ${command_name})"
    return "$BL64_LIB_ERROR_TASK_REQUIREMENTS"
  fi
  return 0
}

function inst64_lib_base_check_prereq_file() {
  bl64_dbg_app_show_function "$@"
  local file_about="${1:-}"
  local file_path="${2:-}"

  bl64_check_parameter 'file_about' &&
    bl64_check_parameter 'file_path' ||
    return $?

  if [[ ! -r "$file_path" ]]; then
    bl64_msg_show_error "the installer was not able to find a required file. Install it and try again (file: ${file_about})"
    return "$BL64_LIB_ERROR_TASK_REQUIREMENTS"
  fi
  return 0
}
