#!/usr/bin/env bash
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

function inst64_lib_target_set_path() {
  bl64_dbg_app_show_function
  local method="INST64_${INST64_APP_ID}_METHOD"
  local target="INST64_${INST64_APP_ID}_TARGET"
  local target_basename="$INST64_APP_NAME"

  bl64_check_parameter "$method" || return $?
  if [[ "${!method}" =~ ^("$INST64_METHOD_AUR"|"$INST64_METHOD_NATIVE"|"$INST64_METHOD_PACKAGE"|"$INST64_METHOD_EXTERNAL"|"$INST64_METHOD_PIP"|"$INST64_METHOD_PIPX"|"$INST64_METHOD_UV"|"$INST64_METHOD_NPM"|"$INST64_METHOD_GO"|"$INST64_METHOD_FPAK"|"$INST64_METHOD_SNAP"|"$INST64_METHOD_KREW"|"$INST64_METHOD_BREW")$ ]]; then
    bl64_dbg_app_show_comments 'TARGET is not used for this installation method'
    return 0
  fi

  if [[ ! -v "$target" || -z "${!target}" ]]; then
    bl64_dbg_app_show_comments 'No target specified, set default'
    if [[ -n "$INST64_TARGET_PATH_DEFAULT" ]]; then
      target_basename="$INST64_TARGET_PATH_DEFAULT"
    else
      if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
        [[ -n "$INST64_TARGET_PATH_DEFAULT_SYSTEM" ]] && target_basename="$INST64_TARGET_PATH_DEFAULT_SYSTEM"
      else
        [[ -n "$INST64_TARGET_PATH_DEFAULT_USER" ]] && target_basename="$INST64_TARGET_PATH_DEFAULT_USER"
      fi
    fi

    printf \
      -v "INST64_${INST64_APP_ID}_TARGET" \
      '%s/%s' \
      "${INST64_OPT_ROOT}" \
      "${target_basename}"
  else
    bl64_dbg_app_show_comments 'Using requested target'
    INST64_TARGET_REQUESTED='YES'
  fi
  bl64_dbg_app_show_vars "$target" 'INST64_TARGET_REQUESTED'
}

function inst64_lib_target_set_owner() {
  bl64_dbg_app_show_function
  local method="INST64_${INST64_APP_ID}_METHOD"

  bl64_check_parameter "$method" || return $?
  [[ "${!method}" =~ ^("$INST64_METHOD_AUR"|"$INST64_METHOD_NATIVE"|"$INST64_METHOD_PACKAGE"|"$INST64_METHOD_EXTERNAL"|"$INST64_METHOD_PIP"|"$INST64_METHOD_PIPX"|"$INST64_METHOD_UV"|"$INST64_METHOD_NPM"|"$INST64_METHOD_GO"|"$INST64_METHOD_FPAK"|"$INST64_METHOD_SNAP"|"$INST64_METHOD_KREW"|"$INST64_METHOD_BREW")$ ]] &&
    return 0

  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    INST64_TARGET_OWNER="$BL64_IAM_SYSTEM_USER"
    INST64_TARGET_GROUP="$BL64_IAM_SYSTEM_GROUP"
  else
    INST64_TARGET_OWNER="$BL64_VAR_DEFAULT"
    INST64_TARGET_GROUP="$BL64_VAR_DEFAULT"
  fi
  bl64_dbg_app_show_vars 'INST64_TARGET_OWNER' 'INST64_TARGET_GROUP'
}

function inst64_lib_target_normalize() {
  bl64_dbg_app_show_function
  local target="INST64_${INST64_APP_ID}_TARGET"
  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
    bl64_fs_path_permission_set \
      "$INST64_TARGET_MODE_FILE" "$INST64_TARGET_MODE_DIR" \
      "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" \
      "$BL64_VAR_ON" \
      "${!target}"
  fi
}

function inst64_lib_target_create() {
  bl64_dbg_app_show_function
  local target="INST64_${INST64_APP_ID}_TARGET"
  local method="INST64_${INST64_APP_ID}_METHOD"

  [[ "${!method}" =~ ^("$INST64_METHOD_AUR"|"$INST64_METHOD_NATIVE"|"$INST64_METHOD_PACKAGE"|"$INST64_METHOD_EXTERNAL"|"$INST64_METHOD_PIP"|"$INST64_METHOD_PIPX"|"$INST64_METHOD_UV"|"$INST64_METHOD_NPM"|"$INST64_METHOD_GO"|"$INST64_METHOD_FPAK"|"$INST64_METHOD_SNAP"|"$INST64_METHOD_KREW"|"$INST64_METHOD_BREW")$ ]] &&
    return 0

  bl64_fs_dir_create \
    "$INST64_TARGET_MODE_DIR" "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" \
    "${!target}"
}

function inst64_lib_target_populate() {
  bl64_dbg_app_show_function
  local target="INST64_${INST64_APP_ID}_TARGET"

  [[ -z "$INST64_WORK_PATH_SOURCE" ]] && INST64_WORK_PATH_SOURCE="$INST64_CLI_NAME"

  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    bl64_fs_path_copy \
      "$INST64_CLI_MODE" "$INST64_TARGET_MODE_DIR" \
      "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" \
      "${!target}" \
      "${INST64_WORK_PATH_STAGING}/${INST64_WORK_PATH_SOURCE}"
}

function inst64_lib_target_merge() {
  bl64_dbg_app_show_function
  local target="INST64_${INST64_APP_ID}_TARGET"
  local source=''

  if [[ -z "$INST64_WORK_PATH_SOURCE" ]]; then
    source="$INST64_WORK_PATH_STAGING"
  else
    source="${INST64_WORK_PATH_STAGING}/${INST64_WORK_PATH_SOURCE}"
  fi

  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    bl64_fs_path_merge \
      "${source}" \
      "${!target}"
}
