#!/usr/bin/env bash
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

function inst64_lib_staging_open_zstd() {
  bl64_dbg_app_show_function
  bl64_check_parameter 'INST64_WORK_PATH_STAGING' &&
    bl64_check_parameter 'INST64_PKG_MAIN' || return $?

  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    zstd -d \
      "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}"
}

function inst64_lib_staging_open_tar() {
  bl64_dbg_app_show_function
  bl64_check_parameter 'INST64_WORK_PATH_STAGING' &&
    bl64_check_parameter 'INST64_PKG_MAIN' || return $?

  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    bl64_arc_tar_open \
      "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}" \
      "${INST64_WORK_PATH_STAGING}"
}

function inst64_lib_staging_open_zip() {
  bl64_dbg_app_show_function
  bl64_check_parameter 'INST64_WORK_PATH_STAGING' &&
    bl64_check_parameter 'INST64_PKG_MAIN' || return $?

  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    bl64_arc_zip_open \
      "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}" \
      "${INST64_WORK_PATH_STAGING}"
}

function inst64_lib_staging_open_gz() {
  bl64_dbg_app_show_function
  bl64_check_parameter 'INST64_WORK_PATH_STAGING' &&
    bl64_check_parameter 'INST64_PKG_MAIN' || return $?

  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    bl64_arc_gzip_open \
      "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}" \
      "${INST64_WORK_PATH_STAGING}"
}

function inst64_lib_staging_open_7z() {
  bl64_dbg_app_show_function
  bl64_check_parameter 'INST64_WORK_PATH_STAGING' &&
    bl64_check_parameter 'INST64_PKG_MAIN' || return $?

  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    bl64_arc_7z_open \
      "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}" \
      "${INST64_WORK_PATH_STAGING}"
}

function inst64_lib_staging_open_bzip2() {
  bl64_dbg_app_show_function
  bl64_check_parameter 'INST64_WORK_PATH_STAGING' &&
    bl64_check_parameter 'INST64_PKG_MAIN' || return $?

  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    bl64_arc_bzip2_open \
      "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}" \
      "${INST64_WORK_PATH_STAGING}"
}

function inst64_lib_staging_create() {
  bl64_dbg_app_show_function
  INST64_WORK_PATH_STAGING="$(bl64_fs_create_tmpdir)"
}

function inst64_lib_staging_remove() {
  bl64_dbg_app_show_function
  bl64_fs_rm_tmpdir "$INST64_WORK_PATH_STAGING"
  return 0
}
