#!/usr/bin/env bash
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

function inst64_lib_show_docs() {
  bl64_dbg_app_show_function
  if [[ -n "$INST64_APP_DOC_SETUP" ]]; then
    bl64_msg_show_doc "Setup documentation: ${INST64_APP_DOC_SETUP}"
  fi
  if [[ -n "$INST64_APP_DOC_INSTALL" ]]; then
    bl64_msg_show_doc "Installation documentation: ${INST64_APP_DOC_INSTALL}"
  fi
  return 0
}

function inst64_lib_show_parameters() {
  bl64_dbg_app_show_function
  local parameter_list=''
  local method_variable_suffix=''
  local var_suffix=''
  local var_name=''

  parameter_list+=' BL64_OS_DISTRO'

  method_variable_suffix+=" ${INST64_APP_ID}_METHOD"
  method_variable_suffix+=" ${INST64_APP_ID}_PLATFORM"
  method_variable_suffix+=" ${INST64_APP_ID}_TARGET"
  method_variable_suffix+=" ${INST64_APP_ID}_VERSION"
  method_variable_suffix+=" BL64_OS_DISTRO"
  method_variable_suffix+=" BL64_OS_FLAVOR"
  method_variable_suffix+=" BL64_OS_MACHINE"
  method_variable_suffix+=" CLI_NAME"
  method_variable_suffix+=" CLI_PROMOTE"
  method_variable_suffix+=" GH_REPO_NAME"
  method_variable_suffix+=" GH_REPO_OWNER"
  method_variable_suffix+=" GIT_BRANCH"
  method_variable_suffix+=" GIT_REPO"
  method_variable_suffix+=" GIT_SERVER"
  method_variable_suffix+=" PKG_DEV"
  method_variable_suffix+=" PKG_MAIN"
  method_variable_suffix+=" OS_REPO_NAME"
  method_variable_suffix+=" OS_REPO_KEY_YUM"
  method_variable_suffix+=" OS_REPO_KEY_APT"
  method_variable_suffix+=" OS_SOURCE_APT"
  method_variable_suffix+=" OS_SOURCE_YUM"
  method_variable_suffix+=" REPLACE_INSTALLED"
  method_variable_suffix+=" REFRESH_PACKAGE_MANAGER"
  method_variable_suffix+=" SYSTEM_WIDE"
  method_variable_suffix+=" WEB_REPO_PATH"
  method_variable_suffix+=" WEB_REPO_URL"

  for var_suffix in $method_variable_suffix; do
    var_name="INST64_${var_suffix}"
    if [[ -v "$var_name" && -n "${!var_name}" ]]; then
      parameter_list+=" ${var_name}"
    fi
  done

  # shellcheck disable=SC2086
  bl64_msg_show_setup 'Installation parameters' \
    $parameter_list
}

function inst64_lib_show_step_prepare() {
  bl64_dbg_app_show_function
  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 1
  bl64_msg_show_phase 'prepare deployment'
  return 0
}

function inst64_lib_show_step_install() {
  bl64_dbg_app_show_function
  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 1
  bl64_msg_show_phase 'deploy application'
  return 0
}

function inst64_lib_show_step_setup() {
  bl64_dbg_app_show_function
  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 1
  bl64_msg_show_phase 'setup environment'
}

function inst64_lib_show_step_verify() {
  bl64_dbg_app_show_function
  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 1
  if [[ -z "$INST64_CLI_TARGET" ]]; then
    INST64_CLI_TARGET=${INST64_CLI_PATH}/${INST64_CLI_NAME}
  fi
  bl64_msg_show_phase 'verify deployment'
  bl64_msg_show_task "test application (${INST64_CLI_TARGET})"
}

function inst64_lib_show_task_download() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'download application assets'
  return 0
}

function inst64_lib_show_task_select_platform() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'determine target CPU architecture'
  return 0
}

function inst64_lib_show_task_select_packages() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'determine target package information'
  return 0
}

function inst64_lib_show_task_deploy() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'install application components'
  return 0
}

function inst64_lib_show_task_publish() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'publish application'
  return 0
}

function inst64_lib_show_task_cleanup() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'cleanup temporary files'
  return 0
}

function inst64_lib_show_globals() {
  bl64_dbg_app_show_function
  bl64_dbg_app_show_comments 'Global parameters'
  bl64_dbg_app_show_vars \
    'INST64_CLI_PROMOTE' \
    'INST64_DEBUG' \
    'INST64_LOCAL_BIN' \
    'INST64_LOCAL_ROOT' \
    'INST64_OPT_ROOT' \
    'INST64_REFRESH_PACKAGE_MANAGER' \
    'INST64_REPLACE_INSTALLED' \
    'INST64_SYSTEM_WIDE' \
    'INST64_TMP' \
    'INST64_USER_BIN' \
    'INST64_VERBOSE'

  bl64_dbg_app_show_comments 'Module ID'
  bl64_dbg_app_show_vars \
    'INST64_APP_FULL_NAME' \
    'INST64_APP_ID' \
    'INST64_APP_NAME' \
    'INST64_CLI_NAME'

  bl64_dbg_app_show_comments 'Module parameters'
  bl64_dbg_app_show_vars \
    "INST64_${INST64_APP_ID}_METHOD" \
    "INST64_${INST64_APP_ID}_PLATFORM" \
    "INST64_${INST64_APP_ID}_TARGET" \
    "INST64_${INST64_APP_ID}_VERSION"

  bl64_dbg_app_show_comments 'Method parameters'
  bl64_dbg_app_show_vars \
    'INST64_APP_INSTALLER' \
    'INST64_CLI_MODE' \
    'INST64_CLI_NAME' \
    'INST64_CLI_NORMALIZE' \
    'INST64_CLI_PATH' \
    'INST64_CLI_SOURCE' \
    'INST64_CLI_SUBPATH' \
    'INST64_CLI_TARGET' \
    'INST64_CPU_DARWIN_ARM64' \
    'INST64_CPU_LINUX_AMD64_GNU' \
    'INST64_CPU_LINUX_AMD64_MUSL' \
    'INST64_CPU_LINUX_AMD64' \
    'INST64_CPU_LINUX_ARM64' \
    'INST64_FPAK_REPO_NAME' \
    'INST64_GH_REPO_NAME' \
    'INST64_GH_REPO_OWNER' \
    'INST64_GIT_BRANCH' \
    'INST64_GIT_REPO' \
    'INST64_GIT_SERVER' \
    'INST64_OS_REPO_KEY_APT' \
    'INST64_OS_REPO_KEY_YUM' \
    'INST64_OS_REPO_NAME' \
    'INST64_OS_SOURCE_APT' \
    'INST64_OS_SOURCE_YUM' \
    'INST64_PKG_DEV' \
    'INST64_PKG_MAIN_PREFIX' \
    'INST64_PKG_MAIN_SUFFIX' \
    'INST64_PKG_MAIN' \
    'INST64_PKG_POST' \
    'INST64_PKG_PRE' \
    'INST64_WEB_FILE_SOURCE' \
    'INST64_WEB_FILE_TARGET' \
    'INST64_WEB_REPO_PATH' \
    'INST64_WEB_REPO_URL'

  bl64_dbg_app_show_comments 'Internals'
  bl64_dbg_app_show_vars \
    'INST64_LIB_VERSION_BL64' \
    'INST64_LIB_VERSION_REQUIRED' \
    'INST64_TARGET_REQUESTED' \
    'INST64_WORK_PATH_STAGING'

  bl64_dbg_app_show_comments 'External'
  bl64_dbg_app_show_vars \
    'INST64_BASHLIB64' \
    'INST64_COMMAND_FLATPAK' \
    'INST64_COMMAND_GO' \
    'INST64_COMMAND_NPM' \
    'INST64_COMMAND_SNAP' \
    'INST64_COMMAND_YAY'
  return 0
}
