#!/usr/bin/env bash
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

function inst64_lib_pkg_suffix_set() {
  bl64_dbg_app_show_function
  # shellcheck disable=SC2034
  case "$BL64_OS_FLAVOR" in
    "$BL64_OS_FLAVOR_ALPINE") INST64_PKG_MAIN_SUFFIX='.apk' ;;
    "$BL64_OS_FLAVOR_ARCH") INST64_PKG_MAIN_SUFFIX='.pacman' ;;
    "$BL64_OS_FLAVOR_FEDORA" | "$BL64_OS_FLAVOR_REDHAT") INST64_PKG_MAIN_SUFFIX='.rpm' ;;
    "$BL64_OS_FLAVOR_DEBIAN") INST64_PKG_MAIN_SUFFIX='.deb' ;;
    "$BL64_OS_FLAVOR_MACOS") INST64_PKG_MAIN_SUFFIX='.pkg' ;;
    *)
      bl64_os_raise_platform_unsupported
      return $?
      ;;
  esac
}

function inst64_lib_pkg_install() {
  bl64_dbg_app_show_function
  # shellcheck disable=SC2249
  case "$BL64_OS_TYPE" in
    "${BL64_OS_TYPE_LINUX}") inst64_lib_pkg_install_linux ;;
    "${BL64_OS_TYPE_MACOS}") inst64_lib_pkg_install_macos ;;
  esac
}

function inst64_lib_pkg_install_macos() {
  bl64_dbg_app_show_function
  bl64_pkg_run_installer \
    -target '/' \
    -pkg "$INST64_PKG_MAIN"
}

function inst64_lib_pkg_install_linux() {
  bl64_dbg_app_show_function
  # shellcheck disable=SC2086
  if bl64_lib_flag_is_enabled "$INST64_REFRESH_PACKAGE_MANAGER"; then
    bl64_pkg_prepare &&
      bl64_pkg_install $INST64_PKG_MAIN
  else
    bl64_pkg_install $INST64_PKG_MAIN
  fi
}

function inst64_lib_pkg_install_file() {
  bl64_dbg_app_show_function
  INST64_PKG_MAIN="${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}"
  inst64_lib_pkg_install
}

function inst64_lib_pkg_repo_add() {
  bl64_dbg_app_show_function
  local repository_url="${1:-}"
  local repository_key="${2:-}"
  local repository_apt_suite="${3:-}"
  local repository_apt_component="${4:-}"

  bl64_msg_show_task 'Add external package repository'
  bl64_pkg_repository_add "$INST64_OS_REPO_NAME" \
    "$repository_url" "$repository_key" \
    "$repository_apt_suite" "$repository_apt_component" ||
    return $?

  if ! bl64_lib_flag_is_enabled "$INST64_REFRESH_PACKAGE_MANAGER"; then
    bl64_pkg_prepare
  fi
}
