#!/usr/bin/env bash
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

function inst64_lib_offline_create_path() {
  bl64_dbg_app_show_function
  bl64_lib_flag_is_enabled "$INST64_OFFLINE_DOWNLOAD" || return 0
  bl64_check_parameter 'INST64_OFFLINE_TARGET' &&
    bl64_fs_dir_create \
      "$INST64_TARGET_MODE_DIR" "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" \
      "$INST64_OFFLINE_TARGET"
}

function inst64_lib_offline_check_method() {
  bl64_dbg_app_show_function
  bl64_lib_flag_is_enabled "$INST64_OFFLINE_DOWNLOAD" || return 0
  bl64_msg_show_error 'this installer does not support offline mode for the current method.'
  return "$BL64_LIB_ERROR_PARAMETER_INVALID"
}
