#!/usr/bin/env bash
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

function inst64_lib_command_run_go() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$INST64_COMMAND_GO" \
    "$@"
  bl64_dbg_app_trace_stop
}

function inst64_lib_command_run_npm() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$INST64_COMMAND_NPM" \
    "$@"
  bl64_dbg_app_trace_stop
}

function inst64_lib_command_run_yay() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$INST64_COMMAND_YAY" \
    "$@"
  bl64_dbg_app_trace_stop
}

function inst64_lib_command_run_flatpak() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$INST64_COMMAND_FLATPAK" \
    "$@"
  bl64_dbg_app_trace_stop
}

function inst64_lib_command_run_snap() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$INST64_COMMAND_SNAP" \
    "$@"
  bl64_dbg_app_trace_stop
}

function inst64_lib_command_run_uv() {
  bl64_dbg_app_show_function "$@"
  bl64_dbg_app_trace_start
  # shellcheck disable=SC2086
  "$INST64_COMMAND_UV" \
    "$@"
  bl64_dbg_app_trace_stop
}

function inst64_lib_command_define() {
  bl64_dbg_app_show_function "$@"
  local command_variable="${1:-}"
  local command_name="${2:-}"

  bl64_check_parameter 'command_variable' &&
    bl64_check_parameter 'command_name' ||
    return $?

  shift
  shift
  printf \
    -v "$command_variable" \
    '%s' \
    "$(bl64_bsh_command_locate_user "$command_name" "$@")"

  if [[ -z "${!command_variable}" ]]; then
    bl64_msg_show_error "the installer was not able to find a required command. Install it and try again (command: ${command_name})"
    return "$BL64_LIB_ERROR_TASK_REQUIREMENTS"
  fi
  return 0
}
