---
# Template: 1.0.0
name: "Test / GihHub"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  DEV_CICD_DEBUG: ""

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/**"
      - "test/bash/**"

jobs:
  test-github:
    runs-on: "macos-latest"
    strategy:
      fail-fast: false
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare environment"
        run: "./bin/dev-lib-base"

      - name: "Run OS specific tests"
        run: |
          source ./bin/dev-set
...
