---
# template: 2.8.0
name: "Test/Bash"

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  DEV_CICD_DEBUG: ${{ vars.DEV_CICD_DEBUG || 'NONE' }}
  DEV_CICD_DEBUG_BASH: ${{ vars.DEV_CICD_DEBUG_BASH || '' }}

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
      - "release/**"
    paths:
      - "src/**"
      - "test/bash/**"

jobs:
  test-bash-linux:
    runs-on: "ubuntu-latest"
    env:
      DEV_TEST_BASH_PATH_REPORT: "./logs/bash/bash-test-linux.log"
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        target:
          - "ARCH"
          - "ALM"
          - "ALP"
          - "AMZ"
          - "CNT"
          - "DEB"
          - "FD"
          - "KL"
          - "OEL"
          - "RCK"
          - "RHEL"
          - "SLES"
          - "UB"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Cache base tools"
        uses: "actions/cache@v5"
        with:
          path: |
            ./lib/bl64
            ./lib/inst64
          key: "dev-tools"

      - name: "Download tools"
        run: |
          ./bin/dev-lib-base

      - name: "Prepare for testing"
        run: "./bin/dev-prep-project"

      - name: "Run OS specific tests"
        run: |
          source ./bin/dev-set &&
          source ./bin/dev-env-bash &&
          ./bin/dev-test-bash $DEV_TEST_BASH_CONTAINER_${{matrix.target}} ${DEV_TEST_BASH_CASES}/${{matrix.target}}

      - name: "Run Linux generic tests"
        run: |
          source ./bin/dev-set &&
          source ./bin/dev-env-bash &&
          ./bin/dev-test-bash $DEV_TEST_BASH_CONTAINER_${{matrix.target}} ${DEV_TEST_BASH_CASES}/LNX

      - name: "Run Unix generic tests"
        run: |
          source ./bin/dev-set &&
          source ./bin/dev-env-bash &&
          ./bin/dev-test-bash $DEV_TEST_BASH_CONTAINER_${{matrix.target}} ${DEV_TEST_BASH_CASES}/UNX

      - name: "Save report as repository artifact"
        uses: actions/upload-artifact@v6
        continue-on-error: true
        if: always()
        with:
          name: "bash-test-linux.log"
          path: "./logs/bash/bash-test-linux.log"

  test-bash-macos:
    needs: "test-bash-linux"
    env:
      DEV_TEST_BASH_PATH_REPORT: "./logs/bash/bash-test-macos.log"
    runs-on: "macos-latest"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Upgrade Bash version"
        run: |
          ./bin/dev-lib-bash

      - name: "Cache base tools"
        uses: "actions/cache@v5"
        with:
          path: |
            ./lib/bl64
            ./lib/inst64
          key: "dev-tools"

      - name: "Download tools"
        run: |
          ./bin/dev-lib-base

      - name: "Prepare for testing"
        run: "./bin/dev-prep-project"

      - name: "Run OS specific tests"
        run: |
          source ./bin/dev-set &&
          source ./bin/dev-env-bash &&
          ./bin/dev-test-bash CONTAINER_MODE_DISABLED ${DEV_TEST_BASH_CASES}/MCOS

      - name: "Run Unix generic tests"
        run: |
          source ./bin/dev-set &&
          source ./bin/dev-env-bash &&
          ./bin/dev-test-bash CONTAINER_MODE_DISABLED ${DEV_TEST_BASH_CASES}/UNX

      - name: "Save report as repository artifact"
        uses: actions/upload-artifact@v6
        continue-on-error: true
        if: always()
        with:
          name: "bash-test-macos.log"
          path: "./logs/bash/bash-test-macos.log"
...
